### ISSUE TITLE
High memory usage on submit node in ipython: concat_variant_files

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1004]
In the workflow step `ipython: concat_variant_files` I see a sudden peak of high memory usage in the bcbio submit node (where `bcbio_nextgen.py` is started, so _not_ the actual ipython cluster worker nodes). The bcbio python process on the submit node usually takes about 1.5G of RAM during the whole `variant2` workflow, but at `ipython: concat_variant_files` I see that peaking to more than 8GB. 

The memory increase is actually in the python process itself, not in any externally called binary. Since python processes continue to take as much RAM as the peak requirement during the runtime of the process (garbage collection only allows re-use within the process, but memory is not not released back to the kernel), this means that bcbio will continue with that much required RAM.

This is a problem since it eats the resources on our puny submit nodes (I actually got terminated bcbio processes since main memory on the submit node was exhausted). Also it breaks users expectations for the submit node resource requirements and may possibly increase even more with more/deeper/WGS samples in the future. 

The data set where I encountered the problem where 300 deeply sequenced (20GB fq.gz/sample) WES samples. In case the high memory peak is expected and the submit node is supposed to deal with it the `multicore` way, I kindly suggest that whatever workflow step takes the memory is pushed to a worker node and that somewhere the resource expectations for that step are captured (in `bcbio_system.yaml`, for instance).

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for the detailed report and sorry about the issues. I'm a bit worried this is a consequence of some design decisions inside bcbio. From your description of the problem, the memory usage might be happening when bcbio tries to put together the objects for combining:

https://github.com/chapmanb/bcbio-nextgen/blob/73eb579e923a18f048f74d265717b06a2a062356/bcbio/distributed/split.py#L86

You might be able to confirm or deny by poking at that with your problem code.

If so, it's not really doing any processing but rather organizing the objects to pass into merging. Since we have those world objects, having 300 of them times the number of split regions can get higher.

This isn't the best overall design and the goal is to replace it with CWL and more sensible/lightweight messages passed around. I'll give a think on the code to see if I can improve it if this does appear to be the problem but generally wish this wasn't so ugly and would like to see a more general fix in place.

Sorry to not have an immediate fix but hope this discussion helps.

**Comment by schelhorn** [comment]
Thanks Brad, I'll look into that piece of code. If it really is the world objects, then we can't do anything about it. It would be a done of these objects, though, to generate 6+GB of strings in memory (world objects are just dicts strings and numbers, aren't they?). If it's something else I will reopen this issue. For now I am closing it. Thanks again.
