### ISSUE TITLE
libcurl-devel + homebrew gcc

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1008]
Hi!

Having issues installing bcbio-nextgen on a new machine (centos 7). 

With this command:
export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export SHELL=${SHELL:-/bin/bash} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install -v --env=inherit  --ignore-dependencies  git

The first problem is apparently solved by installing libcurl-devel on the machine, which might be a good idea to add to the requirements.

But then, this complaint arrives:

Error: The requested Homebrew GCC was not installed. You must:
  brew install homebrew/versions/gcc44 .

Trying this :
$ brew install homebrew/versions/gcc44
==> Installing gcc44 from homebrew/homebrew-versions
==> Installing dependencies for homebrew/versions/gcc44: gmp4, mpfr2, hom
==> Installing homebrew/versions/gcc44 dependency: gmp4
Error: homebrew/versions/gmp4 cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc

Trying this:
$ brew install gcc
==> Installing dependencies for gcc: zlib, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: zlib
Error: zlib cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
... and so on..

gcc 4.8.3-9 is the version installed on the system. I'm trying to get homebrew to point to gcc in /usr/bin/gcc, but I can't seem to figure out how. Any help is appreciated!

//Pär

**Comment by chapmanb** [comment]
Pär;
Sorry about the issues with the build. Are all of these errors coming from trying to build git, or another dependency? I pushed a fix that makes bcbio less aggressive about trying to install git since it seems to be leading to lots of issues. If you `rm -rf tmpbcbio-install` and then re-run your install/upgrade it should hopefully skip it now and build cleanly.

libcurl-devel is a required dependency and we currently list those here (https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#isolated-installations). Definitely let us know if we're missing anything else.

Hope this fixes your issues and gets things installing cleanly.

**Comment by lpantano** [comment]
Hi,

sorry about that. Sometime it happened to me. Don't not exactly the 
reason behind but this post helped me 
https://github.com/Homebrew/linuxbrew/issues/137. They say maybe is 
because you don't have the /usr/bin/gcc4.*. You will see some work around.

hope this help, or maybe @chapmanb has a better solution.

**Comment by parlar** [comment]
Great! 
I actually managed to move past this just now - but have no idea how I did it. Thanks, Ipantano. I'll take a look at that issue. I have another machine i have to install on as well.

Sorry, missed the libcurl-devel dependency (not actually doing an isolated installation.)

**Comment by roryk** [comment]
Looks like this got resolved-- @chapmanb has been a hero unwinding the `linuxbrew` dependencies in place of `bioconda` so hopefully we won't have these issues moving forward.
