### ISSUE TITLE
Bug in debug output for single-core fallback BAM sorting

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1022]
The fallback option for single core BAM sorting throws an error in the [except clause](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/bam/__init__.py#L361) (oh the irony) since three arguments are passed to the format string, which only accepts two arguments. Apparently no one but me has reached that buggy part of the code since November 2013, but having fallback sorting seems to have a _raison d'être_ as I now know.

**Comment by schelhorn** [comment]
Also, in the same except clause we'd require `order_flag = "-n" if order == "queryname" else ""`, since otherwise `samtools` will be feed the ordering option for `sambamba` from the clause before, and exit due to the unknown argument.

**Comment by chapmanb** [comment]
Sven-Eric;
Apologies about the out of date code, and the failures. I haven't seen multicore sambamba sorting errors in a long time so am not sure what the underlying issue is. In addition to fixing things so they'll actually work and run, it also logs errors so you might get a better picture of what is causing the problems in the first place. If that identifies other issues that need fixing please do let us know and we can resolve the underlying problem instead of just the workaround. Thanks much for reporting this.

**Comment by schelhorn** [comment]
Thanks Brad. Finding the cause for the sambamba failure wasn't the issue here anyway - I just wanted the code to be correct. It turned out to be a full temporary hard drive, so nothing to do with bcbio.
