### ISSUE TITLE
upgrades failed.

### ISSUE THREAD

**Issue by kspham** [chapmanb/bcbio-nextgen#1024]
Here is the last error message, probably related to some R packages. My R version 3.0.2 (2013-09-25
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (pcaPP)
ERROR: dependency ‘ks’ is not available for package ‘hdrcde’
* removing ‘/super/bcbio/lib/R/site-library/hdrcde’
ERROR: dependencies ‘hdrcde’, ‘ks’ are not available for package ‘rainbow’
* removing ‘/super/bcbio/lib/R/site-library/rainbow’
Fatal error: local() encountered an error (return code 1) while executing '/super/bcbio/anaconda/bin/Rscript /home/snow/tmp/cloudbiolinux/install_packages.R'

Aborting.

**Comment by kspham** [comment]
and there is an error before it: 
ERROR: dependencies ‘biovizBase’, ‘rainbow’ are not available for package ‘BubbleTree’
* removing ‘/super/bcbio/lib/R/site-library/BubbleTree’
Error: Command failed (1)

**Comment by chapmanb** [comment]
Son;
Sorry about the issue -- the BubbleTree installation is a bit more intense now as it requires rgl. We've started using our version of R included with bcbio (`/super/bcbio/anaconda/bin/Rscript` here) to install the dependencies but something appears to be missing here. I'd be happy to try and add this in if we can get more information about the underlying cause.

It looks like the `ks` package fails to installl, which causes the other chain of failures (`hdrcde` and then `BubbleTree`). Would you be able to post more of the installation log file as a Gist (https://gist.github.com/) so we can try to spot the underlying problem? If you could get everything from the start of the R installations that would be very helpful. Thanks much.

**Comment by kspham** [comment]
do bcbio-nextgen have a complete log file for the installation stored somewhere ?

**Comment by chapmanb** [comment]
Son -- thanks for sending the link to the log file offline. I pushed fixes to CloudBioLinux which I hope will resolve this. The underlying issue was build problems with some R libraries and the conda installed R package, along with a problematic installation of curl from conda. If you `rm -rf tmpbcbio-install` and re-run the upgrade it should hopefully finish cleanly now.

If you need to capture a log script in the future, bcbio doesn't write a log file but you can do this with `script`:
```
script bcbio-install.log
bcbio_nextgen.py upgrade ...
exit
```
Hope this gets things working for you.
