### ISSUE TITLE
How is the raw-regions.bed generated which is supplied to the L command in HaplotypeCaller?

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#1026]
I ran the Exome pipeline http://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#exome-with-validation-against-reference-materials as shown in the 'Getting Started' docs page. When I ran the pipeline without specifying anything for the variant_regions command I noticed that the regions specified in the raw-regions.bed file varied from sample to sample when running HaplotypeCaller. So for example for one sample a raw.regions.bed file generated was S7_L001-1_0_15530044-raw-regions.bed and for another sample a raw.regions.bed file  S8_L001-1_0_15558764-raw-regions.bed was generated which relates to a similar but not identical region. I looked through the commands.log file and could not see where these files are being generated. I would have assumed that by not giving a bed file no regions would be filtered out. Any help would be great.
Thanks

**Comment by chapmanb** [comment]
bcbio generates these regions based on the coverage, so the differences you see will be related to the edges of coverage blocks in different samples/captures. In general it's a good idea to use a BED file with exome/capture experiments since off-target calls aren't always reliable, but either way you'll see slight differences based on where you actually have callable regions to work with. Hope this helps explain the differences.

**Comment by kevjp** [comment]
Thanks for getting back to me. I have a very high coverage region where I have a deletion which is being missed out once I run it through haplotype caller. The region that is actually shown in the region.bed file overlaps exactly with the 9bp deleted region (X: 32717417 - 32717425)

![image](https://cloud.githubusercontent.com/assets/6606060/10040465/de8d95fa-61d3-11e5-9d20-ea46da9d6c74.png)

but once I run it through haplotype caller using -bamout argument the reads for this region are filtered out. I am unsure why this region is being filtered out. If I amend the bed file to widen this region to include the flanking regions of the deletion (X	: 32717350 - 32717490) then haplotype caller no longer filter these reads and the deletion is called as expected. Why do you think BCBIO is filtering this region? I am a little confused why it would do this. I think I have other examples where it is doing this but I would have to check.

Thanks
Kevin

**Comment by kevjp** [comment]
Also which part of the bcbio script generates the raw-regions.bed file? How does it determine what is included in a coverage block?

**Comment by chapmanb** [comment]
Kevin;
Thanks for the detailed example. That is definitely not the intended behavior and it sounds like the analysis block splitting around non-coverage regions is too tight in this interval, resulting in reads being lost. Apologies.

I pushed some fixes which I hope will improve this by increasing the size of blocks it uses to split on to 250bp and being more aggressive about filtering very small regions. I hope this will fix the issue here. You can try re-running on the same sample without realignment by doing:
```
bcbio_nextgen.py upgrade -u development
rm -f align/*/*-callable*bed
rm -rf regions
```
to remove the previous callability/regions calculations and use the hopefully improved ones.

All of the coverage block calculation happens here:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/bam/callable.py

It calculates coverage across the reads, then groups them into blocks trying to find shared regions of no coverage to parallelize across.

Please feel free to re-open this if the update doesn't fix your issue and happy to dig more. Thank you again for the helpful report.

**Comment by kevjp** [comment]
Thanks Brad
I tried to re-run the analysis after the new fix but I get an Import error.
```
/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/IPython/parallel.py:13: ShimWarning: The `IPython.parallel` package has been deprecated. You should import from ipyparallel instead.
  "You should import from ipyparallel instead.", ShimWarning)
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 35, in <module>
    from bcbio.distributed import runfn, clargs
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 11, in <module>
    from bcbio.distributed import multitasks
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 3, in <module>
    from bcbio import heterogeneity, structural, utils, chipseq, upload
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/__init__.py", line 10, in <module>
    from bcbio.heterogeneity import bubbletree, phylowgs, theta
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 21, in <module>
    from bcbio.heterogeneity import chromhacks, theta
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/theta.py", line 22, in <module>
    from bcbio.structural import cnvkit, convert
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 10, in <module>
    from bcbio.structural import (battenberg, cn_mops, cnvkit, delly,
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cn_mops.py", line 20, in <module>
    from bcbio.structural import shared as sshared
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/shared.py", line 17, in <module>
    from bcbio.bam import callable
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 26, in <module>
    from bcbio.distributed import multi, prun
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/prun.py", line 9, in <module>
    from bcbio.distributed import clusterk, ipython, multi, resources
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 31, in <module>
    from cluster_helper import cluster as ipython_cluster
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 22, in <module>
    from IPython.parallel import Client
ImportError: cannot import name Client
```
Thanks for making these changes by the way.
