### ISSUE TITLE
Run bcbio on multiple queues of the same Sun Grid Engine cluster?

### ISSUE THREAD

**Issue by WimS83** [chapmanb/bcbio-nextgen#1048]
Is it possible to run bcbio on multiple queues of the same Sun Grid Engine cluster?

I currently run bcbio on one queue:
bcbio_nextgen.py ../config/freebayes.yaml -t ipython -n 500 -s sge -q main 

and wonder if it is possible to run bcbio on multiple queues. If I currently try 
bcbio_nextgen.py ../config/freebayes.yaml -t ipython -n 1000 -s sge -q main,main2 

only the second queue specified, main2 is used for submitting jobs to. 

I think this is something that the underlying  qsub from the sun grid engine supports.

**Comment by roryk** [comment]
Hi @WimS83,

We don't currently have support for specifying multiple queues-- it might be possible to implement, but it might not be too useful. There is an assumption in the code that the compute that is available on a queue is fairly homogeneous. For example, we connect to a machine via the queue, determine what is available in terms of resources, make the assumption that the machines on the queue generally look like that and then scale resource requests based on that information. If the two queues have very different looking machines we'll end up being incorrect.

How does the multiple queues work with the parallel environments? Do you have to specify one for each queue or something like that? Do you have an example SBATCH script that works?

**Comment by WimS83** [comment]
Hi @roryk 

Google and qstat -pe my_pe tell me that you can have a PE over multiple queues. 

By default if you don't specify a queue, SGE qsub will submit your job to any queue that can process it. 

I thought that the node / job specification was picked up from galaxy/bcbio_system.yaml ? I did not know that there is some auto detection involved?

In my case I have two queues. One queue with regular machines and one with large machines that have more cpu and memory and a better mem / cpu ratio. 

The current job sizes (cpu and mem) that I specified in bcbio_system.yaml fit both the machines in the normal queue and in the large queue. 

I don't know what the auto detection involves but maybe you could also take the machines from the first queue as the minimal machine size and then also try to submit that size of jobs to the second queue? This is the case that a second queue is specified. 

I don't know what a SBATCH script is.

**Comment by schelhorn** [comment]
While I cannot offer a direct solution I'd like to add some notes that may be of help for devising a solution. We circumvent (or better, hack) a problem similar to yours by hard-patching [`cluster_helper.cluster`](https://github.com/roryk/ipython-cluster-helper/blob/master/cluster_helper/cluster.py#L237). For instance, for us it is crucial that the bcbio ipython `controller` job runs on a queue different from the queue for the ipython `engine` jobs due to the long run time of the former and the the fact that we would like to ensure that the controller is run on an queue just for AWS on-demand nodes rather than on a queue for spot nodes that distributes the engines. So you may have similar luck by just modifying the cluster_helper package in your installation and add the PBS flags that you were detailing to the corresponding SGE function there. Bcbio will then blindly use that.

In case that breaks the cluster discovery @roryk mentioned you can just add a file to your working directory at `provenance/ipython-QUEUENAME.yaml` I believe. Once you conducted a bcbio run via `bcbio_bextgen.py` this file will be created; you can modify it at will and copy it into the analogous directory for another bcbio run. If existing, bcbio will take the node resource information from that file when it is started without trying to discover the node resources again. In that manner you can simulate arbitrary node resources to bcbio, which can make sense if you have an heterogeneous cluster (like you may have due to multiple queues, and as we have due to the use of an AWS auto-scaling spot-cluster).

**Comment by roryk** [comment]
Hi @WimS83,

It picks up the resources from the `bcbio_system.yaml` file but it needs to figure out how many jobs it can submit to each machine. So if the machine has 64 cores but only 40 GB of memory, and the `bcbio_system.yaml` file is set up to take 16 cores per job and each job will take 20 GB of memory, it will only stick two jobs on that one machine. If the machines are super different across the two queues we'll end up making some bad calculations.

@schelhorn, I'd be super interested in adding support for your hack to `ipython-cluster-helper`. A patch maybe if github won't work?

**Comment by WimS83** [comment]
@schelhorn Thanks for your tip! I'll have a go at using that for our situation. 

@roryk Thanks for your answer. I would like to understand better why you choose to detect node size in the cluster and to reuse jobs/slots on machines in the cluster.

In my previous experience with cluster computing  I just made jobs  of a certain size (cpu +mem) so that every node could run one or more of those jobs. I subsequently submit all those thousands of those jobs to SGE and let the SGE scheduler figure out when and how many of those jobs to run on which nodes. 

Something like this for thousands of jobs:
qsub -hard -q main,main2,mainx,mainy -pe my_pe 16 -l h_vmem=20G,vf=20G

If there is  no machine in any queue that is large enough to run this type of job SGE returns a warning. For the rest SGE figures out the scheduling.

Seems to me that your are now doing something similar in your own scheduler. 

I am interested in knowing why you did not take the SGE scheduler approach but the one you currently do. I suspect there are many good reasons but I am just curious. Thanks.

**Comment by schelhorn** [comment]
Bcbio uses ipython parallel as a meta-scheduler; that has a couple of advantages like pipelining jobs, handling node-local resources that span multiple jobs, and real time logging. SGE only sees one controller job and a couple of engine jobs, the latter of which do the actual work and are renewed based on the parallel environment that the workflow uses in a particular stage. It's a little complicated and somewhat of an internal black box that isn't exposed to the end user, but what it comes down to is that cluster_helper is the interface between ipython and your SGE, and that it basically has one python class for controller and engines each, and that these classes issue PBS commands. So you could just hard code your second queue in there for the engine and you should be good to go. Ask engines and the controller have to end up in the same subnet though I believe, so you have your nodes set up to assure that.

**Comment by roryk** [comment]
Thianks @schelhorn and @WimS83. @schelhorn nailed it, `http://ipython.org/ipython-doc/dev/parallel/` has a more in depth description of how the parallelization works. We're hoping that at some point we won't have to do any of that anymore and have a company or another project handle the parallelization backend and just write bcbio-nextgen to use the CWL: https://github.com/common-workflow-language/common-workflow-language but none of that stuff is ready to go yet.

**Comment by WimS83** [comment]
Thanks @roryk  and @schelhorn . I appreciate very much the functionality already available in bcbio and will try to use the second queue in the way @schelhorn suggested.

**Comment by roryk** [comment]
Sweet, let us know if you run into any other troubles, closing out this issue for now.
