### ISSUE TITLE
Include genome coverage and off-target percentages in bcbio-summary

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1052]
As the title says, it would be nice to know at a glance how things stand, considering that these calculations are done already to determine the coverage type.

**Comment by lpantano** [comment]
Hi,

sorry about the delay. I think is a good idea and will add this tomorrow if it is not there already. It will help as well with some report we have.

thanks for the idea.

**Comment by lpantano** [comment]
Hi,

I added the pct for offtargets  https://github.com/chapmanb/bcbio-nextgen/commit/31eb30da9ac806bc68cf682f943e5df999da805f
when you say the coverage, are you thinking in a specific file already there, like one of the `callables`? we are doing a lot of coverage calculation when `coverage` is in the YAML file, but it would be good to have a singe number in the final project file. 
If you have some idea in mind, happy to implement it.

thanks

**Comment by lbeltrame** [comment]
In data mercoled� 14 ottobre 2015 07:22:37 CEST, Lorena ha scritto:

Hello Lorena,

> 3e5df999da805f when you say the coverage, are you thinking in a specific
> file already there, like one of the `callables`? we are doing a lot of

As I was discussing in the biovalidation ML, an indication of mean coverage 
per region, given we use chanjo already. Rory mentioned the 
"coverage_experimental" option, but at the moment this does not produce 
anything.

**Comment by lpantano** [comment]
Hi,
we don't use chanjo anymore. But we do the same calculations if you have the `coverage: bed file` in the YAML file, so i will add the average of the mean coverage per region parsing the file we produce inside `report/coverage`.

thanks

**Comment by lbeltrame** [comment]
I'll be testing this real soon (installing a new cluster for quick test runs, so finally I have an environment I can break ;), I'll let you know how it goes, and if it's OK, I'll close this report.

**Comment by lbeltrame** [comment]
Just checked the results: what's the unit of measure of "average coverage"? Because it's quite inconsistent with the (arguably much coarse) results I got by using bedtools. In an amplicon experiment it's not uncommon to have coverage in the thousands, while I get results like 70.xx.

Also, report is not generated for paired tumor-normal analyses (will open a separate report for it)

**Comment by lpantano** [comment]
Hi, 

it should be the average of the average coverage of regions. You could check the file that have that information. Should be inside `report/coverage/samplename_coverage.bed`. It is the column that says `meanCoverage`.

If numbers there are bigger, then I did something wrong parsing the file, if not, then we need to run manually the command we use and maybe compare to bedtools and see if they agree.

**Comment by lbeltrame** [comment]
Hello Lorena,

finally I managed to compare the results of the report with the one from qualimap.
For one targeted sample (2 genes, so we expect large changes), the YAML summary gives

```
avg_coverage_per_region: '159.205'
````
However, for the same sample, `qualimap` says there's an average coverage of 5362.54X and a standard deviation of 3775 (it was a not so good sample).

**Comment by lpantano** [comment]
Hi,
thanks for all this digging. It is really weird indeed. Could you check inside the working directory, inside `report/coverage` folder, what is the values for that column in the file that should correspond to this sample, like `sample2_coverage.bed` ? that will help to know if the problem is the parsing or sambamba tool.
thanks a lot for your time!

**Comment by lbeltrame** [comment]
I just checked: the number comes directly from the coverage file.

**Comment by lpantano** [comment]
Hi, thanks.
Any change you can give me a reduced bam files for one region, and the coordinates of that region where you know there are difference between bedtools and sambamba so I can dig into?
It would help a lot to find the source, because we had others that match, so maybe is something that affect only some cases.
If that is not possible, will try to find one myself.
thanks a lot again!

**Comment by lbeltrame** [comment]
Unfortunately those are patient data so I'm guessing it'll be hard to produce something that can be shared. However what I can tell you is this discrepancy was observed on an amplicon based library (coverage level "amplicon").

**Comment by lpantano** [comment]
hum, 
that's fine. You said that only two genes are there. So I am guessing you only have two lines in the `coverage.bed` file for that sample? can you post these two numbers? If they are supper difference maybe is just an effect because only there are two lines. Bcbio will do the average of that column. Maybe other tools calculate different the mean average and that's the reason, like the average of all bases on those two regions. Here, first you have the average of on region, and then the average of the average of the regions. Could that explain that? I don't have any other explanation right now.

I will try to check if number of reads for each region are equal between tools, maybe bedtools and what you see in `coverage.bed` file. That will help if the previous explanation doesn't match.

**Comment by lpantano** [comment]
Hi @lbeltrame, i think that maybe I have a hint here. `sambamba` is skipping regions when the coverage is higher to the value we use in the command line, in this case 200. I will try to add those regions downstream and see if that fixes the problem.

**Comment by lbeltrame** [comment]
That would be helpful: it's not unusual for targeted experiments, in particular if you only have a handful of genes, to go over thousands in coverage.

**Comment by lpantano** [comment]
Hi,

I increased the limit and those regions after that, so should be fine now.

thanks!
