### ISSUE TITLE
sambamba-view: Unable to write to stream

### ISSUE THREAD

**Issue by junchend** [chapmanb/bcbio-nextgen#1055]
Hi Brad,

Recently, I installed bcbio_nextgen in our cluster system and tried to analysis the DNA-seq (whole exome), I tested 10 samples with:

bcbio_nextgen.py ../config/YHY_WE.yaml -t ipython -s torque -n 320 -q high -r account=YHY  --tag YHY_WE

At the beginning, everything looks good, however, after recalibration, realign, error occurred:

[2015-10-09T07:22Z] TC3600.site: multiprocessing: combine_sample_regions
[2015-10-09T07:22Z] TC3600.site: Identified 203 parallel analysis blocks
Block sizes:
  min: 194499
  5%: 6186933.2
  25%: 15512766.0
  median: 15545366.0
  75%: 15737173.5
  95%: 16969187.9
  99%: 32936914.74
  max: 38219273
Between block sizes:
  min: 300
  5%: 521.4
  25%: 2280.0
  median: 8833.0
  75%: 53934.5
  95%: 702915.4
  99%: 2423742.98
  max: 4201459

[2015-10-09T07:22Z] TC3600.site: Timing: structural variation initial
[2015-10-09T07:22Z] TC3600.site: Timing: alignment post-processing
[2015-10-09T07:22Z] TC3600.site: ipython: piped_bamprep
[2015-10-09T07:45Z] node2: Uncaught exception occurred
Traceback (most recent call last):
  File "/public/home/juncheng/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/public/home/juncheng/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /public/home/juncheng/bcbio_install/bin/sambamba view -f bam -L /public/home/juncheng/YHY_WE/work/regions/WGC029878U-noanalysis_blocks.bed /public/home/juncheng/YHY_WE/work/align/WGC029878U/WGC029878U_2015-10-08_YHY_WE1-sort.bam | /public/home/juncheng/bcbio_install/bin/bedtools intersect -abam - -b /public/home/juncheng/YHY_WE/work/regions/WGC029878U-noanalysis_blocks.bed -f 1.0 -nonamecheck> /public/home/juncheng/YHY_WE/work/bamprep/WGC029878U/noanalysis/tx/tmp8U6ScN/WGC029878U_2015-10-08_YHY_WE1-sort-noanalysis-prep.bam
terminate called after throwing an instance of 'std::runtime_error'
  what():  BgzfStream::Write() - trying to write to non-writable IO device
sambamba-view: Unable to write to stream
/bin/bash: line 1: 12608 Exit 1                  /public/home/juncheng/bcbio_install/bin/sambamba view -f bam -L /public/home/juncheng/YHY_WE/work/regions/WGC029878U-noanalysis_blocks.bed /public/home/juncheng/YHY_WE/work/align/WGC029878U/WGC029878U_2015-10-08_YHY_WE1-sort.bam
     12609 Aborted                 (core dumped) | /public/home/juncheng/bcbio_install/bin/bedtools intersect -abam - -b /public/home/juncheng/YHY_WE/work/regions/WGC029878U-noanalysis_blocks.bed -f 1.0 -nonamecheck > /public/home/juncheng/YHY_WE/work/bamprep/WGC029878U/noanalysis/tx/tmp8U6ScN/WGC029878U_2015-10-08_YHY_WE1-sort-noanalysis-prep.bam
' returned non-zero exit status 134
[2015-10-09T07:45Z] node2: Unexpected error
Traceback (most recent call last):
  File "/public/home/juncheng/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 44, in _setup_logging
    yield config
  File "/public/home/juncheng/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 175, in piped_bamprep
    return ipython.zip_args(apply(bamprep.piped_bamprep, *args))
  File "/public/home/juncheng/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/variation/bamprep.py", line 145, in piped_bamprep
    data["config"])
  File "/public/home/juncheng/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 111, in write_noanalysis_reads
    do.run(cl.format(**locals()), "Select unanalyzed reads")
  File "/public/home/juncheng/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/public/home/juncheng/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /public/home/juncheng/bcbio_install/bin/sambamba view -f bam -L /public/home/juncheng/YHY_WE/work/regions/WGC029878U-noanalysis_blocks.bed /public/home/juncheng/YHY_WE/work/align/WGC029878U/WGC029878U_2015-10-08_YHY_WE1-sort.bam | /public/home/juncheng/bcbio_install/bin/bedtools intersect -abam - -b /public/home/juncheng/YHY_WE/work/regions/WGC029878U-noanalysis_blocks.bed -f 1.0 -nonamecheck> /public/home/juncheng/YHY_WE/work/bamprep/WGC029878U/noanalysis/tx/tmp8U6ScN/WGC029878U_2015-10-08_YHY_WE1-sort-noanalysis-prep.bam
terminate called after throwing an instance of 'std::runtime_error'
  what():  BgzfStream::Write() - trying to write to non-writable IO device
sambamba-view: Unable to write to stream
/bin/bash: line 1: 12608 Exit 1                  /public/home/juncheng/bcbio_install/bin/sambamba view -f bam -L /public/home/juncheng/YHY_WE/work/regions/WGC029878U-noanalysis_blocks.bed /public/home/juncheng/YHY_WE/work/align/WGC029878U/WGC029878U_2015-10-08_YHY_WE1-sort.bam
     12609 Aborted                 (core dumped) | /public/home/juncheng/bcbio_install/bin/bedtools intersect -abam - -b /public/home/juncheng/YHY_WE/work/regions/WGC029878U-noanalysis_blocks.bed -f 1.0 -nonamecheck > /public/home/juncheng/YHY_WE/work/bamprep/WGC029878U/noanalysis/tx/tmp8U6ScN/WGC029878U_2015-10-08_YHY_WE1-sort-noanalysis-prep.bam
' returned non-zero exit status 134

I searched the error message, it looks similar at github of bedtools2:

https://github.com/arq5x/bedtools2/issues/229

but no solution.

So could you pls check it?

bedtools version for bcbio_0.9.4 is 2.24.0, is it the point?

Thanks!

**Comment by chapmanb** [comment]
Sorry about the problem. I'm a bit unsure how to proceed given the issues Aaron and Neil had reproducing this. If you run the failing command outside of bcbio with:
```
/public/home/juncheng/bcbio_install/bin/sambamba view -f bam -L /public/home/juncheng/YHY_WE/work/regions/WGC029878U-noanalysis_blocks.bed /public/home/juncheng/YHY_WE/work/align/WGC029878U/WGC029878U_2015-10-08_YHY_WE1-sort.bam | /public/home/juncheng/bcbio_install/bin/bedtools intersect -abam - -b /public/home/juncheng/YHY_WE/work/regions/WGC029878U-noanalysis_blocks.bed -f 1.0 -nonamecheck> test.bam
```
Does it fail with the same problem every time? If so, what type of system are you running on?

Practically to get your work done, do you need re-calibration and re-alignment for your analysis? We typically skip these steps when using realigning callers. This would avoid needing to do this processing, which is pretty disk IO intensive.

Hope this helps.

**Comment by junchend** [comment]
Hi Brad, 

Thanks so much for your response, for the first running:

/public/home/juncheng/bcbio_install/bin/sambamba view -f bam -L /public/home/juncheng/YHY_WE/work/regions/WGC029878U-noanalysis_blocks.bed /public/home/juncheng/YHY_WE/work/align/WGC029878U/WGC029878U_2015-10-08_YHY_WE1-sort.bam | /public/home/juncheng/bcbio_install/bin/bedtools intersect -abam - -b /public/home/juncheng/YHY_WE/work/regions/WGC029878U-noanalysis_blocks.bed -f 1.0 -nonamecheck> test.bam

It can be go through, no error occurred.

Following your suggestion for the practical issues, the yaml should be:

details:
  - files: [ /public/home/juncheng/YHY_WE/input/WGC029878U_R1_trim.fq.gz, /public/home/juncheng/YHY_WE/input/WGC029878U_R2_trim.fq.gz ]
    genome_build: GRCh37
    lane: WGC029878U
    description: WGC029878U
    analysis: variant2
    algorithm:
      aligner: bwa
      coverage_interval: exome
      mark_duplicates: true
      merge_bamprep: true
      platform: illumina
      quality_format: standard
      realign: false
      recalibrate: false
      remove_lcr: true
      effects: vep
      variant_regions: my_custom_locations
      variantcaller: [ gatk, freebayes ]
      ensemble:
        classifier-params:
          type: svm
        classifiers:
          balance: [ AD, FS, Entropy]
          calling: [ ReadPosEndDist, PL, PLratio, Entropy, NBQ ]
        format-filters: [DP < 4]
        trusted-pct: 0.65

no realign and recalibrate needed? could you pls give me some suggestions for the analysis?

Thanks so much!

**Comment by chapmanb** [comment]
Thanks for the details. If running that command works cleanly, it was likely a temporary problem writing to disk. This could either be due to high IO load on the networked or local filesystem, or a temporarily filled up `/tmp` directory. Either way, another option is to re-run the same analysis and hope things are in a happier place for the second re-do.

But practically skipping the recalibration and realignment is a good choice to avoid the extra problems entirely. Your configuration looks good, but I'd suggest using `gatk-haplotype` instead of `gatk`. The new GATK HaplotypeCaller is much better than the old UnifiedGenotyper. You can also call with either freebayes or gatk-haplotype and leave out the ensemble section. For germline calling, both choices do well and there is not a ton of advantage of doing the extra work for ensemble calls. Hope this helps.

**Comment by junchend** [comment]
Thanks so much, to make it clear for practical issues:

only one variant caller is ok for germline mutaion? either gatk-haplotype or freebayes? I noticed that gatk-haplotype is time-consuming.

if I want to call somatic mutation for paired design (tumor vs normal), what's your suggestion?

following was the yaml I used:
 
 - files:
   - /newdata6/EC_WES/input/WGC040973_R1_trim.fq.gz
   - /newdata6/EC_WES/input/WGC040973_R2_trim.fq.gz
   genome_build: hg19
   description: S01-tumor
   metadata:
     batch: S01
     phenotype: tumor
   analysis: variant2
   algorithm:
     aligner: bwa
     coverage_interval: exome
     mark_duplicates: true
     merge_bamprep: true
     platform: illumina
     quality_format: standard
     realign: false
     recalibrate: false
     remove_lcr: true
     variant_regions: my_custom_locations
     variantcaller: [ mutect,freebayes ]
     indelcaller: [ pindel,sid ]
     ensemble:
         numpass: 2
 - files:
   - /newdata6/EC_WES/input/WGC040878_R1_trim.fq.gz
   - /newdata6/EC_WES/input/WGC040878_R2_trim.fq.gz
   genome_build: hg19
   description: S01-normal
   metadata:
     batch: S01
     phenotype: normal
   analysis: variant2
   algorithm:
     aligner: bwa
     coverage_interval: exome
     mark_duplicates: true
     merge_bamprep: true
     platform: illumina
     quality_format: standard
     realign: false
     recalibrate: false
     remove_lcr: true
     variant_regions: my_custom_locations
     variantcaller: [ mutect, freebayes ]
     indelcaller: [ pindel,sid ]
     ensemble:
         numpass: 2


Is it OK?

Thanks so much for your kindness!

**Comment by junchend** [comment]
Yaml foramt:

details:
 - files: [ /newdata6/EC_WES/input/WGC040973_R1_trim.fq.gz, /newdata6/EC_WES/input/WGC040973_R2_trim.fq.gz ]
   genome_build: hg19
   description: S01-tumor
   metadata:
     batch: S01
     phenotype: tumor
   analysis: variant2
   algorithm:
     aligner: bwa
     coverage_interval: exome
     mark_duplicates: true
     merge_bamprep: true
     platform: illumina
     quality_format: standard
     realign: false
     recalibrate: false
     remove_lcr: true
     variant_regions: my_custom_locations
     variantcaller: [ mutect,freebayes ]
     indelcaller: [ pindel,sid ]
     ensemble:
         numpass: 2
 - files: [ /newdata6/EC_WES/input/WGC040878_R1_trim.fq.gz, /newdata6/EC_WES/input/WGC040878_R2_trim.fq.gz ]
   genome_build: hg19
   description: S01-normal
   metadata:
     batch: S01
     phenotype: normal
   analysis: variant2
   algorithm:
     aligner: bwa
     coverage_interval: exome
     mark_duplicates: true
     merge_bamprep: true
     platform: illumina
     quality_format: standard
     realign: false
     recalibrate: false
     remove_lcr: true
     variant_regions: my_custom_locations
     variantcaller: [ mutect, freebayes ]
     indelcaller: [ pindel,sid ]
     ensemble:
         numpass: 2

**Comment by chapmanb** [comment]
Either gatk-haplotype or freebayes would be a good choice for germline calling. Both should have similar speed and HaplotypeCaller is much faster in the recent 3.4 release.

For somatic calling, I'd also start with a single caller, and use VarDict. So add `variantcaller: vardict` and remove the `indelcaller` and `ensemble` keys. VarDict calls both SNPs and indels sensitively and is also fairly fast.

Hope this helps.

**Comment by junchend** [comment]
Great!

Thanks so much, Brad, I will have a try!

**Comment by phu5ion** [comment]
Hi Brad,

I also met with the problem of sambamba not being able to write to stream. I don't think it is due to memory as I've tried increasing resource allocation to samtools in bcbio_system.yaml (from 16 core with 2GB memory to 32 core) but the run still fails. Is the tmp directory in the current working directory? If so it should have enough space too. I indeed did realignment and recalibration but am reluctant to set them to false and rerun the analyse as that will mean additional time. Could you advise on what I should do? 

The traceback is as follows:

[2016-09-13T04:09Z] multiprocessing: detect_sv
[2016-09-13T04:09Z] lumpyexpress : T180_080414
[2016-09-13T04:09Z] Sourcing executables from /home/hodl/local/share/bcbio/anaconda/bin/lumpyexpress.config ...
[2016-09-13T04:09Z]
[2016-09-13T04:09Z] Checking for required python modules (/home/hodl/local/share/bcbio/anaconda/bin/python)...
[2016-09-13T04:09Z]
[2016-09-13T04:09Z]     create temporary directory
[2016-09-13T04:09Z] Calculating insert distributions...
[2016-09-13T04:09Z] sambamba-view:  (Broken pipe)
[2016-09-13T04:09Z] Library read groups: T180_080414
[2016-09-13T04:09Z] Library read length: 100
[2016-09-13T04:11Z] sambamba-view: unable to write to stream
[2016-09-13T04:11Z] Removed 6962 outliers with isize >= 280
[2016-09-13T04:11Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/home/hodl/local/share/bcbio/anaconda/bin:$PATH && lumpyexpress -v -B /media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/align/T180_080414/T180_080414-sort.bam,/media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/align/N180_WBC/N180_WBC-sort.bam -S /media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/align/T180_080414/T180_080414-sort-sr.bam,/media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/align/N180_WBC/N180_WBC-sort-sr.bam -D /media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/align/T180_080414/T180_080414-sort-disc.bam,/media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/align/N180_WBC/N180_WBC-sort-disc.bam -x /media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/structural/T180_080414/lumpy/T180_080414-sort-180080414-svs-exclude.bed -T /media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/tx/tmpN6rJ_W -o /media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/structural/T180_080414/lumpy/tx/tmppprMX5/T180_080414-sort-180080414-svs.vcf
Sourcing executables from /home/hodl/local/share/bcbio/anaconda/bin/lumpyexpress.config ...

Checking for required python modules (/home/hodl/local/share/bcbio/anaconda/bin/python)...

    create temporary directory
Calculating insert distributions...
sambamba-view:  (Broken pipe)
Library read groups: T180_080414
Library read length: 100
sambamba-view: unable to write to stream
Removed 6962 outliers with isize >= 280
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/hodl/local/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script

  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script

  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 177, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 125, in run
    for xs in to_process.values()))
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 220, in detect_sv
    return structural.detect_sv(*args)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 144, in detect_sv
    for svdata in caller_fn(items):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/lumpy.py", line 125, in run
    lumpy_vcf, exclude_file = _run_lumpy(full_bams, sr_bams, disc_bams, work_dir, items)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/lumpy.py", line 45, in _run_lumpy
    do.run(cmd.format(**locals()), "lumpyexpress", items[0])
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/home/hodl/local/share/bcbio/anaconda/bin:$PATH && lumpyexpress -v -B /media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/align/T180_080414/T180_080414-sort.bam,/media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/align/N180_WBC/N180_WBC-sort.bam -S /media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/align/T180_080414/T180_080414-sort-sr.bam,/media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/align/N180_WBC/N180_WBC-sort-sr.bam -D /media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/align/T180_080414/T180_080414-sort-disc.bam,/media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/align/N180_WBC/N180_WBC-sort-disc.bam -x /media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/structural/T180_080414/lumpy/T180_080414-sort-180080414-svs-exclude.bed -T /media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/tx/tmpN6rJ_W -o /media/storage3/hodl/Projects/180/split_reads/structural_variants/bcbio/work/structural/T180_080414/lumpy/tx/tmppprMX5/T180_080414-sort-180080414-svs.vcf
Sourcing executables from /home/hodl/local/share/bcbio/anaconda/bin/lumpyexpress.config ...

Checking for required python modules (/home/hodl/local/share/bcbio/anaconda/bin/python)...

    create temporary directory
Calculating insert distributions...
sambamba-view:  (Broken pipe)
Library read groups: T180_080414
Library read length: 100
sambamba-view: unable to write to stream
Removed 6962 outliers with isize >= 280
' returned non-zero exit status 1

**Comment by schelhorn** [comment]
I have the same issue; this is a side effect of some recent bcbio code change since the configuration I chose worked for my last CNV-calling project. I disabled lumpy for now and the analysis completed.

**Comment by chapmanb** [comment]
Sorry about the issue with lumpy. We tracked this down to an issue in lumpyexpress and submitted a PR that fixes it. If you update lumpy with:
```
bcbio_conda install -c bioconda lumpy-sv
```
it will get you the latest version that should work correctly. Sorry again about the issue and hope this gets your analysis finished cleanly.

**Comment by phu5ion** [comment]
Hi schelhorn thanks for the heads-up and Brad thanks for fixing the problem! Seems to be working for now!
