### ISSUE TITLE
feature request: vcf-validator

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#1059]
This might be a useful step for multi-step variant calling. I still run into failed batch pipelines due to line truncation in vcfs. I'm assuming it's an environment issue so not much control except identify/purge/redo. 

https://github.com/EBIvariation/vcf-validator

**Comment by schelhorn** [comment]
+1

**Comment by chapmanb** [comment]
Daryl and Sven-Eric;
Thanks for the suggestions. I'm happy to incorporate more sanity checking. Right now, we're using GATK as an unofficial validator since running through GATK tools requires a well formatted VCF and I'd hope would catch line truncations and other issues.

Do you have a sense of what callers you get the truncated VCFs with, or at what point in the process? I'm trying to identify the best point to insert a validator to make it easier to catch or roll-back errors. Thanks again.

**Comment by lpantano** [comment]
Hi all,

I will close this guessing it's ok now.

Thanks!
