### ISSUE TITLE
RFC: Script to do a consistency check on the configuration prior to the analysis

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1070]
This should be already in because it's done when the pipeline starts, but IMO it would be good to have also as standalone: my use case is that the IPython cluster takes quite a bit to start up, and the check is only done afterwards, so if there are multiple issues in the configuration it's just a lot of time spent waiting.

Where's the code for this check at the moment?

**Comment by chapmanb** [comment]
Luca;
If you'd like to do this locally instead of on the cluster, the easy way is just to run `bcbio_nextgen.py your_config.yaml` without parallelizing on the local machine. The checking should be the first step so if it checks through this and proceeds to alignment then you know you're okay to submit the jobs to the cluster. It isn't currently build to run standalone beyond that, but the code for the check is here if that local run workaround doesn't work for you:

https://github.com/chapmanb/bcbio-nextgen/blob/10d744630f6392b5f537aea1df14c4907d15fdcd/bcbio/pipeline/run_info.py#L467

**Comment by lpantano** [comment]
Closing this since it seems it is solved.

thanks!
