### ISSUE TITLE
Do BAM files go in to the tmp dir? How much scratch space is needed for freebayes template?

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1110]
Hi,

Do BAM files go in to the tmp dir if one is specified for a freebayes template analysis?

resources:
  tmp:
    dir: $YOUR_SCRATCH_LOCATION

http://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#temporary-directory

So if I have 10 samples that will each produce bam files of 100GB, and I analyze 2 samples in parallel per cluster machine I need 400 GB scratch space per cluster machine? 200 GB for storing the bwa output BAM files and 200 GB for storing the de-duplicated bam files?

Is the BWA output BAM file deleted and the de-duplicated bam file moved to the working directory after de-duplication is finished?

Would is be possible to start creation of the coverage bed files directly after marking the duplicates? This to make use of the BAM file still being in the scratch dir and not in the working dir? 

This would also spread out the IO load of the bedtools stream trough bam files more. Because not all BAM files would be streamed at the same point in time. 

Thanks! 

Neill

**Comment by chapmanb** [comment]
Neill;
The temporary directory is used while file writes are in progress. When finished, the files get moved back to the work directory. bcbio streams alignment to de-duplication so there are not separate intermediate files for bwa and de-duplication and the expected needed temporary space is approximately that of each BAM file.

We don't currently have a way to run coverage on files in the temporary directory since those are separate steps and the finalized BAM file gets moved back to the shared space. Longer term we're working on supporting the common workflow language (CWL -- https://github.com/common-workflow-language/common-workflow-language)  which does not assume shared filesystems so we'll be able to make optimizations like that in the future. But that's still a work in progress.

Hope this helps -- feel free to reopen this if you need any additional details.

**Comment by NeillGibson** [comment]
Ok thank for you for the information.
