### ISSUE TITLE
Is there a log somewhere of how validate.py is run?

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#1111]
Thanks for making the change a538cecd86c0000d17d3f9d4f8ac9d2da04f9884
I can't see any record in the command log to show how validate.py is run. Would it be possible to include this somewhere?

**Comment by kevjp** [comment]
Thanks Brad
I have only just had a chance to look at this now so sorry for not getting back to you before this.
I have been looking at how indels are represented in my TP and FN files. The issues I have been having relate to indels where there is a deletion followed by insertion in the same region. So one example I found is reported in my truth set as: 

```
X	32404529	.	CTTT	C	.	.	.	GT	0/1
X	32404532	.	T	TAG	.	.	.	GT	0/1`
```
but the call was made in my test sample as:
```
X	32404529	.	CT	C
X	32404531	.	T	A
X	32404532	.	T	G
```
 rtg vcfeval quite correctly interpreted the two calls to be the same . In the TP file it counts the number of indels as 1 indel and 2 SNPs as  indicated by the way the call is made in the bottom example rather than 2 indels as shown in my truth set. This means that the totals in the summary.csv file relate to the calls made in the test sample rather than the truth set. For validation purposes it would be useful for the total to relate to the truth set but given that rtg provides the output in this format I am not sure there is an easy solution to re-format the output. What do you think?

**Comment by chapmanb** [comment]
Kevin;
Ah, that makes sense. Thanks for digging into this. I'm not sure if there is a straightforward way to get vcfeval to spit out the original representations in the truth set, instead of the called versions. This gets to be tricky from an outside perspective since vcfeval doesn't expose all the decisions underneath which help call these as identical. It might be worth asking @Lenbok on the RTG mailing list to see if he has any ideas:

https://groups.google.com/a/realtimegenomics.com/forum/#!forum/rtg-users

Sorry to not have a better approach right now but hope this helps.

**Comment by Lenbok** [comment]
Yes, the tp.vcf contains the called version of the TP variants but it is easy to get the truth versions. In the release version there is a flag `--baseline-tp` that will tell vcfeval to create an extra output file containing all the baseline variants that were matched, so you could use those if you want the indel vs snp determination of TP to be according to the truth set. 

Note that snp vs indel for FP must by definition be determined by callset representation, and similarly snp vs indel for FN must by definition be determined by baseline representation, which is one of the reasons why we've been reluctant to do such breakdowns as part of vcfeval -- it kind of depends on what you're looking at (e.g. from a caller-algorithm development perspective you mostly care about whether the caller thought it was snp vs indel).

As a heads-up though, in our upcoming release this additional output file will be produced by default and the `--baseline-tp` flag is being removed to keep things consistent with some other new functionality (primarily a new `--output-mode` flag that enables some new output styles, such as an "annotate" mode, a "combine" mode that gives a side-by-side view, and potentially a ga4gh mode for when running vcfeval as an engine inside hap.py). There'll be other new functionality at that point that you might want to consider making use of (you can get a peek on the rtg-tools dev branch, but I wouldn't recommend plugging that into bcbio just yet in case we decide to change some details of the new stuff before the release).

**Comment by chapmanb** [comment]
Len;
Thanks so much for the detailed breakdown of options. Apologies for missing the `--baseline-tp` flag, that sounds like exactly what we need. It sounds like it's worth waiting for the next release and plugging in the new generalized functionality instead of adjusting twice. When the new release is ready I'll tackle getting this all in for Kevin to do better reporting relative to the truth set. Thanks again.

**Comment by kevjp** [comment]
Thanks very much @Lenbok for your advice, ```--baseline-tp``` is exactly what I was after. Look forward to the new updates you plan to implement in the upcoming release. Thank you very much for looking into this.

**Comment by lpantano** [comment]
closing this since there has been several releases from that date.Hopefully that was solved.

thanks a lot!
