### ISSUE TITLE
Troubleshooting ensemble results -- Tribble error

### ISSUE THREAD

**Issue by sxv** [chapmanb/bcbio-nextgen#1112]
Hi,

After running several normal/tumor exomes through our bcbio pipeline, I noticed that some of the ensemble VCFs contained 30-40x more calls than the median number. Surprisingly, there was no corresponding spike in the individual callers' VCF outputs for the same samples. See line counts in this screenshot:

https://s3.amazonaws.com/f.cl.ly/items/0x3o2Y2l1e0m3h1v273G/ensemble-discrepancy.png

To determine the cause of these spikes, I attempted to reproduce ensemble VCFs using bcbio-variation-recall using the following command:

`/bcbio/bin/bcbio-variation-recall ensemble --cores=16 --numpass 2 --nofiltered ./ensemble.test.vcf /bcbio/genomes/Hsapiens/hg19/seq/hg19.fa ./mutect/21f-mutect.vcf ./varscan/21f-varscan.vcf ./freebayes/21f-freebayes.vcf ./vardict-java/21f-vardict-java.vcf`

which results in the following error:

```
java.lang.IllegalArgumentException: A reference dictionary is required for creating Tribble indices on the fly
```

Any advice appreciated. Thanks.

**Comment by chapmanb** [comment]
Sujay;
Thanks for the report and sorry about the issues. I'm not exactly sure what is going on with those ensemble outputs either. A useful debugging step would be to count the PASS variants in each of the individual callers. My guess would be that something is going on with the normals in the sames with many more ensemble variants. The ensemble variants are always PASS, while the individual callers will have a mix of PASS and filtered variants.

Regarding the bcbio-variation-recall error, my suggestion would be to pass bgzipped and tabix indexed VCFs instead of raw VCFs. My experience is that the htsjdk/Picard libraries have lots of intermittent issues with generating indexed from raw VCFs, but the bgzipped and index ones work cleanly. bcbio normally does this preparation work upstream of feeding to bcbio-variation-recall.

Hope this helps with debugging. Thanks again for the report and digging into the underlying issues.
