### ISSUE TITLE
IOError: Could not prepare index seq for hg38-noalt by any method

### ISSUE THREAD

**Issue by tomsing1** [chapmanb/bcbio-nextgen#1135]
Thanks a lot for making this pipeline available to the research community. 
Unfortunately, for ca. 48 hours now, I have run into the following error 

```
IOError: Could not prepare index seq for hg38-noalt by any method
```

when trying to install bcbio using the `bcbio_vm.py` script with the following command:

```
bcbio_vm.py --datadir=~/install/bcbio-vm/data install --data --tools --genomes hg38-noalt --aligners bwa
```

Please find the full error message attached:
[error.txt](https://github.com/chapmanb/bcbio-nextgen/files/50953/error.txt)

The same command worked a few days ago, so perhaps some of the reference file paths / names have changed?

**Comment by chapmanb** [comment]
Thomas;
Sorry about the problems with the data preparation. The hg38 support is still a work in progress and we're hoping to phase out the hg38-noalt target in favor of only supporting hg38. The remaining problem point is RNA-seq support with alts, but Rory has been making good progress on that. Would installing hg38 instead be an option for you? Let us know if this has any issues at all.

@roryk, do we want this to work for hg38-noalt, or can we start to deprecate that genome. We could leave basic support but skip anything extra and then remove it over time. What do you think?

**Comment by roryk** [comment]
Hi Brad and Thomas,

I'd love to deprecate no-alt. The outstanding issue is that with hg38 we lose the annotation of genes on the alt alleles when using the Ensembl gene annotation. The issue is that the alts are specified using two different sets of coordinates; Ensembl replicates the entire chromosome with just the alt region different and the UCSC builds we are using just have the alt portion with some annotation about where it should go. The coordinates don't entirely add up though, if you have any ideas about who might be a good person to talk to about translating between the two that would be super helpful.

I have runs of hg38 and hg38-noalt with the SEQC data that I haven't analyzed yet. If hg38 looks good even without having the alt gene annotations I think we will be able to go ahead and deprecate noalt.

**Comment by tomsing1** [comment]
Hi Bruce and Rory,

thanks a lot for your immediate response. Switching to hg38 fixed the issue and my installation works again. I am mainly interested in the variant calling workflow right now, so I am not blocked by the outstanding issues with RNA-seq. 

Sorry, I don't have any insights into how to translate the different coordinate systems at this point.
Thanks again for helping me get back on track with the installation!
Thomas
