### ISSUE TITLE
bcbio-nextgen update fails (gemini)

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1138]
running

```
/usr/local/share/bcbio/anaconda/bin/gemini --annotation-dir /usr/local/share/bcbio/gemini_data update --dataonly
```
gives the following error:

```
Command '['git', 'checkout', 'tags/v0.18.0\nv0.18.0a']' returned non-zero exit status 1
```

**Comment by schelhorn** [comment]
I have the same issue. I also see a `error: pathspec 'tags/v0.18.0
v0.18.0a' did not match any file(s) known to git.`.

**Comment by schelhorn** [comment]
So I removed and added `gemini` using `conda -c bioconda`, but to no avail. `gemini` itself is updated just fine, but the `gemini` install script errors out when calling `git` in `_update_testdir_revision` method at `subprocess.check_call(["git", "checkout", "tags/%s" % tag])`. Apparently some unit tests still are downloaded from the `gemini` github repository and fail due to some tagging problem. Perhaps the bioconda installation of `gemini` should try to do without the tests, since it makes using bioconda a lot less robust if it still depends on the git repo.

**Comment by schelhorn** [comment]
I commented out the call to `_update_testdir_revision()` in 
 `/bcbio/lib/anaconda/lib/python2.7/site-packages/gemini/gemini_update.py`, and the updater runs fine now.

**Comment by parlar** [comment]
Thanks!

**Comment by schelhorn** [comment]
Perfect, thanks @chapmanb.

**Comment by chapmanb** [comment]
Pär and Sven-Eric;
Thanks for the heads up on the problem. I pushed a fix to the conda package which should avoid this. If you do a `--tools` update before the next `--data` update it should get the latest version and hopefully work cleanly now. Thanks for all the patience as we transition over to a hopefully easier install process for GEMINI.

**Comment by lpantano** [comment]
Hi,

I will close this since it seems it worked! Please, if you find more problem feel free to open it again!

thanks for all your help!
