### ISSUE TITLE
cerntificate install issues present with installer

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1176]
With reference to a previous bugfix, the installer ```bcbio_nextgen_install.py``` is unable to use system wide SSL certificates. This was earlier corrected in ```bcbio_nextgen.py```.

**Comment by chapmanb** [comment]
Pär;
Sorry about the issues. Is this with the latest `bcbio_nextgen_install.py` script? What command line did you use and what traceback did you get?

We revamped the entire install process to use conda instead of pip so my hope was this problem is no longer present. The only place we use pip is to install the development version of bcbio from the GitHub repository, so I'm not sure if that's what triggers the issue here. Thanks for any additional details.

**Comment by parlar** [comment]
I lost the traceback (sorry) but everything seems to work after commenting out these lines:
```
    cert_file = os.path.join(anaconda["dir"], "ssl", "cert.pem")
    if os.path.exists(cert_file):
        os.environ["PIP_CERT"] = cert_file
```

**Comment by chapmanb** [comment]
Pär;
Thanks for the additional information. It looks like you have a slightly older version of the install script. If you get the latest, it no longer does that and should hopefully work cleanly for you:

https://github.com/chapmanb/bcbio-nextgen/blob/master/scripts/bcbio_nextgen_install.py

Hope this helps.

**Comment by parlar** [comment]
Thanks! I thought I did a fresh install using a new install file, maybe I managed to use an old file then.
