### ISSUE TITLE
Please create unique BAM ReadGroup identifiers in BWA+freebayes pipeline

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1198]
Hi,

Could you please create unique BAM ReadGroup identifiers in the BWA+freebayes pipeline?

Currently the ReadGroup is set to an auto increment number, ie . 
```
@RG     ID:1    SM:BATCH1_SM_1
to 
@RG     ID:999    SM:BATCH1_SM_999
```
This auto increment is reset at every BCBio run. Which conflicts with the unique RG requirement from the BAM spec. 

```
Read group identier. Each @RG line must have a unique ID.
The value of ID is used in the RG tags of alignment records. 
Must be unique among all read groups in header section. 
Read group IDs may be modied when merging SAM les in order to handle collisions.
```
https://samtools.github.io/hts-specs/SAMv1.pdf

This makes it impossible to variant call the combined group of BAM files produced by two BCBio alignment runs. 

BCBio run 1:
```
@RG     ID:1    SM:BATCH1_SM_1
@RG     ID:2    SM:BATCH1_SM_2
```

BCBio run 2:
```
@RG     ID:1    SM:BATCH2_SM_1
@RG     ID:2    SM:BATCH2_SM_2
```

If you try to variant call with freebayes the four above BAM files, the VCF output of freebayes has two samples instead of the four you would expect.  

This because of the conflicting ReadGroup identifiers. 

Could you therefore please use the sample name also as the ReadGroup identifier. As the sample name is (more) unique. Or maybe the combination of an auto increment and the sample name?

BCBio run 1:
```
@RG     ID:BATCH1_SM_1    SM:BATCH1_SM_1
@RG     ID:BATCH1_SM_2    SM:BATCH1_SM_2
```

BCBio run 2:
```
@RG     ID:BATCH2_SM_1    SM:BATCH2_SM_1
@RG     ID:BATCH2_SM_2    SM:BATCH2_SM_2
```

The version of BCBio I am using is 0.9.5a0 . 

Thank you!

**Comment by chapmanb** [comment]
Neill;
Thanks for the feedback. In the initial design the idea behind the ID mapping was to reduce size of files by keeping this small, since the read group ID is repeated on every line of the file. This is a big outdated now since we never deal with SAM directly and I believe bgzip compression will take care of this, so I'll revisit this as it would be useful to re-mixing processing as you suggest.

As a short term fix, the ID comes directly from an optional `lane` specification in the input:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#sample-information

so you can define this to be something unique if you're planning to combine inputs like this. Thanks again for bringing this up.

**Comment by NeillGibson** [comment]
Hi Brad, 

Thank you for the quick response! I could have found this myself in the documentation if had looked harder.  

A guaranteed unique RG ID ( hash key?) would facilitate remixing of the produced bam files with other bam files produced in other runs / workflows. 

Specifying a lane field & values in the sample CSV  to set the RG ID  in the sample configuration YAML will work.  

Thanks again for the quick answer. 



.

**Comment by chapmanb** [comment]
Neill;
Thanks again for this suggestion. This improvement had the highest ratio of testing (lots) versus lines of code changed (one) yet. Swapping over doesn't effect BAM file sizes on disk and doesn't change runtimes for full pipelines. Thanks for the great practical suggestion.

**Comment by NeillGibson** [comment]
Hi Brad thank you for the improvement.
