### ISSUE TITLE
MuTect2

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1203]
Hi Brad,
I have just seen that GATK 3.5 include a tool call Mutect2 .. I was just wondering if you are planing to include it in the DNA variant pipeline.

Thanks!

**Comment by chapmanb** [comment]
We'd definitely like to support MuTect2, although haven't yet had time to integrate or validate it. We'd love to explore it so as always happy to accept contributions if other folks have interest and tackle it before we do. Thanks much.

**Comment by apastore** [comment]
I would like to help... But I have to admit das bcbio is still a black box for me... could you explain where I could find the bcbio/variation dir in my isolate installation?

Thanks!

**Comment by apastore** [comment]
I have a mutec2 script for bcbio... how can I send a pull request? Thanks

**Comment by apastore** [comment]
I have create a new repository apastore/bcbio-nextgen-mutect2

**Comment by chapmanb** [comment]
Thanks so much for looking into this. I updated the documentation on developing and contributing to bcbio to try and help with all your questions:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/code.html#development-infrastructure

Please let us know if we could add anything here to help with this.

Practically, if you can make a fork of bcbio-nextgen with your MuTect 2 changes, then submit a pull request, we'd be happy to pull it in. That would give you credit in the history for your changes (rather than me trying to pull from your separate repository). Thank you again for doing this.

**Comment by apastore** [comment]
Thanks, got it!

**Comment by chapmanb** [comment]
merged in PR #1207
