### ISSUE TITLE
about using bcbio OptiType 

### ISSUE THREAD

**Issue by cenielyj** [chapmanb/bcbio-nextgen#1210]
I saw in the bcbio, we can use OptiType to do HLA typing.
However may I ask if I can use already mapped and SNP calling VCF to do that? which command should I use if I want to do so.
Thanks very much.

**Comment by chapmanb** [comment]
Thanks for the question. We do support OptiType HLA calling, and the process is:

- Align to the hg38 human genome to extract fastq reads in HLA regions.
- Pass extracted fastq reads in HLA subtypes to OptiType for the typing process

Since OptiType works from input fastq reads, not VCFs, there is not a short cut process working around the mapping in bcbio. Hope this helps.
