### ISSUE TITLE
If "phenotype: normal" is set for samples , part of the pipeline is not run even if it's not a tumor/normal run

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1249]
As the subject says: I recycled a template to do a germline analysis and forgot to leave "normal" out of the phenotypes. When the run completed, I realized that some steps (like GEMINI) did not get done, and "germline" data was being created, even. 

Removing the stray phenotype lines allowed the processing to continue once re-run.

**Comment by chapmanb** [comment]
Luca;
Sorry about the issues. We have a fix in place for this in the latest development version:

https://github.com/chapmanb/bcbio-nextgen/commit/3532fb666aa011dd2cbdae1e75044c627dfb2b2e

and hope to have a new release soon that includes it. The underlying issue was that bcbio assumed a tumor/normal pair when normal was specified and attached the combined variant call to the tumor sample. When this was missing, it did the analysis but did not pass the file on to downstream steps. Thanks much for the heads up and sorry about the confusion.
