### ISSUE TITLE
bowtie (1) sets quality format incorrectly

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1273]
Currently:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/ngsalign/bowtie.py#L17

```python

if qual_format is None or qual_format.lower() == "illumina":
        qual_flags = ["--phred64-quals"]
```
The behavior is the *opposite* of what the bowtie2 configuration does. I think it should be harmonized, and default like bowtie2 does.

cc @LMannarino who found this issue.

**Comment by chapmanb** [comment]
Luca -- thanks for the heads up on the bowtie problems. We haven't been giving bowtie 1 much love in the thought of deprecating it. I'm not sure of any use cases where we'd expect bowtie 1 to do better. Do you need it, or could your process work with bowtie2? If the later, we can start removing bowtie to avoid confusion.

**Comment by lpantano** [comment]
Hi, 
For small RNA, i am using bowtie in case people cannot use STAR, so for now I think this is the only case maybe still useful. Since small RNA are not that difficult to map, and the options and BAM flags are better in the case for (small RNA only). Maybe, if there is no any other case, we can add the restriction there to only be used with this pipeline.

**Comment by lpantano** [comment]
For now, I fixed that behavior. Are you using bowtie1 for something in particular?

**Comment by lbeltrame** [comment]
In data mercoled� 16 marzo 2016 14:20:40 CET, Lorena Pantano ha scritto:
> For now, I fixed that behavior. Are you using bowtie1 for something in
> particular?

For now we were just trying out different aligners to check for issues in our 
CHiP-seq data, but it turned out to be a completely different problem 
altogether.
