### ISSUE TITLE
Testing with NA12878-exome-methodcmp.yaml

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1287]
I ran the pipeline with example exome data. (in bcbio)

When I finished all job with NA12878-exome-methodcmp.yaml config file, I checked the last step and found the error in Rscript.

I think this issue cause some column missing.

My command is..
`$ Rscript NA12878-exome-eval/final/project_2016-03-23/report/qc-coverage-report-run.R`

The error line is..
(NA12878-exome-eval/work/report/report-ready.Rmd)

```
# Adjust some of the text information for formatting purposes
#qc_table <- qc[, metrics]
qc_table <- qc
```

**Error message**

> Quitting from lines 54-159 (report-ready.Rmd)
> Error in appendFormatter(x$options$rowCallback, columns, colnames, rownames,  :
>   You specified the columns: Average_insert_size, but the column names of the data are %GC, Duplicates, Duplicates_pct, Mapped_reads, Mapped_reads_pct, Median_insert_size, Name, Quality_format, Sequence_length, Sequences_flagged_as_poor_quality, Total_reads, Variations_total, mapped, offtarget, offtarget_pct, avg_coverage_per_region, sample
> Calls: render ... <Anonymous> -> formatStyle -> formatColumns -> appendFormatter

> Execution halted

**Comment by chapmanb** [comment]
Hyunmin;
Sorry about the error messages. Practically, bcbio should recover from these and finish cleanly -- the build of the report is a convenience but is currently optional. So if you don't need the report you can use the rest of the outputs without any problems.

If you need the report, @lpantano might be able to help more with fixing that. I believe there were some problems with the last release (0.9.6) which are fixed in development, so updating with:
```
bcbio_nextgen.py upgrade -u development
```
could fix it if you're running the release version. Hope this helps.

**Comment by lpantano** [comment]
Hi @hmkim,

sorry to be late. And sorry about the issue, some times it gives an error at that point depending on the data. 

We want that line to filter columns because other wise it will create a big table. Could you tell me what column are you missing from the following?  

```
metrics = c("sample", "Total_reads" ,"Mapped_reads_pct", "Duplicates_pct",
            "offtarget", "%GC", "Sequence_length", "Average_insert_size")

```

I moved the stats to use samtools and maybe have some conflicts with the stable version and the last report version. I will try to fix the report to try to avoid this error.

**Comment by hmkim** [comment]
I check this file.

NA12878-exome-eval/work/report/metrics/metrics.tsv

This file have an columns in below.

%GC     Duplicates      Duplicates_pct  Mapped_reads    Mapped_reads_pct        Median_insert_size      Name    Quality_format  Sequence_length Sequences_flagged_as_poor_quality       Total_reads     Variations_total        mapped  offtarget       offtarget_pct   avg_coverage_per_region sample

**missing 'Average_insert_size' **

Thanks in advance!

**Comment by lpantano** [comment]
Hi,

yep, sorry, that was the changed. you can update bcbio and run again (you will need to remove the reports as well) to get the new tables. Or just change that by "Medium_insert_size".

As well I tried to update the package that generates the report to try to be compatible with both versions, so if you update the tools, maybe this error disappears. 

This report can have some problems with some analysis and I am trying to handle all the situation. So if you try to run with the new version or in your future analysis, let me know what you find.

As well, I found some problems when there is only one sample, I am trying to figure out how to handle that.

thanks!

**Comment by lpantano** [comment]
Hi,

we have turned off the render of the report until we have it in a better shape.
This report is really useful mainly when you turn on `coverage` option in your YAML file. If at some point you need it, just try to render manually the report if we couldn't get a stable version at that point.

I pushed a new version and fixed some of the problems. So feel free to try, but works better with many samples. Please, open a new issue for the report problem if this persists.

Thanks a lot!

**Comment by hmkim** [comment]
Thanks for your support.

I'll try to run with some example data, and I'll report it if I get the error.
