### ISSUE TITLE
query on incremental calling

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#1315]
After several rounds of batch/joint calling I'm scoping a more sane incremental caller. 

1) Any chance this is on the development plans for bcbio?

2) Does bcbio support freebayes gvcf output? Wasn't sure if it stabilized. 

3) Can gvcf's be directly input into the joint calling pipeline? i.e. as paths in the metadata file.

**Comment by chapmanb** [comment]
Daryl;
Sorry about the joint calling issues. Are you having trouble with the current freebayes joint calling? It is imperfect and disk intensive. We do currently support FreeBayes gVCF output but don't yet have a method for combining gVCFs into a final output. We're hoping to use GLnexus for this when it's available and have a full discussion in #1134

Is using gatk-haplotype joint calling an option for you? That uses gVCFs and should scale cleanly.

We don't have a way to inject gVCFs directly into the pipeline. That's something we'd like to tackle but have to think about how it works with general gVCFs (since GATK gVCF and FreeBayes gVCF are not identical) so that would probably be something to look at after supporting a general gVCF merging approach for all joint calling.

Hope this helps.

**Comment by dwaggott** [comment]
Thanks!
