### ISSUE TITLE
higher number of cores used than specified on command line

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#1318]
I used the `-n 96` option to specify the number of cores used on a small SGE cluster with two nodes, 64 cores each. Bcbio starts 6 engines with 16 cores/slots each. This is used for a while, but then it reconfigures itself, and now seems to have started 7 engines with 15 cores/slots each, so 105 in total, which is larger than what I have specified. Only 6 engines are running, and one more is queued and waiting, but I have no idea why this is happening.

Is this expected? Maybe we have some SGE configuration problem?

**Comment by chapmanb** [comment]
Endre;
At the second stage it does a different memory allocation strategy so likely finds it can only schedule 15 cores per block (of 16 cores) with the memory specification. Since 15 * 6 < 96 it schedules the higher number to get you at least 96 cores. The processing will run fine even if all engines don't get scheduled, so the thought process is to give at least as many cores as you wanted, rather than less. Is this a problem, or were you just worried about the allocation logic here? Happy to think about options if it's causing issues.

**Comment by razZ0r** [comment]
No problem if this is expected, I was just wondering about the logic behind it. Thanks for the clarification.
