### ISSUE TITLE
Revert to cramtools 2.1

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1321]
I am using the `cram` compression option in bcbio for archival of the alignment. Using `cramtools 2.1` this goes smoothly; however, bcbio now seems to install `cramtools 3.0-b47`, which fails with `Unknown read or base category: i` error when running the bcbio builtin conversion. This `cramtools 3` seems to have other issues as well, for instance here https://github.com/enasequence/cramtools/issues/48 where it forces one to retain read names even if it is specified to omit them. The `cramtools` people are working on it, but the issue is still open. I therefore suggest to revert to the working `cramtools 2.1` version that is in homebrew until all issues are fixed.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for reporting this and sorry about the issues. Do you think it's worth trying out the latest cramtools 3.0 before reverting? I'm a bit nervous about moving backwards with CRAMs continued evolution and there have been a few changes since b47, and this could also be due to bcbio being out of date. I could bump this to the latest and update bcbio CRAM support first to see if that resolves it. Would that work for you?

**Comment by schelhorn** [comment]
Sure, let's try that first. I'm a little doubtful since `cramtools` development doesn't seem to be overly active, but of course we should try to go with the current major release. I'll can test tomorrow.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks much. I bumped to the latest version of cramtools if you update. Fingers crossed. I also did some cleanup of bcbio and where we use cramtools. If this is still an issue we could try switching over to `samtools view` for BAM to CRAM conversion. The only downside is that I don't believe samtools has a way to do quality score binning so we'd lose that functionality to help reduce file sizes. Thanks for looking at this.

**Comment by schelhorn** [comment]
So the new cramtools version seems to require Java 8 (Java error is `unsupported major.minor version 52.0`). Bcbio comes with Java 7. I'll stick with cramtools 2x for now but I'm fine with monkey patching that in myself if need be.

**Comment by schelhorn** [comment]
I'd recommend going with `samtools view`, though - it will be better supported in the future and also the quality binning will be added later on by the devs, from what I heard.

**Comment by chapmanb** [comment]
Sven-Eric;
Sorry about the continued problems. I agree, I'd rather have stable CRAM output we can trust rather than quality binning for size reduction. Hopefully that'll come to samtools soon as well and we can add it in. I pushed this fix so the latest development should hopefully work cleanly on your example. Let me know if you run into anything else with this.

**Comment by schelhorn** [comment]
Great; there may be a chance to add binning back in right now by piping from `bamUtil squeeze` into `samtools`. That would also allow replacing read names with integers to go down to 20% size or so. But that also depends on the additional effort for maintaining that new binary, of course. See here: http://genome.sph.umich.edu/wiki/BamUtil:_squeeze At least it is actively maintained: https://github.com/statgen/bamUtil
