### ISSUE TITLE
picard metrics from bcbio

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio-nextgen#1335]
Hi Brad and others,

When I tried to look more into the code I see that there is code implemented to parse different picard metrics. We are mostly interested in hsmetrics. The new version of bcbio no more places those results in the align folder. How can get them? Should we be writing our own code to pull those?

Thanks,

Diya

**Comment by chapmanb** [comment]
Diya;
Thanks for the suggestions and thoughts. We don't currently run Picard metrics in bcbio -- they'd been removed primarily due to speed issues. I do agree that HsMetrics has some useful stats that it might make sense to include for capture experiments. @lpantano has been refactoring the bcbio QC to use MultiQC:

https://github.com/ewels/MultiQC

which supports parsing and including these in the report. Maybe we should think about re-including this, or trying to get equivalent statistics with Qualimap. Happy to discuss more about how best to do this.

**Comment by lpantano** [comment]
Hi,

I am happy to include other metrics here. I wasn’t here when bcbio was using that, but if you tell me kind of metrics you would like, I can dig into different tools to get them.

cheers

**Comment by DiyaVaka** [comment]
Thank you Brad and Ipantano.

I agree that having picard run will have speed issues. We ourselves faced it while we were using the older version of bcbio. Even if there are other tools to calculate the coverage and other stats which picard hs metrics provides we are more than happy to use them. We are mainly interested in getting the hs metrics (On bait bases, near bait bases, off bait bases, mean bait coverage, on target bases, mean target coverage, 10x coverage targets, zero coverage targets, fold enrichment).

We did try to run multi qc on our sample. I see it has few basic stats and figures from fastqc report. It is a good report but that won't be sufficient for our clients.

**Comment by tanglingfung** [comment]
ngscat appears to be a faster alternative, with useful metrics:
http://www.bioinfomgp.org/ngscat

Hope it helps.

**Comment by lpantano** [comment]
Thanks.

I am currently working in getting coverage metrics, mean coverage, 10x coverage targets and similar. That would be in the next version of multiqc, I hope to add these features in the next week. 
I will try ngscat, but the web is not working right now. 
I guess off bait bases are off-target reads (meaning reads outside the target regions)? this should be in multiqc, the others related to target regions will come shortly and I can add more metrics since we calculate the data.  As well, if you did variant calling, it would have number of variants detected, known variants, other similar stats. As well, it would plot coverage ~ variant relationship, and CG content as well. In general should be quite better for stats related to variant calling pipeline and showing the targeted regions enrichment.

**Comment by DiyaVaka** [comment]
Awesome. Can we expect the hs metrics results to be available by the end of the month? Since we are already using the stable version bcbio how can we upgrade just a single tool?

**Comment by tanglingfung** [comment]
@lpantano , your list is better.. I guess you don't need to bother with ngscat in that case.

And I like your metrics on the variants, I wonder if you will separate the figures for somatic and germline variants.

**Comment by lbeltrame** [comment]
For the record, I would not recommend TEQC because it has (used to have?) huge issues with parsing BAM files with different chromosome names ("chr1" vs "1").

**Comment by tanglingfung** [comment]
Thanks Luca, it's good to know.

**Comment by DiyaVaka** [comment]
Hi lpantano,

Just checking back with you if the stats from picard program are implemented in your multiQC report? Please let me know if this takes longer, we can implement picard in our master piepline to generate them for our researchers.

Thanks,

Diya

**Comment by lpantano** [comment]
hi

i implemented multiqc-bcbio, that will try to adapt our metrics to multiqc. 
you will need to update tools and probably the dev version of bcbio or wait to the next release. 

But to have coverage information you will need to add to the yaml
file the coverage option pointing to a bed file with regions. Can be all the regions of your capture or anything.

As well, if you add tools_on: [qualimap_full] you should get 
that into multiqc.

You can check if this is enough and work together to add more information you are missing or/and you can add picard as a backup
plan.

I will continue adding metrics to QC, and will try not to be dependent on bcbio develop code but stable version in the future, but i needed to do some low level changes. 

cheers

sent not from my computer

**Comment by DiyaVaka** [comment]
Hi Ipantano,

Thanks for the metrics. It took us long to go through all the data generated from the report. When we compare our recent reports with the previous ones we are still missing off bait, near bait percentages, and zero coverage metrics. Are we not running picard metrics to get all the stats?

It would be a great help if we can derive these through qulaimap and multiqc reports as you guys are already getting lot of information from different tools. If not then we need to run picard independently just for these.

**Comment by lpantano** [comment]
Thanks for the feedback!, I will talk to Brad to get a plan how to integrate these missing metrics.

**Comment by DiyaVaka** [comment]
Hi Ipantano,

I see there is offtarget percentage in one of the multiqc report file. Does this mean off bait percentage? 

Thanks,

Diya

**Comment by lpantano** [comment]
i think so. Is the reads outside the target regions you used for the analysis.

**Comment by lpantano** [comment]
Hi,

I think we cannot get near bait percentages if that means reads around the target regions right now.
Could you tell me exactly what is zero coverage metrics? If it is target with 0 reads, I can add that because we calculate the coverage for all the regions, so that would be easy to add as table or numbers.

thanks for helping with that.

**Comment by chapmanb** [comment]
Lorena and Diya;
I think the best approach would be to have a pluggable option to run Picard HsMetrics:

https://broadinstitute.github.io/picard/picard-metric-definitions.html#HsMetrics

and then ensure this gets integrated into the QC report. Diya, this is definitely something we'd like to work on as we continue to revamp the QC module to be more generic. If there are other equivalent reports for hybrid capture happy to consider those instead of Picard.

**Comment by lpantano** [comment]
it makes sense. Multiqc has already the module for parsing HsMetrics, so we just need to add a option to run picard.

**Comment by DiyaVaka** [comment]
Thank you Lorena and Brad.

% Zero coverage is "targets which have no reads". I see there is a off target percentage in metrics.tsv file from the report folder. When we add off target and on target percentage, and subtract it from the 100% we get near target %. So for now we should be good with that. Getting the zero coverage solves the issue.

I definitely go with brad, for future we can have picard as a pluggable option. 

Thank you both.

Diya

**Comment by DiyaVaka** [comment]
Hi Brad and lorena,

When we look at the qualimage report I see that been generated by using sort.bam file.

Your previous version report was based on recalub.realign.bam file.

Does it make more sense to have the report numbers on the recalib.realign bam file?? Previous you guys provided us with this bam. Now we no more see those intermediate files in bcbio align directories.

Either we need to have this bam file to do the stats ourselves or can you guys make qualumap use that bam file before they get deleted??

Thanks,

Diya

**Comment by chapmanb** [comment]
Diya;
We did switch over to using the standard aligned BAM file for quality control. The recalibrated/realigned BAM will still be produced, and saved in the output directory, if you have `recalibrate: true` and `realign: true` in your algorithm configuration.

We prefer using the aligned/de-duplicated BAMs, instead of the post-processed ones, for consistency between analyses. We generally don't use recalibration and realignment for standard runs. Either way, you shouldn't expect a lot of differences in results between these two so hopefully it won't impact any of your interpretations and downstream analysis. Hope this helps.

**Comment by DiyaVaka** [comment]
Hi Brad,

Thanks for your answers. Yes, we do use them in our sample.yaml file, but still we donot see them in the output folder.

**Comment by chapmanb** [comment]
Diya;
The `sample/sample-ready.bam` file in your output folder should be the realigned/recalibrated BAM file. We don't store two separate files (aligned only, plus this) to avoid disk space concerns. In general we like to have as few copies of BAM files around as we can. Hopefully that provides what you need.

**Comment by DiyaVaka** [comment]
Thank you Brad

**Comment by lpantano** [comment]
Hi,

picard metrics now can be integrated with multiqc in the next version, and picard can be run with bcbio if it is in `tools_on`.

hopefully this will help you. We continue working to get the report as complete as possible with the default QC tools though.

**Comment by DiyaVaka** [comment]
Awesome. Will definitely give it a try for our next run. Thanks a bunch

**Comment by lpantano** [comment]
Hi,

I will close this, but feel free to open if still what we have is missing some parts. 

Thanks!
