### ISSUE TITLE
PYTHONPATH 

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1347]
Hi!

On my machine PYTHONPATH is automatically set, I think because of updates. Perhaps there are others in this situation? Would it be a bad idea just include ```os.environ["PYTHONPATH"] = ""``` in the bcbio_nextgen.py script?

cheers

**Comment by brainstorm** [comment]
Hello @parlar,

Good question! Nowadays the standard python sites (both developers and users) use "virtual environments" that isolate python and system-related environment variables, including `PYTHONPATH`.

We think that resetting `PYTHONPATH` would be quite intrusive/aggressive and in our experience (yes, I tried), it breaks more than fixes.

Please consider using virtual environments by Anaconda (our favorite):

http://conda.pydata.org/miniconda.html

Or venvs:

https://virtualenv.pypa.io/en/latest/

Hope that helps!

**Comment by chapmanb** [comment]
In addition to Roman's good suggestion for conda, we also run bcbio_nextgen.py with:
```
bcbio_python -Es
```
which should ignore PYTHONPATH and the local user site directory, to try and avoid issues with overlapping with existing installation. Python sometimes includes libraries despite this due to unknown reasons (at least to me) but this catches most cases. Hope this helps.
