### ISSUE TITLE
Small RNA pipeline - issue with SeqCluster

### ISSUE THREAD

**Issue by AurelieMLB** [chapmanb/bcbio-nextgen#1353]
Hello,

I am trying the new smallRNA seq analysis pipeline of bcbio.
My understanding is that it does run seqcluster and I do get a folder with this nam in work. But from the documentation I was expecting a reader.html file which is not there at all (https://github.com/lpantano/seqcluster, http://seqcluster.readthedocs.org/more_outputs.html#report ). 
In the html folder (under seqcluster ) I do get an index.html file and there are also folders for clusters but they are all empty so I am not sure this worked till the end.

Would you see any reason this would happen please?
Something must have gone wrong at some point because the seqcluster folder is not appearing in the final folder.

Many thanks for any help
Aurelie

**Comment by lpantano** [comment]
hi,

sorry about this. can you send me the files inside the log folder and i will take a look to the problem and the tdemapper as well.


sent not from my computer

**Comment by AurelieMLB** [comment]
Hello,

Apologies about the delay.
Please find the log folder attached.

Just to mention : the issues 1351, 1352,1353 are referring to the same run with the same samples in input. I did add a comment on the 1351 this morning after it was closed.
It might be relevant for you to know that for a lot of samples I did not get much reads and it seems that the trimming is removing a lot... maybe too much. I used the option "adapters: truseq". I am thinking that this might lead to too much null results and so cause the pipeline to fail ?

Many thanks for your help
Aurelie

[log.zip](https://github.com/chapmanb/bcbio-nextgen/files/229765/log.zip)

**Comment by lpantano** [comment]
hi, 

i will look at the files, bit for sure you need a specific 3' adapter sequence for the small rna library. Normally the people who did the library know which is. I can send you the standard later, but if you get few reads after that, this normally is the problem.

I will try to add some more useful message during the pipeline if this is the case.

sent not from my computer

**Comment by lpantano** [comment]
Hi, 
normally this is the one I use: TGGAATTCTCGGGTGCCAAGG, not sure it could be this.
Also, I see an error, that probably is causing that everything goes to short sequences, because adapter is expecting a sequence not a word, like this: `adapters: ["TGGAATTCTCGGGTGC"] `

**Comment by AurelieMLB** [comment]
Hi,
OK. I did ask for the specific adaptor sequences that have been used. But int the meantime, I will try to re-launch with your sequence, just to see if everything run till the end. I will keep you updated asap.

Thanks a lot !

**Comment by AurelieMLB** [comment]
Hello,

The new run with the adapter option set to adapters: ["TGGAATTCTCGGGTGCCAAGG"] just finished.
There is indeed much less trimming happening.
But I am afraid otherwise I still get the nearly same outcome..:
-no counts_mirna_novel.tsv file in final or in work (issue 1351)
-no tdrmapper folder in final or work. Just a trna folder in work. I am not sure if it is normal or not (issue 1352)
-The good news is that now I do have maps.html in the cluster folders. So this part seems to have gone through (this issue 1353)

Did you manage to find anything in the logs I attached?

I can see in the log for this run that at the end of mirdeep2 logs, I have:
Can't locate PDF/API2.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/mirdeep2//make_html.pl line 9.
BEGIN failed--compilation aborted at /apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/mirdeep2//make_html.pl line 9.
ended: 11:51:26
total:0h:0m:0s
No csv file given for bed conversion
Usage: get_mirdeep2_precursors.pl -r result.csv  [options] ...

Does it ring any bell on your side please?

I could not find anything in the debug file related to TdrMappingScripts.pl .

Many thanks for any help

Aurelie

**Comment by lpantano** [comment]
hi,

normally, if you don't have the novel counts is because there is not novel ones. All these problems are related to slow number of reads after trimming. Can you send me again the logs files for this run.

**Comment by AurelieMLB** [comment]
Hello,

Please find the log files enclosed. 
Thanks for looking into this !! so to summarise it seems that the only thing which is missing is the tdrmapper folder.
[log.zip](https://github.com/chapmanb/bcbio-nextgen/files/234264/log.zip)

**Comment by lpantano** [comment]
Hi,

still seems weird. Is this a standard small RNA-seq library? I see few reads mapped to miRNAs, and maybe is the reason you don't have an output with tdrMapper.  Just in case, maybe you want to try the command alone, like this:

`unset PERL5LIB && export PATH=/apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/bin:$PATH && perl /apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/bin/TdrMappingScripts.pl /ngs/reference_data/genomes/Hsapiens/hg19/srnaseq/trna_mature_pre.fa A_B_BIPR_M8_S6_R1_001.clean.fastq.gz`

and see if you get all the files, the final files should have *mapped* word in the name.

sorry about that. I think there is something weird, I can help if you can tell me more about these samples. Normally small RNAseq data comes from a different library preparation than the RNAseq, so the RNA follows a completely specific experimental steps. If you tell me the library used for these samples, I can investigate further.

thanks!

**Comment by AurelieMLB** [comment]
Hello,

Ah!! if the final files for trdMapper are the files with "mapped" in their names then I got them but they are in a folder called trna in work. Here is what I get for one sample:
A_B_Bd_M11_S9_R1_001.clean.fastq.gz.hq_cs.mapped
A_B_Bd_M11_S9_R1_001.clean.fastq.gz.hq_cs.mapped.covgPre.txt
A_B_Bd_M11_S9_R1_001.clean.fastq.gz.hq_cs.mapped.covg.txt
A_B_Bd_M11_S9_R1_001.clean.fastq.gz.hq_cs.mapped.speciesInfo.txt
A_B_Bd_M11_S9_R1_001.clean.fastq.gz.hq_cs.mapped.top50covgPre.txt
A_B_Bd_M11_S9_R1_001.clean.fastq.gz.hq_cs.mapped.top50covgPre.txt.top50Pre_tdr.pdf
A_B_Bd_M11_S9_R1_001.clean.fastq.gz.hq_cs.mapped.top50covg.txt
A_B_Bd_M11_S9_R1_001.clean.fastq.gz.hq_cs.mapped.top50covg.txt.top50_tdr.pdf

For some reason they are not moved in final and I have no folder called tdrmapper. But it is not critical for me. I just did not know what to look for. Now I have to figure out what it all mean exactly :)

I did try to run the command line you kindly sent. It does seem to run but the result file in empty. On the other hand I got a file with the same name in work/trna and this one has results in it. So I am probably doing something wrong with the command line...

May I ask you what is still weird then please? As this is my first time with this. I might be doing something wrong without realising...
My understanding is that a Qiagen miRNeasy mini kit was used to extract miRNA + small non coding RNA from the cells. And the Truseq small RNA kit was used for the library prep. So I was not surprised to see some miRNAs in there. Should I be?
The adapters are:
RNA 5’ Adapter (RA5)
5’ GUUCAGAGUUCUACAGUCCGACGAUC
RNA 3’ Adapter (RA3)
5’ TGGAATTCTCGGGTGCCAAGG
But I should probably only consider the RNA 3' one (?) which is the one you are using it seems.
For each sample, I have R1 and R2 but it seems to me that the pipeline is only working on R1? Or are R2 useful at some steps?

Does it help please?

My libraries are probably a bit too small which causes problems. May I ask you what would be a good library size please? What is too small? Would you have a sense for this please?

Many thanks
Aurelie

**Comment by lpantano** [comment]
Hi,

I will fix that, and move to final directory, sorry about that.

You are right about the 3’ adapter, then we are good.

A normal value of annotated miRNAs if the RNA is standard is about 50.000 sequences. You can check the mirbase-* files and look at how many line you have. I was looking at the log files (*debug.log) and I see messages with a small number of miRNAs:



Reading reads
[2016-04-22T10:35Z] ukapdlnx117: Number of reads to be mapped: 1721
[2016-04-22T10:35Z] ukapdlnx117: Searching in precursors
[2016-04-22T10:35Z] ukapdlnx117: Reading reads
[2016-04-22T10:35Z] ukapdlnx117: Reading reads
[2016-04-22T10:35Z] ukapdlnx117: Number of reads to be mapped: 1459
[2016-04-22T10:35Z] ukapdlnx117: Searching in precursors
[2016-04-22T10:35Z] ukapdlnx117: Reading reads
[2016-04-22T10:35Z] ukapdlnx117: Number of reads to be mapped: 12681
[2016-04-22T10:35Z] ukapdlnx117: Searching in precursors
[2016-04-22T10:35Z] ukapdlnx117: Number of reads to be mapped: 685
[2016-04-22T10:35Z] ukapdlnx117: Searching in precursors
[2016-04-22T10:35Z] ukapdlnx117: Reading reads
[2016-04-22T10:35Z] ukapdlnx117: Number of reads to be mapped: 244
[2016-04-22T10:35Z] ukapdlnx117: Searching in precursors
[2016-04-22T10:35Z] ukapdlnx117:


 it could be your sample is not enriched at all in miRNAs? can I know the cell type?

I worked with sperm, for instance, and even the numbers are low, I get more. My main worry it is that the library prep didn’t work or you are getting mainly degradation, or the type cell has a little of small RNAs. You can check the % mapped reads of the BAM file, but I think is low:12272.

You can check in the trimming folder these files: *clean.trimming.fastq* and see how many sequences you have. That can help to know when the problem started. 

A good data are the samples from mirQC project, you can download one, and run it, so you can compare numbers:  https://github.com/lpantano/seqcluster/blob/master/data/pipeline_example/mirqc/download.sh
 
the srna-report.rmd file can help to look at the data, but you need some knowledge in R, because is just a template and don’t compile clean the majority of time. I am trying to improve that, but If you have time to learn a little and try to get the first figures, probably it will tell you something else. I am moving many of them to multiqc report, but probably I will have that in 1-2months.


hope this help.

**Comment by AurelieMLB** [comment]
Hello,

Thanks a lot for your answer!
I am blinded for a lot of info regarding the samples so I do not have the cell type for instance unfortunately.... But your comments are all VERY useful, I will raise this with the experimentalists to try to understand what has happened.

Thank you very much for your help !!

**Comment by lpantano** [comment]
I will close this, but feel free to open any other issue if you have more problems.
thanks
