### ISSUE TITLE
samblaster: Too many sequences in header of input sam file.  Exiting.

### ISSUE THREAD

**Issue by mattingsdal** [chapmanb/bcbio-nextgen#1356]
Hi,

I'm working on a custom genome with 50 000 contigs using the development version of bcbio. 
Everything goes well until samblaster exists with the following error:

> samblaster: Loaded 50156 header sequence entries.
> samblaster: Too many sequences in header of input sam file.  Exiting.
> 
> [fputs] Broken pipe
> ' returned non-zero exit status 1

As always, I google the error and found 
https://github.com/GregoryFaust/samblaster/issues/19

however from reading this my limited cognition fail to understand how to solve this.
Is this a piping error in bash or a samblaster limitation

best
morten

**Comment by chapmanb** [comment]
morten;
Thanks for the report. It looks like samblaster does not support running on genomes with more than 32 thousand contigs. I switched over bcbio to check for this and to use an alternative de-duplication method in these cases. If you update to the latest development it should no longer fail:
```
bcbio_nextgen.py upgrade -u development
```
As a more high level suggestion, it might be worth trimming your reference genomes to remove tiny contigs and bring down the total number. I know a lot of tools have slow or spotty coverage for runs with this many contigs so that could help avoid other issues. 

Hopefully the fix will help get your analysis finished.
