### ISSUE TITLE
CRAM corruption

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1372]
I currently have many failed cram indexing processes during archiving in variant2 that seem to point to corrupt cram files. I will continue to investigate, but a first thing to notice is that the samtools cram compression command does not specify memory (`-m`) at the moment. Also, and that's a different request, could we perhaps get more checkpoints in the variant2 workflow? At the moment, bcbio has the multicore2 checkpoint which contains a lot of result files. A more granular approach would really speed up rerunning and debugging. Last, I would love to see the option to do `samtools quickcheck` on the result alignments - that makes sure that the alignments are not corrupted before they are archived.

**Comment by schelhorn** [comment]
Um, and also the `samtools` command used in bcbio compression isn't from `config_utils.get_program`. So whatever samtools is first in PATH is used, which probably is some outdated version on my system that doesn't know about CRAM.

**Comment by schelhorn** [comment]
While we're at it, `bamUtil` is now in bioconda. With that it is possible to do 8-binning and discarding of read names during cram compression in a pipe. The relevant command would take the bamfile as input and do `bam squeeze --in input.bam --out -.ubam --keepDups --readName --binQualS 2,10,20,25,30,35,70 --binMid | <samtools compression here>`. That should help the larger sequencing labs along to reduce their storage bill quite a lot.

**Comment by schelhorn** [comment]
(correction: bamUtil is still a bioconda pull request, but it already had been reviewed) https://github.com/bioconda/bioconda-recipes/pull/1179

**Comment by chapmanb** [comment]
Sven-Eric;
Sorry about the problems with CRAM. Were you able to diagnose an underlying cause of the corruption? I've seen some corrupted CRAM files in the past -- on the order of ~1% of my BAM to CRAM conversions, but this was with cramtools versus samtools. Regarding your thoughts:

- `samtools view` doesn't have a memory option since it's a streaming operation.
- We're assuming in bcbio now that the bcbio tools directory is the first thing in your PATH so we'll pick up those tools, rather than relying on referencing the internal directory. Is this a problem to setup?
- We can add in bamUtil once that recipe is finalized. It looks like there is some work to do as it's currently failing to build. I'll give it a go -- it was on my list of things to work on.
- For the granular workflow question, we're hoping to move this way with the CWL work. The plan is to replace our current approach with that which will hopefully allow more control over job re-use and retries.

If you have an idea of the underlying cause of the corruption, happy to dig more into detecting or preventing it. Thanks again.

**Comment by schelhorn** [comment]
Yes, and thank you for dealing so well with my unstructured comments. It was the missing `config_utils.get_program` line that bcbio is using in all other `samtools` calls to resolve the absolute path name of the binary. I added that in the cram module as well as a call to `samtools quickcheck` on the post-transactional CRAM file for good measure, with a n=3 retry loop to build the CRAM in case of quickcheck failure (or at least that was what I intended to do, let's see). Probably overengineered, I know, but that goes with the blue collar.

**Comment by schelhorn** [comment]
By the way, upon further reflection it is my personal belief that not explicitly specifying the absolute path of binaries at calling and logging is a step backwards for debugability and reproducibility. Given that the PATH environment of compute nodes can be influenced by many factors, I fear that in future it will be hard to identify the root cause of errors such as mine with that new implicit assumption. I suspect that this choice simplifies certain configurations for CWL/Docker, but personally I'd prefer to leave the absolute paths as they are. To quote `import this`: explicit is better than implicit.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for all the feedback on this. Corrupt CRAM files is a pretty poor output for having out of sync PATHs so I fixed this to explicitly reference the internal samtools. In general we still need to rely on users to provide good isolation of PATHs and reference bcbio explicitly when using it but it makes sense to be pragmatic about it. Hopefully Docker will solve all these worries sooner rather than later.

I also added in 8-bin compression and read name simplification via bamUtils squeeze. If you have a chance to test please let me know if you run into any issues. Thanks again.

**Comment by schelhorn** [comment]
Great, much appreciated! Will test.

**Comment by schelhorn** [comment]
After testing the `bamUtil` compression I would ask for a slight change to the `bamUtil squeeze` command; specifically, the `--readName` option should be omitted since storing the readname-to-integer mappings in memory for WGS is prohibitive (40GB of RAM for a 100GB BAM file). Omitting this single parameter results in the read names staying in the CRAM file as-is, but the sequence and quality score compression is still worth it.

**Comment by chapmanb** [comment]
Sven-Eric -- thanks for testing this out and for the easy fix. I pushed this so hopefully things will work cleanly now.
