### ISSUE TITLE
CPU Optimisation 

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen#1377]
Hi Brad;

I would like get detailed information about cpu usage. As far I know from resources link of the [documentation](http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#resources), I can set CPU and RAM distribution. So in my case, I did not set anything in the default configuration of bcbio but the locations of the jar's of GATK/Mutect. 

My bcbio-vm run with 250 gb(170 gb Tumor/ 80 Normal -  50x coverage) mutation calling took 48 hours. It seemed a lot for my PI. Then I checked the 12 hr period of bcbio-nextgen.py single node run. Here is the CPU utilisation. In the course of 12 hours, our max was 65%. Moreover, over average was %30 CPU usage. I think we are not using CPU's in the most effective manner. 

I ran both of the runs with ```bcbio_nextgen.py -n 36 ../config/bcbioconfiguration.yaml ```

Therefore I have these following questions;
1. What is the time difference between using -n 16 and -n 32. Can I save 2x time?
2. I prefer using all the cores %100, How can I assure this ? Is there anything that I can do to make them run more efficient, with less core ?

I asked my HPC specs. I was told that it is Sun Grid Engine Queing management mechanisms.

Thank you,

T.

![screen shot 2016-04-27 at 21 53 45 2](https://cloud.githubusercontent.com/assets/12833865/14912890/e0fa31c8-0e07-11e6-87b6-9fdd99c1957a.png)

**Comment by ohofmann** [comment]
That's pretty much in line with the numbers I see (actually a bit faster). If you can post your config it's likely easier to point at steps that take long, but in general you will see nowhere near to 100% CPU utilisation for all kinds of reasons:

* some tools do not scale beyond a single node (SV calling, for example); these are also a limiting factor when throwing more nodes at the data and prevent a linear scaleup
* probably 30+% of the time is spent waiting on I/O. SSDs/parallel filesytems to help but only to a certain point
* there is usually some waiting involved towards the end of each phase, e.g., 10 nodes waiting on the one node that's still trying to call variants in a high depth/complex area

Best, Oliver

**Comment by chapmanb** [comment]
Tunc;
Oliver is right on with his explanations. To answer your two questions: we strive to be as efficient as possible in bcbio, but are often constrained by disk IO, memory and the ability of software to effectively use all cores. Adding cores does improve run time, but it won't be a strict linear speed up. Steps can be constrained by ability to parallelize since not all programs can effectively distribute over all distributed cores, and as you add processes you can find additional filesystem bottlenecks. This post has detailed plots of resource usage for variant calling to give you an idea of the tuning we've done:

http://bcb.io/2014/12/19/awsbench/
http://imgur.com/a/AZjuC

Hope this helps.
