### ISSUE TITLE
Fastqc report may be misleading in variant calling pipeline?

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1414]
Hi bcbio developers,
thanks for the great pipeline!

I'm running variant calling for exome seq, and I have 59 mln paired reads.

In the final/project/report/metrics the duplication level is 85% and this is true, if you 
run fastqc from the command line you would receive this value.

But in the final/S1/qc/fastqc/fastqc_data.txt total deduplicated percentage is 81.5% (should be 100-85%=15%). It seems that here fastqc has been run on the subset of 10 mln reads. Problems with subsampling?

SN

**Comment by chapmanb** [comment]
We do downsample fastqc and qualimap to 10 million reads by default to try and avoid long runtimes, so it won't report the exact duplication level of full tools. The idea is to run quicker tools for assessing duplication and other global metrics and to get an idea of quality, contamination and other metrics from fastqc by doing a quicker pass on downsampled data.

What behavior would you prefer to change? We're always happy to hear suggestions about how to better report QC metrics. Thanks much.

**Comment by naumenko-sa** [comment]
I'm ok with downsampling but the approximate value should be close to the real one?
In my case duplication level (59 mln reads) = 85% (very bad)
                   duplication level (10mln reads) = 19.5% (good)
So after running pipeline you are with impression that data is good, however it is not.
Maybe a problem of sampling from fastq?

**Comment by roryk** [comment]
Hi Sergey,

FastQC only uses the first 100k reads to figure out the duplication percentage: http://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/8%20Duplicate%20Sequences.html

Did you run FastQC on the sorted BAM file? If FastQC just takes the first 100,000 and not a random set of 100,000 and since it is position sorted it looks like there are a bazillion duplicates. Maybe when we downsample we get a more random subset of the file and so the duplication percentage doesn't look as bad.

**Comment by ohofmann** [comment]
The FASTQC duplication percentage is not representative. bcbio now also calculates it from samtools which shows up in the MultiQC report; it might be best to hide/ignore the FASTQC duplication column. From my duplication check runs it can be off as much as one order of magnitude.

**Comment by naumenko-sa** [comment]
Thanks @roryk and @ohofmann!
I run fastqc in the command line for fastq file, not for sorted bam. The result was 85% duplicated.
Samtools output from bcbio is also 85% (work/qc/sample_id/samtools (reads duplicated).

Fastqc called from bcbio resulted in 81.5% deduplicated which means duplication level of 18.5%.

That is the question: fastqc command line != fastqc from bcbio, and samtools support fastqc command line. Is it possible that the way bcbio calls fastqc is incorrect?
If fastqc duplication level is not relevant, maybe it is worth noting somewhere in the docs with a proof?
It is counter-intuitive. 

From Fastqc docs
[http://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/8%20Duplicate%20Sequences.html](http://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/8%20Duplicate%20Sequences.html)

> 
To cut down on the memory requirements for this module only sequences which first appear in the first 100,000 sequences in each file are analysed, but this should be enough to get a good impression for the duplication levels in the whole file. Each sequence is <b>tracked to the end of the file</b> to give a representative count of the overall duplication level. 
>

Now fastqc calculates statistics for the first 200,000 sequences.
[http://proteo.me.uk/2013/09/a-new-way-to-look-at-duplication-in-fastqc-v0-11/](http://proteo.me.uk/2013/09/a-new-way-to-look-at-duplication-in-fastqc-v0-11/)

200,000 sequences tracked to end of the file, should be a good estimate for a fastq file?

Best,
SN

**Comment by ohofmann** [comment]
Might be worth looking into how we downsample (or whether it's really necessary). But yes, do ignore those and use the samtool-based ones for the time being.

**Comment by brainstorm** [comment]
@naumenko-sa, sorry for the confusion, and great that you brought up this topic. It's something I wanted to look at myself for a while now, so lets dig into it:

There's the [fastqc class](https://github.com/chapmanb/bcbio-nextgen/blob/c34b1c40f625d0b3c7698c1b91de731cc6cac244/bcbio/qc/fastqc.py#L20) which calls the [bam.downsample](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/bam/__init__.py#L114) function.

This is afaict, for BAM files and used as QC. Which actually calls `sambamba` to perform the subsampling:

```
cmd = ("{sambamba} view -t {num_cores} {read_filter} -f bam -o {tx_out_file} "
            "--subsample={ds_pct:.3} --subsampling-seed=42 {in_bam}")
```

Sambamba uses a clever [FNV-1a](https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function) hashing algorithm to perform the downsampling, which I guess does pick reads randomly by masking the resulting generated hashes:

```
auto h = simpleHash(read.name);
        return (h&0xFFFFFFFFUL) < _threshold;
```

As far as I can see in bcbio's code, bcbio just passes the amount of "targets" (reads?) to subsample directly to `sambamba`, letting the latter do it efficiently on the whole (BAM?) file.

Perhaps unrelated since I cannot see QC steps calling this function directly, for fastq files, there's the following function which picks up FASTQ reads randomly:

https://github.com/chapmanb/bcbio-nextgen/blob/e9bdcbae7ecbb4c5818f06e87e1efa8de8f24965/bcbio/bam/fastq.py#L182

Hope that helps? As Brad mentioned, let us know if there's something we can do to improve that.

**Comment by naumenko-sa** [comment]
Thank you @brainstorm for the detailed trace. Now how it looks from the data/logs point of view.
I used the project output folder and bcbio-nextgen-commands.log

1. project/work/qc/sample/fastqc/fastqc_data.txt is misleading while
project/work/qc/sample/samtools/sample.txt is correct.
2. sample.txt is generated by 
samtools stats project/work/align/sample/sample-sort.bam
it is correct because uses all reads for statistics.
3. fastqc_data.txt is generated by
fastqc -f project/work/qc/sample/sample-sort-downsample.bam
sample-sort-downsample.bam is misleading, when checked with samtools stats it gives the same level of duplication as fastqc. So it is not a problem of fastqc, but the problem of downsampling.
4. sample-sort-downsample.bam is produced by sambamba:
sambamba view -f bam project/work/align/sample/sample-sort.bam

So, sambamba IMHO with its clever algorithm produces misleading downsample.bam.

I would suggest to exclude sambamba downsampling, because fastqc does downsampling well,
and (hopefully) we will see the same output for samtools and fastqc.

Best,
SN

**Comment by lpantano** [comment]
Hi,

I actually remove the column from the multiqc report, and only the samtools QC would show.

thanks!
