### ISSUE TITLE
Please suggest a good method to run variant2 anaysis with multiple BED files.

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1424]
Hi bcbio developers and users,

could you please suggest how to run variant2 analysis with multiple BED files?

Imagine you have one BED file for exome capture kit, second BED for genome annotation
(ucsc, refseq), and third for target regions (OMIM).

Currently I'm running separate analysis for each BED.
The other option is to chose the BED which captures more than others (or to create a union)
and then filter the results (coverage, variants) according to each BED.

But is there a more efficient way?

SN

**Comment by chapmanb** [comment]
Sergey;
Thanks for starting this discussion. Are you looking for different reporting in each of the BED regions? Practically, it makes sense to only call with the BED capture region since that's where you actually expect coverage and useful variants. Then you might want to subset this to do different types of analyses downstream. I know @ohofmann had some ideas around providing multiple files for coverage QC and reporting and might want to chime in here.

Practically, I think the best way to approach is to define use cases and then try to determine if there's anything general in bcbio that we can do to help. In the end we're not going to be able to do every kind of downstream analysis, but could provide hooks to do commonly useful ones if there's some shared agreement about that entails. Thanks again for bringing this up.

**Comment by naumenko-sa** [comment]
Thanks Brad. I ended up with separate runs of bcbio and then compared vcfs and coverage reports. Maybe there is no new use case for bcbio. SN

**Comment by ohofmann** [comment]
My use case was a bit different -- I was looking into a standard BED file for all (human, WGS) coverage reporting as a default, augmented with a user-defined BED file to calculate coverage in the regions important for the project. 

The standard coverage report ensures consistency between different runs and projects and can be included in MultiQC as a QC section. The user-defined BED file lets the user know what important genes (e.g., cancer drivers) lack in coverage.

**Comment by naumenko-sa** [comment]
Sounds interesting, did you automate this with bcbio, or you just extracted a subset from the standard coverage report according to the user-defined BED?

**Comment by ohofmann** [comment]
That was just a feature suggestion ;-)
