### ISSUE TITLE
vardict error:bcbio vardict java error : Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio-nextgen#1429]
Hi Team, 

I see that there was an user with the same error but that was coming from a bed file and I see that CIGAR from the modified gatk bam file is causing problems for vardict. 

I am not sure if my case is the same but I dont see any error regarding bedfile so I am not completely sure if its CIGAR which is causing the problem. Attached is the bcbio.stderr file. Can you guys please help me to figure out this. 
[bcbio.stderr.txt](https://github.com/chapmanb/bcbio-nextgen/files/309579/bcbio.stderr.txt)

**Comment by chapmanb** [comment]
Sorry about the issue. Do you know which version of vardict-java you're running? It should be reported in `provenance/programs.txt`. The latest VarDict release (1.4.6) has some fixes for this.

If you have the latest version the other thing to try is to add `realign: false` to your bcbio configuration file. Realignment is not necessary with VarDict (or GATK HaplotypeCaller) and false will be the new default in the next release of bcbio since the GATK has also dropped their recommendation of realignment. Realignment can create strange BAMs CIGARs that cause these kind of issues with VarDict. Hope this helps.

**Comment by lpantano** [comment]
Hi @DiyaVaka 

I assume that was solved some how, please come back to us if you find further issues.

cheers
