### ISSUE TITLE
RNA-seq: a problem with the human reference?

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1430]
Hi bcbio developers!

When trying
```
bcbio_nextgen.py upgrade --data --datatarget rnaseq --genomes GRCh37
```
it does not install STAR index, even with
```
bcbio_nextgen.py upgrade --data --genomes GRCh37 --aligners star
```

with hg19 it installs but then the pipeline exits with
```
Could not find reference genome file hg19 samtools
```

Any ideas?

Thanks,
SN

**Comment by chapmanb** [comment]
Sergey;
Sorry about the issues -- I'm confused as those commands should work. You do need to specify `--aligners star` as in the second command, since the `--datatarget` argument doesn't add aligner indices, but that should include it. I'm not sure why it doesn't do that and why your hg19 data installation is broken. Is there anything custom/modified about the install that would help us diagnose?

As next steps, it might be useful to see what is in some of the problem folders/files:
```
tree /path/to/bcbio/genomes/Hsapiens/GRCh37/
tree /path/to/bcbio/genomes/Hsapiens/hg19
cat  /path/to/bcbio/galaxy/tool-data/sam_fa_indices.loc
```
Hope this helps some.

**Comment by naumenko-sa** [comment]
Hi Brad,
```
tree /path/to/bcbio/genomes/Hsapiens/GRCh37/ 
├── chrLength.txt
├── chrNameLength.txt
├── chrName.txt
├── chrStart.txt
├── genomeParameters.txt
├── Log.out
└── _STARtmp

1 directory, 6 files
```
Genome build has not been finished. I've tried to delete the directory and start again.
```
tree /path/to/bcbio/genomes/Hsapiens/hg19/ 
├── chrLength.txt
├── chrNameLength.txt
├── chrName.txt
├── chrStart.txt
├── Genome
├── genomeParameters.txt
├── Log.out
├── SA
└── SAindex
```
Looks perfect.
```
cat  /path/to/bcbio/galaxy/tool-data/sam_fa_indices.loc
index	GRCh37	/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
index	soltub3	/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/stuberosum/soltub3/seq/soltub3.fa
index	glymax2	/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/glycinemax/glymax2/seq/glymax2.fa
index	TAIR10	/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Athaliana/TAIR10/seq/TAIR10.fa
index	mm10	/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Mmusculus/mm10/seq/mm10.fa
0 directories, 9 files
```
Thanks,
SN

**Comment by chapmanb** [comment]
Sergey;
Thanks for the additional details. It looks like the GRCh37 STAR index building is in progress (or never finished) and the hg19 didn't finish cleanly since it's not in the sam_fa_indices.loc file. Are you getting errors or other problems before the data install finishes?

The STAR genome build is resource intensive and will need a lot of memory (30+Gb if I remember right) and could use multiple cores. If you add `--cores 16` (or however many cores you can spare) to the bcbio_nextgen.py upgrade command that should help with speed. @roryk, can you correct me if I misquoted any resource requirements?

Hope this helps get it finished.

**Comment by naumenko-sa** [comment]
Thanks, @chapmanb . I've generated STAR index for GRCh37. It seems that previous runs were short of storage space.
