### ISSUE TITLE
bcbio-ipengine.err:cat: write error: Broken pipe

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1442]
Hi Brad,

Recently, when I updated the bcbio-nextgen in the newest development version and ran any variant calling pipeline, I frequently found the following error in bcbio-ipengine.err.%%j files. In addition, all the log files did not update instantly until error occurs. So I could not keep tracking the status of the running. Could you help me to debug it? Thanks!

2016-06-22 11:13:20.044 [IPEngineApp] Completed registration with id 8
cat: write error: Broken pipe
cat: write error: Broken pipe
cat: write error: Broken pipe
cat: write error: Broken pipe
cat: write error: Broken pipe
cat: write error: Broken pipe
cat: write error: Broken pipe
2016-06-22 12:14:52.391 [IPEngineApp] WARNING | No heartbeat in the last 5010 ms (1 time(s) in a row).

**Comment by roryk** [comment]
Hi @pengxiao78,

It is hard to tell from this output but my first guess is that the worker nodes in your cluster are having trouble writing to the log files in the log directory for some reason. Does the ipcontroller file have any enlightening information in it? Does bcbio-nextgen fail? What does that error look like?

**Comment by pengxiao78** [comment]
Hi Rory,

This error may has nothing with the log file writing. If bcbio-nextgen failed, job canceled or the running completely finished in the cluster, the log files would be updated. I had successfully finished two runs without showing any updates in all the log files in log folder and my own log file in work folder during runnings, but just saw the results in final folder and updated log files when the runs were completed. However, I feel uncomfortable without monitoring running stages. 

The ipcontroller file has the following info. Thanks.

#!/bin/sh
#SBATCH -p cluster
#SBATCH -J project_test_somatic-c
#SBATCH -o bcbio-ipcontroller.out.%j
#SBATCH -e bcbio-ipcontroller.err.%j
#SBATCH -t 00-96:00:00
#SBATCH --cpus-per-task=1
#SBATCH -A batch
#SBATCH --mem=4000

/user/parallel/bcbio/anaconda/bin/python -E -c 'import resource; cur_proc, max_proc = resource.getrlimit(resource.RLIMIT_NPROC); target_proc = min(max_proc, 10240) if max_proc > 0 else 10240; resource.setrlimit(resource.RLIMIT_NPROC, (max(cur_proc, target_proc), max_proc)); cur_hdls, max_hdls = resource.getrlimit(resource.RLIMIT_NOFILE); target_hdls = min(max_hdls, 10240) if max_hdls > 0 else 10240; resource.setrlimit(resource.RLIMIT_NOFILE, (max(cur_hdls, target_hdls), max_hdls)); from cluster_helper.cluster import VMFixIPControllerApp; VMFixIPControllerApp.launch_instance()' --ip=* --log-to-file --profile-dir="/user/project/patients_no_adapters_R1_R2/somatic/work/log/ipython" --cluster-id="ebc631d2-65ff-4e63-9732-d6ab0ac1f13c" --nodb --hwm=1 --scheme=leastload --HeartMonitor.max_heartmonitor_misses=720 --HeartMonitor.period=5000

**Comment by roryk** [comment]
This sounds like something outside of bcbio that is causing this issue. Are the directories you are running the analyses in mounted over NFS? What do those options look like? If this isn't causing errors, I'm guessing there is maybe some NFS caching going on or something like that that is causing the delay in updating.

If you ssh into the node where the main bcbio-nextgen process is running, do the files look updated and not have the delay? Brad will definitely have better suggestions than I do with this.

**Comment by chapmanb** [comment]
Thanks for all the discussion and sorry about the problems. To try and summarize to see if I understand: your runs finish fine and logs look okay, but the logs are not updated in real time during the analysis. Is that right?

Rory's suggestion is right on in that this is likely something with updates of files within the directories. If logs are being passed they should go back to the machine running the main `bcbio_nextgen.py` process and then get written immediately. We don't have any type of caching mechanism.

The `cat` messages you found in the engine log are expected. We have steps in the pipeline where he use cat and then head, which leads to these:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/ngsalign/bwa.py#L102

It's not an error, since we know we're cutting off cat, but I don't know to suppress it. We previously had sent stderr to /dev/null here to avoid printing them, but this swallows actual errors so we pulled that out in the last release.

I'd suggest following Rory's suggestions to see if that sheds any light on the underlying issue. Hope this helps.

**Comment by pengxiao78** [comment]
Thank you, Rory and Brad! Brad, your understand is right. I will do more research on delayed written problems for log files following Rory's advices.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
