### ISSUE TITLE
Error during variant calling with freebayes

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1474]
Hi Brad,

I've encountered a weird error during the variant calling step with freebayes.
We sequenced a sample of Genome In A Bottle on our in house sequencers to test the performance and would like to analyze the results with bcbio.

I've added the debug log and the stdout to this issue. If you find the time, could you have a look at them? There's a whole lot of error messaging going on.

Thanks!
M

[logs.zip](https://github.com/chapmanb/bcbio-nextgen/files/365268/logs.zip)

**Comment by chapmanb** [comment]
This one looks like one of the programs core dumped, but it's hard to tell which one since it's in a big pipe. In general the best thing to do if you run into an error is to re-run in a single core:
```
bcbio_nextgen.py your_config.yaml
```
which will remove some of the noise when seeing the error message and also check if it fails consistently. If it does fail you can try running the failing command (the last one in `bcbio-nextgen-commands.log`) outside of bcbio to see if it fails there and then try to diagnose. Hope this helps figure out the problem.
