### ISSUE TITLE
BAM file after realignment

### ISSUE THREAD

**Issue by deber1980** [chapmanb/bcbio-nextgen#1479]
Hello,

I wanted to know if there is currently an option to get the BAM file after variant calling realignment. To the best of my knowledge the "XXX-ready.bam" is the one created by the aligner (BWA), and when looking at it with IGV, sometimes its hard to understand why variants were reported or not by the variant caller.
Also, if there is an option to keep it, can it be stored in the "final" folder or uploaded to S3 at the end of the processing?

Thanks

**Comment by chapmanb** [comment]
The BAM file in the final directory is the recalibrated/realigned file if those options are turned on in the configuration. We only pass along a single BAM file to the final directory, so use the most processed version that goes into variant calling.

Practically most callers like FreeBayes and GATK HaplotypeCaller do realignment internally so there won't be a BAM representation of the reads used to call since that happens internally in the program.
If you want to debug a region and are using HaplotypeCaller, you can produce a BAM file based on it's realignment as a manual process outside of bcbio:

http://gatkforums.broadinstitute.org/gatk/discussion/5484/howto-generate-a-bamout-file-showing-how-haplotypecaller-has-remapped-sequence-reads

Hope this helps.

**Comment by deber1980** [comment]
Thanks Brad. very helpful
