### ISSUE TITLE
Joint Calling Pipeline

### ISSUE THREAD

**Issue by lsturm1** [chapmanb/bcbio-nextgen#1505]
Hi,

Is it possible to use vcf files as inputs for joint calling with gatk? I am trying to reduce the computational load and the time necessary to joint call samples. I have been using BAM files as input, but I ran one job that failed to finish, but it completely finished the normal variant calling step. I have a folder in that project called gatk-haplotype with all of the variant files. Is there any way to use those as inputs into the gatk-haplotype-joint so I don't have to recall all the variants?

Thank you,
Luke

**Comment by roryk** [comment]
Hi Luke,

VCF files just have the list of variant positions for each sample. Let's say in sample A there is a variant at chr1:20 and there is nothing listed in sample B for chr1:20. From the VCF files, there is no way to know if sample B was homozygous reference at chr1:20 or if there were no reads at chr1:20 or it had some heterozygous reads but not enough to call a variant, etc. So you can't do joint calling from the VCF files because there is no information about why a variant does not exist. You have to go back to the BAM files for that.

**Comment by lsturm1** [comment]
Thank you! Is there a way to specify both the BAM and the variants as inputs? Or does it have to go through the strict path of starting with BAM, variants calling on the BAM, and then joint calling?

**Comment by chapmanb** [comment]
Luke;
You can pass in pre-aligned BAMs using `files: [your.bam]` as in the put option and setting `aligner: false`:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#alignment

Then it'll skip the alignment and proceed to variant calling. You will have to recall variants though so you can gVCFs instead of standard VCFs. Hope this helps.

**Comment by lpantano** [comment]
Hi Luke,

I will close this, but feel free to open more issues for any problem/question you find.

cheers
