### ISSUE TITLE
Deploy bcbio on Azure

### ISSUE THREAD

**Issue by deber1980** [chapmanb/bcbio-nextgen#1519]
Hello,

I wanted to ask if there are any recommendations for deploying bcbio on Azure. I am aware of bcbio-vm and the docker container and have used it successfully when deploying to AWS but I'm looking for a wrapper similar to bcbio-vm for quick deployment on Azure.  

From what I've seen elasticluster doesn't support azure yet. 
Would using Ansible (http://docs.ansible.com/ansible/azure_module.html) for implementing such a wrapper would be a good choice?
Are there any other plans or directions for supporting bcbio on Azure?

Thanks for your help.

**Comment by chapmanb** [comment]
Thanks for the timely question, we've been working on Ansible scripts and documentation for running bcbio across multiple clouds in a simplified way using a single machine and attached disks, rather than setting up a cluster. This is conceptually simpler and more flexible and should handle smaller run cases. The Ansible scripts and in-progress docs are here:

https://github.com/chapmanb/bcbio-nextgen/tree/master/scripts/ansible

The docs aren't fully finished so will still have some missing parts we're filling in but hopefully have enough detail to give an overview.

For larger runs, our plan is to use the CWL support in bcbio (http://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html) to run on top of other systems that support Azure and other clouds. For instance, we already have bcbio working with Arvados (https://arvados.org/) which runs on Azure. Curoverse's public instance at https://cloud.curoverse.com is on Azure and is free for trying out. This type of integration should gradually replace the custom elasticluster code we wrote so we can focus bcbio development on science and pipeline development while using the awesome work others have for building scalable clusters.

Hope this helps practically with getting started on Azure.

**Comment by deber1980** [comment]
Thanks a lot Brad. This is great!

**Comment by deber1980** [comment]
Hello Brad,
I wanted to follow up on this thread. 
I see that the docs mention that bcbio can run on Toil, and mention that it can be specifically can be used for running on [AWS](https://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html#running-bcbio-cwl-on-toil
)

Since I see that toil has templates for [running on Azure](http://toil.readthedocs.io/en/releases-3.3.x/installation.html#installation-on-azure), I wondered if this should basically work? 
If I want to run a bcbio cluster over azure I should 
- Create a toil cluster according to their installation [instructions](http://toil.readthedocs.io/en/releases-3.3.x/installation.html#installation-on-azure)
- Install bcbio on the toil cluster. I'm not very familiar with toil so not sure what are the exact steps 
- Use bcbio cwl support in order to run the analysis on the cluster

Can you confirm that this is the way to go? Are there known limitation for doing what I wrote above?

Thank you for your help.

**Comment by chapmanb** [comment]
Thanks for continuing this discussion. We do hope that Toil will be the right way to run bcbio at scale on AWS, GCE and Azure. Right now we're actively working on testing CWL runs with Toil AWS autoscaling using workflows here:

https://github.com/bcbio/bcbio_validation_workflows

These have inputs and reference data stored in S3 for enabling the run that make this possible. Some notes on running it right now are available here:

https://github.com/chapmanb/bcbio-nextgen/tree/master/scripts/ansible#running-with-toil

We'll plan to write up better docs once we have confidence this is working well and then can proceed to testing on Azure and GCE and also providing equivalent documentation.

So practically this is the right path not quite ready yet. To finalize on Azure we'll need to provide data collections in Azure blob store and then provide ways to generate CWL referencing these in bcbio-vm. Toil uses these external references plus bcbio Docker containers so there are no explicit install steps.

Hope this helps some with directions and the current status.
