### ISSUE TITLE
install bcbio

### ISSUE THREAD

**Issue by MengNiu** [chapmanb/bcbio-nextgen#1522]
Hi When i was trying to install bcbio on cluster, i got this error msg:

Error: Could not open u'/.conda/envs/.pkgs/jbig-2.1-0.tar.bz2.part' for writing ([Errno 2] No such file or directory: u'/.conda/envs/.pkgs/jbig-2.1-0.t
ar.bz2.part').
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 245, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 38, in main
    bcbio = install_conda_pkgs(anaconda)
  File "bcbio_nextgen_install.py", line 72, in install_conda_pkgs
    "--file", os.path.basename(REMOTES["requirements"])])
  File "/util/opt/anaconda/2.0/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bcbio/anaconda/bin/conda', 'install', '--quiet', '--yes', '-c', 'bioconda', '--file', 'requirements-conda.txt']' returned non-ze
ro exit status 1

**Comment by chapmanb** [comment]
Sorry about the install issue. It looks like conda ran into some issues writing to your filesystem. I'm not sure if this was due to the filesystem being full or some intermittent error from the filesystem. Practically the best way to get through it is to re-run the install command with the same commands and it should pick up where it left off. Hope this helps you finish your installation.
