### ISSUE TITLE
Add algorithm to existing results

### ISSUE THREAD

**Issue by deber1980** [chapmanb/bcbio-nextgen#1526]
Hello,

I've recently executed variant calling pipeline for few samples (bwa, GATK etc) and save the results - bam files (ready, disc, sr) and vcfs. I would like to execute CNV calling e.g. using Lumpy or Delly.
Is there a quick way for doing this or should I rerun the entire pipeline from the beggining. Can I provide bcbio the 3 bam files as input for instance? 

Thank you!

**Comment by chapmanb** [comment]
Do you still have the work directory for the previous run? If so, the easiest way is to add the callers you want to the configuration, remove the `checkpoints_parallel` directory and re-run. This makes use of all the files already generated and will be the fastest route.

For a re-run you can feed in pre-aligned BAM files with:
```
files: /path/to/your.bam
algorithm:
   aligner: false
   variantcaller: false
   svcaller: [cnvkit, manta]
```
For CNV calling, I recommend a depth based caller like CNVkit. Manta is a good paired/split read caller to include as well. Using Lumpy with a pre-aligned BAM file will be a bit expensive since we don't have a way to include the discordant and split read files and it will need to re-generate those, but workable if you want a third caller. Delly is currently quite slow compared to other callers so we haven't been maintaining the integration recently.

Hope this helps.

**Comment by deber1980** [comment]
Hello Brad,

Thank you for the answer.
I don't have the full work directory, only the files which are stored in the "final" directory. I believe it is not enough.
Can you elaborate a little about the "checkpoints_parallel" directory? If I **remove** it then the pipeline uses previous files?
Also, does it mean that the "ready" bam includes all the reads, even those which are in the discordant and split read files?

Thanks again

**Comment by chapmanb** [comment]
If you only have the final directory you do need to setup a new run. In this case you don't need to worry about `checkpoints_parallel`. In a run directory that tell bcbio that a parallelization process (like alignment) has finished so you don't need to re-spawn a parallel job (or cluster job) for that step, so you'd want to remove it if re-running in the same work directory.

The `-ready.bam` does have all reads, including the discordant and split. Those are separate in case you want to manually put them into other downstream analyses.

Hope the re-run works cleanly for you.

**Comment by deber1980** [comment]
Got it. Thanks again Brad

**Comment by brentp** [comment]
Just to clarify, if the bam is aligned via bcbio, then the split/discordant reads will be available to lumpy, right?

**Comment by chapmanb** [comment]
Brent -- that's right. We use samblaster and extract these then make them available to lumpy so there is no extra work if aligned with bcbio. For pre-aligned BAMs we need to run samblaster to extract them as an initial step so have the overhead of name sorting the BAM and running the extraction.

**Comment by deber1980** [comment]
Hello,
I wanted to try and run lumpyexpress on the disc and split bam but when I'm looking in the "final" folder I see only the "-ready.bam". I'm pretty sure that in previous analyses I used to see them there. Anything change recently?

**Comment by chapmanb** [comment]
You now need to specify lumpy as an svcaller to get bcbio to run samblaster. We were getting reports of segfaults and other issues with lumpy (like you reported in #1639) so only run it when needed for the downstream workflow. We're trying to debug with samblaster but avoiding it also makes the piping simpler (since you don't need to manage output of 3 simultaneous files) so could help there as well. If you specify lumpy as an svcaller bcbio can run it for you directly, and will also produce these output files.

**Comment by deber1980** [comment]
So, I'll try and be more specific as to what I am doing.
I have few whole genome samples (around 2 files of 50GB each sample) for which I would like to do both snps/indels variant calling as well as detect CNVs/structural variants.
Currently I'm using a configuration similar to this.
~~~~

details:
- algorithm:
    aligner: bwa
    bam_clean: false
    effects: false
    mark_duplicates: true
    platform: illumina
    quality_format: standard
    realign: false
    recalibrate: gatk
    tools_off:
    - gemini
    variantcaller:
    - gatk-haplotype
    - freebayes
    svcaller:
    - mantra
    - cnvkit
    - lumpy
  analysis: variant2
  description: mysample
  files:
  - /encrypted/data/mysample1.fq.gz
  - /encrypted/data/mysample2.fq.gz
  genome_build: hg19
  metadata:
    batch: Sample_batch
    phenotype: ''
fc_date: '2016-11-14'
fc_name: sample_name
~~~~

Which sometimes fails with the error on issue #1639 .
However, regardless of the failture, would it make more sense to run first the germline variant calling using the above config by removing the "svcaller" part from the yaml, and then after it is finished run it over the same work dir, e.g. something like this:


~~~~

details:
- algorithm:
    aligner: false
    bam_clean: false
    effects: false
    platform: illumina
    quality_format: standard
    realign: false
    recalibrate: false
    tools_off:
    - gemini
    svcaller:
    - mantra
    - cnvkit
    - lumpy
  analysis: variant2
  description: mysample
  files: /encrypted/data/final/mysample2-ready.bam
  genome_build: hg19
  metadata:
    batch: Sample_batch
    phenotype: ''
~~~~


Splitting this into two parts would allow better understand of where exactly it fails, and get results to germline variants even if the structural variant calling fails.
Two questions:
(1) Is this less efficient then putting all in the same config?
(2) In case I no longer have the work dir, and I only have the results of the first part (germline variant calling), specifically the bam file, is it less efficient then running all in the same config?

**Comment by chapmanb** [comment]
Thanks for all the details on your configuration. There is no advantage to running it twice and it makes things more complicated, so I'd avoid that. bcbio is primarily tested for your first case of including everything in one configuration. Supporting restarting from arbitrary points is more complex so we try to avoid that as much as possible. Variant calling happens separately from structural variant detection, so those two steps should not impact each other. Also, re-running in the same work directory is always more efficient since bcbio can re-use coverage and other calculations.

If you update bcbio to the latest development version you can choose between including lumpy in the SV calling and getting samblaster, or leaving it out and getting biobambam. I don't have a good way to work around samblaster issues other than avoiding lumpy/samblaster for cases where it fails. We have a reproducible segfault case that Greg is currently looking at:

https://github.com/GregoryFaust/samblaster/issues/26

but other than that being fixed I don't have any other tips. If we did we'd definitely include them as part of bcbio to avoid issues.

Hope this helps with your analysis getting things working.

**Comment by deber1980** [comment]
Thanks for the detailed answer.
Just to make sure - If I only configure bcbio to manta and cnvkit, then things should be good since samblaster is not used? I thought the manta is based on split and discordant reads as well.

**Comment by chapmanb** [comment]
That's right. Manta does use split and discordant reads but extracts them from the full BAM so doesn't need them to be pre-processed with samblaster. Please let us know if you run into any other problems.

**Comment by chapmanb** [comment]
The latest development version now has a cleaned up approach to preparing Lumpy inputs from pre-aligned BAM files that should allow you to now use lumpy again when re-running from there (https://github.com/chapmanb/bcbio-nextgen/issues/1738#issuecomment-273754039). Please feel free to re-open if you're still stuck on any issues with the latest version.
