### ISSUE TITLE
Quality score conversion with BAM input file

### ISSUE THREAD

**Issue by andersjacobsen** [chapmanb/bcbio-nextgen#1529]
It seems the quality score conversion ('standard' vs 'illumina') is only done when input is fasta. To remedy this, I added the following code to 'alignprep.py', and it appears to work:

```
    cores = config["algorithm"].get("num_cores", 1)
    max_mem = config_utils.convert_to_bytes(resources.get("memory", "1G")) * cores
    bgzip = tools.get_bgzip_cmd(config, is_retry)

    ## >> begin quality score fix
    needs_convert = config["algorithm"].get("quality_format", "").lower() == "illumina"
    if needs_convert:
        seqtk = config_utils.get_program("seqtk", config)
        bgzip = "{seqtk} seq -Q64 -V - | ".format(**locals()) + bgzip
    ## << end fix

    # files
    work_dir = utils.safe_makedir(os.path.join(dirs["work"], "align_prep"))
```

**Comment by chapmanb** [comment]
Anders;
Thanks for the report. We purposely do not check `quality_format` and do conversion for BAM files since these are always supposed to use standard/sanger/+33 scores:

http://samtools.github.io/hts-specs/SAMv1.pdf

Aligners and other inputs should always translate it into those scores, independent of the original quality of the fastqs. Is this not the case with your BAM inputs? Do you know how they were created?

**Comment by andersjacobsen** [comment]
Hi Brad,

These are 'pre-historic' bams created around 2011/12 that we are now
reprocessing, haven't checked what aligner they were created with. I do not
necessarily expect we bump into this problem again any time soon, so fine
if you just want to leave the code as it is, just wanted to report that
this little hack seems to do the job.

**Comment by chapmanb** [comment]
Anders -- thanks for following up and for the details. Glad this is a "deal with an old project" problem and not something new that needs fixing. I appreciate you sharing your workaround in case anyone else runs into the issue.
