### ISSUE TITLE
gatk path problem

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1530]
Hi!

I installed GATK-3.6 in a fresh install of bcbio-nextgen using the recommended way:

```$ gatk-register /path/to/GenomeAnalysisTK.tar.bz2```

Did not work. Didn't not find the GATK jar for realignment. After running ```$ bcbio_nextgen.py upgrade --tools --toolplus gatk=/path/to/gatk/GenomeAnalysisTK.jar``` things worked as should.

I updated also from 0.9.9 to to the latest devel version. Could also be what fixed it, however.

**Comment by chapmanb** [comment]
Pär;
Thanks for the report. There are some fixes in the latest development to resolve problems with finding the new gatk-register approach, so that is likely what solved the issue. If you run into other problems please do let us know as we try to resolve all the outstanding issues with the change in how we register GATK.
