### ISSUE TITLE
no indication when error in slurm args

### ISSUE THREAD

**Issue by brentp** [chapmanb/bcbio-nextgen#1550]
I am running this:
```
bcbio_nextgen.py ../config/eiee.yaml -n 84 -t ipython -s slurm -q $q -r "account=$q" -r "parition=$q" --timeout 1000
```
the controller gets on the queue, but the engines never do. The slurm engine script has this header.

Note that I misspelled "partition". As far as I can tell, this just hangs until timeout with no indication of the error. I just finally happened to notice the misspelling.

**Comment by chapmanb** [comment]
Brent;
Sorry about the issues, the interaction through IPython with the cluster is imperfect as we're essentially preparing and submitting batch scripts so don't get good error reporting to diagnose these kind of issues. Since we've been actively moving to CWL based runners to replace IPython we haven't invested much effort in improving this. Definitely happy to accept a PR if you think it's worth digging into and fixing.

**Comment by brentp** [comment]
ok. I'll close for now. I was able to debug eventually, would be nice to have a message go to stderr, but it seems that's deep in ipython code where I'm not willing to venture.
