### ISSUE TITLE
save_diskspace may be incompatible with kraken implementation

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1558]
When `save_diskspace` is activated, `kraken` tries to access the dummy `.fq.gz` files in `align_prep` and exits with an error. I propose that `kraken` could use the original FASTQ files from `inputs` instead. That should be a quick fix [about here](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/qc/kraken.py#L36).

**Comment by lpantano** [comment]
Hi @schelhorn 

thanks for the tips. I am not sure where else the original FASTQ file could be, I am using `data['files']` but this is not working in this case. @chapmanb , do you know other key inside the data structure where the original FASTQ can be? I think `inputs` in only available when CWL is running. Will try to figure out this.

**Comment by schelhorn** [comment]
I guess `files` is overwritten with the files from `align_pre` once these are generated. Perhaps there could be an additional field added to the global data structure; other QC tools use the FASTQ files as well - how are they doing it?

**Comment by chapmanb** [comment]
Lorena and Sven-Eric;
Thanks so much for digging into this. Apologies, I hadn't realized the fastq files were used outside of the original alignment steps. I added in the ability to save the original fastqs so we can use those as
input to Kraken instead of the cleaned and removed ones. Another potential long term approach would be to stream fastqs from the align_bam file as input. That would be cleaner but is a bigger change so I made the simple one to get things working again. Let us know if you run into any other problems.
