### ISSUE TITLE
Download issues with GrCh37 hapmap

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#1568]
Hi Brad,

While downloading the bcbio pipeline into another server, I could not get past the download for GrCH37 hapmap as the download does not proceed at all.
Running GGD recipe: hapmap
--2016-09-22 10:57:14--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/2.8/b37/hapmap_3.3.b37.vcf.gz
           => “-”
Resolving ftp.broadinstitute.org... 69.173.80.251
Connecting to ftp.broadinstitute.org|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /bundle/2.8/b37 ... done.
==> SIZE hapmap_3.3.b37.vcf.gz ... 59819710
==> PASV ... done.    ==> RETR hapmap_3.3.b37.vcf.gz ... done.
Length: 59819710 (57M) (unauthoritative)

 0% [                                       ] 0           --.-K/s

I can and have run this command separately to get the completed file; however, even if I add the completed file into the directory, it is always overwritten back to an empty file after I restart the download. Could you advise on how I can bypass the wget in the download script? Thanks!

**Comment by chapmanb** [comment]
Sorry about the download issues. The GATK ftp server often has downtime and instability so it might be worth retrying to get it working. We don't have a great way to manually download and insert it right now since the download gunzip and bgzips the file on the fly so won't recognize it's already present. Hopefully retrying will find the ftp site working again and get you a finished download. Sorry to not have a better plan but hope this helps.

**Comment by phu5ion** [comment]
Hi Brad,

I just got it to download after a few attempts, so everything's alright now, thanks!
