### ISSUE TITLE
OptiType for RNA-Seq data

### ISSUE THREAD

**Issue by rdocking** [chapmanb/bcbio-nextgen#1576]
Hi there:

  I'm interested in using the OptiType HLA genotyper with RNA-Seq data. I've done this using the stand-alone OptiType tool with good results so far, but I'd like to try scaling it up within the context of bcbio. 

  From a quick look at the code, the relevant section in [optitype.py](https://github.com/chapmanb/bcbio-nextgen/blob/8b1d1df4e046d78e256d1a7835c0db3abaf048de/bcbio/hla/optitype.py#L116) is:

```
        cmd = ("OptiTypePipeline.py -v --dna {opts} -o {tx_out_dir} "
                "-i {hla_fq} -c {config_file}")
```

... would need to be set to `--rna` rather than `--dna` to make this work. I could potentially help set up a pull request to include this if there's interest. Thoughts? Thanks for all your work on bcbio!

**Comment by chapmanb** [comment]
Thanks for the interest in adding OptiType to RNA-seq. Unfortunately this is going to be a bit bigger project to integrate within bcbio. We'd need to do two things:

- Be able to extract HLA reads from RNA-seq alignments. For variant calling this is done using hg38 HLA alternative alleles and bwa. I'm not sure if there's an equivalent approach to identify HLA reads as part of RNA-seq alignment steps. @roryk, do you know if we have an approach we could take with hg38?
- We'd need to include the HLA-typing process as part of the RNA-seq pipelines. Right now this is only run for variant calling since that's the only read extraction process we have.

We're happy to help as you implement this. Apologies it'll be a bigger project that initially envisioned but hope this helps for getting started.

**Comment by roryk** [comment]
How are you extracting the HLA reads for variant calling?

**Comment by chapmanb** [comment]
For variant calling, we use hg38 HLA alternative contigs and bwa extracts only the HLA aligning reads into separate fastq files that we can feed into OptiType. We'd need some equivalent upfront process to avoid needing to pre-process the full set of reads to extract only HLA aligners for RNA-seq, but not sure what the best approach is.

**Comment by rdocking** [comment]
Thanks for your response. It does indeed sound like this would be a bigger project than I was envisioning. 

When I've run this in the past, I haven't done any HLA read extraction prior to running OptiType. This means that _all_ the reads end up being re-aligned (and loaded into memory) as part of the OptiType run - I can see that this may cause run-time / memory issues if this approach was taken within bcbio. 

I haven't tested using bwa on hg38 to extract HLA-aligning reads from RNA-Seq data - I'm not sure whether it would work or not (or whether there's some other pre-processing approach that might work for bcbio).

Perhaps best to close this issue for now then. If I end up needing to scale this up dramatically, I can investigate read pre-processing steps that would allow for simpler integration with bcbio.

**Comment by chapmanb** [comment]
Thanks for following up on this. We'd definitely be happy to work with you if you want to re-explore this, just check back in and we'll reopen and tackle it. Thanks again.
