### ISSUE TITLE
dbNSFP 3.2a vs 3.2c

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1589]
Hi Brad,

Is there a reason bcbio uses the non academic version of dbNSFP (c instead of a)? Using the academic version would be useful, as this includes CADD scores and polyPhen2 annotations.

M

**Comment by chapmanb** [comment]
We're trying to make bcbio widely available for use in any institution, so try to avoid academic-only licensing where we can. For dbNSFP it's not totally clear if you can use dbNSFPa versions as a commercial company if you make use of other annotations and skip the problematic ones. Since GEMINI provides these, we skipped them here to avoid extra complexity.

That's the motivation, but happy to hear suggestions about how to best work around this issue.

**Comment by matthdsm** [comment]
I completely understand the reasoning behind this decision. Perhaps the CADD scores can be added using the VEP plugin since the CADD files are already present for gemini?

**Comment by matthdsm** [comment]
Or perhaps you could add an option to the installer using the `--datatarget`flag? Depending on the installed version, annotation fields could then be added/removed.
for example: `--datatarget dbsnfp-academic` or `--datatarget dbnsfp-commercial`

**Comment by chapmanb** [comment]
I'm a bit worried about adding extra complexity here. dbNSFP is difficult to support because of the giant file sizes and slow preparation process since the download doesn't ship as a ready bgzipped input. It can be quite time consuming to update and test this, so adding double the work doesn't seem worth the tradeoff here.

If CADD and polyPhen2 provide that much value over other methods, maybe the best approach is to contact the authors and see about how they feel about distributing them in a tool that could be used for both commercial and non-commercial purposes provided that we add a disclaimer that commercial users need to get a license to use those outputs. If that's a possibility we could go forward with the academic version only with the additional scores.

**Comment by matthdsm** [comment]
I agree dbNSFP is a bit cumbersome to process. If it's possible to add the disclaimer and use the academic version, it would be very helpfull for clinicians. This would be especially true for polyphen2, as CADD is already integrated into Gemini.

**Comment by chapmanb** [comment]
We moved the latest recipe to use the academic version -- see the discussion in #1571. Thanks again for the helpful feedback and hope this works for you.
