### ISSUE TITLE
[CWL] consider generating configuration files at runtime

### ISSUE THREAD

**Issue by mr-c** [chapmanb/bcbio-nextgen#1621]
http://www.commonwl.org/v1.0/UserGuide.html#Creating_files_at_runtime

**Comment by brainstorm** [comment]
Here's some context to this issue:

While running [bunny](https://github.com/rabix/bunny) with [`test_bcbio_cwl` pipeline](https://s3.amazonaws.com/bcbio/cwl/est_bcbio_cwl.tar.gz), @simonovic86 found that passing JSON directly under `sentinel-runtime` did not work because it had to be bash-escaped:

```
sentinel-runtime={"cores":8,"outdir":"/Users/janko/Desktop/test_bcbio_cwl/run_info-cwl-workflow/fcf61cad-cfe6-4491-a44f-d75a8c71d97b/root/alignment/prep_align_inputs","outdirSize":null,"ram":12743,"tmpdir":"/Users/janko/Desktop/test_bcbio_cwl/run_info-cwl-workflow/fcf61cad-cfe6-4491-a44f-d75a8c71d97b/root/alignment/prep_align_inputs","tmpdirSize":null}
``` 

While @simonovic86 is working on fixing it from the CWL spec bits outlined by @mr-c, I'll go ahead and introduce `sentinel-runtime-file` (instead of `sentinel-runtime`) on [bcbio-nextgen approapiate place](https://github.com/chapmanb/bcbio-nextgen/blob/1ff4b5bef6cbcf7e659bc5a9322cba495594dd2c/bcbio/distributed/runfn.py#L117) unless there is any other better place for that, @chapmanb ;)

**Comment by brainstorm** [comment]
@simonovic86, let me know when you're ready with the workflow tricks and if you have other issues with bcbio integration, the changes on our side are relatively simple as we saw (namely introducing `sentinel-runtime-file` extra parameter).
