### ISSUE TITLE
Passing FreeBayes frequency test when no normal information available

### ISSUE THREAD

**Issue by sambrightman** [chapmanb/bcbio-nextgen#1622]
At this line:

https://github.com/chapmanb/bcbio-nextgen/blob/af4701be303bd64ccb47b107d9be36cd606d278d/bcbio/variation/freebayes.py#L255

Frequency is set to zero when there is no normal information available (either "." in FreeBayes normal sample or sum(AO) + RO == 0, or invalid field content). This then passes the frequency filter due to being under the normal threshold.

The error cases don't seem equivalent to the case that sum(AO) == 0 with RO > 0. Our experience suggests that these are very often false positives - there is simply not enough information to say the tumor call is good.

**Comment by chapmanb** [comment]
Sam;
Thanks for starting the discussion. This implementation is on purpose to try and avoid filtering out calls which have no evidence in the normal. These definitely could contribute to false positives, because, as you say, there is not enough evidence to rule out the call being germline. On the other side, which is the stance we're taking here, there is also not enough evidence to be sure the call should be removed. We also use similar logic in checking LOD scores.

In cases of incomplete information like this we try to error on the side of passing too much rather than risk removing real variants. This is a case where having to make a yes/no decision like this is painful since the right answer would really be to report "maybe" and that we need more information.

Hope this helps in terms of the implementation logic. I'm happy to discuss better implementations that help improve how this gets conveyed in the final VCF.

**Comment by sambrightman** [comment]
I think this is skewed heavily towards false positives in practice, just wanted to alert you to that. We are seeing thousands and thousands of cases where there is a "tumor call" which is passed because the normal has poor coverage, FreeBayes says ".", but the deeper-sequenced tumor location passes this filter.

I would say the evidence is already there that no call can be made - FreeBayes outputs something because it is basically looking at the samples independently as I understand it. If you were looking at both samples together you would not make a call at a location with no information in one of them.

We aren't using this repo, so feel free to close the issue if you like the current method.

**Comment by chapmanb** [comment]
Sam -- sorry for dropping this discussion thread earlier. FreeBayes calls tumor and normal together so should have information to attempt to make a reference call if there is enough evidence there. A call in tumor and no-call in normal says you have coverage (and a variant) in the tumor and insufficient coverage in the normal. I guess this is a difference of an opinion about whether it's useful to know there is a tumor call even if you don't have normal evidence. I worry that you could throw away known variants by removing anything without normal coverage, especially in cases where you have uneven tumor and normal sequencing coverage. Thanks again for this discussion.

**Comment by sambrightman** [comment]
In what sense are the normal and tumor called together if there is no normal coverage at a given position? Can you really call it a _known_ (tumor) variant given that fact?

**Comment by chapmanb** [comment]
Sam;
They're called together since FreeBayes has reads from both tumor and normal when making calls, so will try to distinguish homozygous reference versus no call at that position. In this case there is evidence for a call in the tumor sample, but no read evidence in the normal to help us determine whether it is somatic or germline. In a sense, it's similar to calling with tumor but no normal at this position. You're right that the majority of these will be germline. This is the same as if you sequenced a tumor without the normal; a majority of those calls are germline. However, throwing them all out also throws out the minority which are somatic variants.

You're right that you don't know if it's somatic or germline, and that the majority are germline. My argument is that you also have somatic signal in there so if you filter them out you lose that signal. In the lack of normal evidence, we typically rely on prioritization schemes (http://bcb.io/2015/03/05/cancerval/) for these tumor only cases as the best way to try and reduce the background. Hope that helps explain the thinking.

**Comment by sambrightman** [comment]
Sounds like it would make sense to discard these in your matched normal path but keep them in the without-normal path?

**Comment by chapmanb** [comment]
Sam;
I was only trying to draw a parallel between this case: matched tumor/normal with no normal coverage at a region, and tumor-only calling. You'd interpret both the same way, as a variant in the tumor without any sample specific knowledge about whether it's somatic or germline.

**Comment by lpantano** [comment]
Hi Sam,

I will close this guessing you all the information you needed. Let us know if you find more issues.

Thanks!
