### ISSUE TITLE
error when installing bcbio

### ISSUE THREAD

**Issue by csmatyi** [chapmanb/bcbio-nextgen#1633]
Hello all,

Trying to install bcbio on Linux server but ran into these errors:

    perl-error-0.17024         |                0          10 KB  bioconda
    perl-error:                        0.17024-0               bioconda
perl-error-0.1 100% |###############################| Time: 0:00:00   1.82 MB/s
[      COMPLETE      ]|##################################################| 100%
2016-11-07 18:15:21 ERROR 404: Not Found.
Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O GRCh37-rtg.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz''
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/path/to/bin/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 1
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/path/to/bin/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/path/to/bin/bcbio', '--genomes', 'GRCh37', '--genomes', 'mm10', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

Could someone help me with this?

Thanks, MC

**Comment by chapmanb** [comment]
MC -- thanks for the report and sorry about the issue. The download for GRCh37-rtg is expected to fail since we don't have a pre-created RTG database for these resources due to size. However, the install should recover from this and run rtg locally to create it, which I guess is the step that actually fails. Do you find other errors related to rtg in addition to what you pasted above? You might need to include `/path/to/bin/bcbio/bin` in your PATH to ensure we're able to access rtg. Happy to provide more specifics with additional details about the error. Hope this helps.

**Comment by csmatyi** [comment]
Hello Dr. Chapman,
Thanks for your reply,

"You might need to include /path/to/bin/bcbio/bin"

Yes, I did include that directory to PATH, like so:
export PATH=/path/to/bin/bcbio/bin:$PATH

In my very first post I provided lines from an error file like so:

grep -i error err_file.txt

It seems that this is an error line related to rtg:

Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O GRCh37-rtg.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz''


Also, I tried accessing https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz but that file is missing, wouldn't it be better if you made that file available and modified the bcbio_nextgen_install.py script accordingly?

Thanks, MC

**Comment by chapmanb** [comment]
MC -- as mentioned above, we can't make pre-built tarballs of all of the resources available due to the size of some indices. So the 404 is expected and we fall back to building locally.

If you provide the full error log as a gist (http://gist.github.com/) we may be able to spot the issue. Hope this helps.

**Comment by csmatyi** [comment]
Hello Dr. Chapman,

Here is my gist:

https://gist.github.com/csmatyi/b853b1f19b3f35d195b095280f6e5bf5

**Comment by csmatyi** [comment]
What kind of permissions do I need on /path/to/bin/bcbio/bin ?

**Comment by chapmanb** [comment]
Thanks for posting the full log. The informative error message is here:
```
--2016-11-07 19:00:46--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/2.8/b37/1000G_phase1.snps.
high_confidence.b37.vcf.gz
           => “-”
Resolving ftp.broadinstitute.org... 69.173.80.251
Connecting to ftp.broadinstitute.org|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ... 
Login incorrect.
```
The GATK FTP site can be unreliable under load so this is likely a one-off failure. If you re-run your install command it will pick up where it left off and hopefully access the Broad FTP site correctly. Hope this fixes it for you and please feel free to re-open the issue if you run into any other problems.
