### ISSUE TITLE
Upgrade freebayes to v1.1.0 , should be 4 x faster

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1634]
Hi,

Would it be possible to include Freebayes v.1.1.0 in the upcoming bcbio release. 

It should be 4x faster and much more memory efficient by swapping out the BamTools library for the more memory efficient SeqLib library for reading Bam files.  

See 
https://github.com/ekg/freebayes/releases/tag/v1.1.0
https://github.com/ekg/freebayes/pull/316

Thank you.

**Comment by chapmanb** [comment]
Neill;
Thanks for the suggestion. We're definitely planning to validate and update to FreeBayes 1.1.0, the SeqLib integration is a great improvement. I'll take this on as a post-release task though, as we're trying not to get any new updates in there so we can have a release. Normally new versions of variant callers take some testing and tweaks (we're still pushing fixes for GATK 3.6 which has been delaying this release). Hope that will work with you and thanks again.

**Comment by NeillGibson** [comment]
Good to know that it will be included in a upcoming release and that it first will be validated. Thank you.

**Comment by chapmanb** [comment]
Neill;
The latest development version of bcbio now supports v1.1.0 with a small change since it fixes an issue we were working around in 1.0.2. We'll still need to default to 1.0.2-29 until the next release because of this but you can now manually install from conda with:
```
bcbio_conda install -c bioconda freebayes=1.1.0
```
The validations look great, it is identical to the previous version and has all the speed/memory improvements you mentioned:

https://github.com/bcbio/bcbio.github.io/blob/master/_posts/2016-11-21-giab-hg38-freebayes.md

We'll also validate on somatic calling but I don't anticipate issues given how consistent this looks. Thanks again for promoting this and looking forward to having it be the default in the next release.

**Comment by NeillGibson** [comment]
Thank you Brad. Very nice to have the new and faster Freebayes available!
