### ISSUE TITLE
SEQ and QUAL are of different length

### ISSUE THREAD

**Issue by deber1980** [chapmanb/bcbio-nextgen#1639]
Hello,

I'm getting the error below while running pipeline. Is there any practical way to debug this? I guess the problem might be with the files themselves but they are huge....

Thanks,
Y.

[fputs] Broken pipe
[E::sam_parse1] incomplete aux field
[W::sam_read1] parse error at line 259549
[bam_sort_core] truncated file. Aborting.
[E::sam_parse1] SEQ and QUAL are of different length
[W::sam_read1] parse error at line 170753
[bam_sort_core] truncated file. Aborting.
[W::sam_read1] parse error at line 27387614
[main_samview] truncated file.
' returned non-zero exit status 1
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the problem, we'd likely need more information about your run to be able to debug this. It's typically due to some sort of memory issue during the run. If you're using 0.9.9 the latest development version has some fixes to try and improve resource usage during the alignment process and also does automatic splitting of alignments for giant BAM files to avoid problems. If you're already using the latest development, a full traceback and understanding of the sample YAML you're using could help us try to provide more helpful information.

**Comment by deber1980** [comment]
I'm running a version from about 1-2 weeks ago (dev).
I provided a description of the configuration and what I'm doing in #1526  
Is there a way to work around it? Use less threads when running bcbio for instance?  Can I increase samblaster memory?

**Comment by chapmanb** [comment]
Thanks for the additional details. I'll answer these questions in the other thread and close this to keep the discussion in one place.
