### ISSUE TITLE
Providing multi-sample VCF when SV calling with LUMPY 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1648]
Hi, 

I am trying out structural variant calling that can be done with LUMPY within bcbio. 

In the final output directory I only see single sample VCF files with the called and typed structural variants per sample. 

There is not a multi-sample VCF file, is there a rationale behind this?

Thank you.

**Comment by NeillGibson** [comment]
The single sample VCF files have the same number of records and even the variant INFO attributes seem to be identical for 3 random structural variant records over the single sample VCF files. 

`bcftools merge -l vcf.list  -m none` seems to be able to merge the list of single sample VCF files to a multi-sample VCF file. 

I am interested in having the multi-sample SV VCF file for filtering out monomorph SV's and / or selecting SV's that have a certain allele frequency.

**Comment by chapmanb** [comment]
Neill;
During structural variant calling the samples get called together in a pool to enable callers to take advantage of multiple samples. This is why sites and INFO fields will be identical for anything analyzed in a batch. Following calling, we split the VCF into samples to do the separate genotyping step which determines if each contains the variation or is reference. We don't merge them back again together to try and make it easier to do downstream single sample analysis. So far, most uses of SV calling have been for assessing a sample rather than population level analysis. Does post-merging of VCFs work for you or should this be incorporated into the bcbio preparation process?

**Comment by NeillGibson** [comment]
Hi Brad,  thank you for explaining the rationale and how the process works. 
I can do the merging myself. Just wanted to double check that things make sense.
