### ISSUE TITLE
Single-cell WGS

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1650]
Hi there, is anyone working on single-cell WGS analyses in bcbio, or is interested in doing so in Q1/Q2 2017? I'd like to set something up focusing on cancer genomics and immunobiology. We're agnostic concerning the kit or analysis procedure, but I'd like to hook up with the current best practises and the existing single-cell RNA-Seq code in bcbio.

**Comment by chapmanb** [comment]
Sven-Eric;
We've recently been working on incorporating additional UMI support into bcbio variant calling, but primarily with the goal of better differentiating and removing duplicates by collapsing into consensus reads using fgbio (https://github.com/fulcrumgenomics/fgbio). @roryk added support recently to the umis library (https://github.com/vals/umis) to better handle WGS for this by putting tags into read names and translating into BAM tags (rather than needing to read a fastq file of UMIs into memory), so we're hoping to incorporate that.

Do you have single cell variant calling analysis methods you think are worth incorporating? I haven't dealt with this data for variant calling so don't have practical experience but would be happy to hear what you and others have been using successfully. Thanks for starting this discussion.

**Comment by schelhorn** [comment]
Thanks, Brad. Let's move that offline so that we don't clutter the issues list. I'll contact you once we know more internally.
