### ISSUE TITLE
Built in validation

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1652]
Hi Brad,

We've sequenced GiB (exome) in house, and we would like to validate the results using the built in validation option.

Could you explain shortly what results we should get from the resulting report? The one that was generated now just looks like a reformatted fastqc report with some coverage information. Shouldn't there be more information included?

Thanks!
M

**Comment by chapmanb** [comment]
The validation report currently doesn't go into the consolidated MulitQC report, although that would be a useful thing to add. Thank you for the suggestion. You should get validation plots for your samples in `final/*/*-validate.png` that are similar to the plots in comparisons we report on (http://chapmanb.imgur.com/). Hope this provides what you need.

**Comment by gabeng** [comment]
Hi Brad,

you are doing a tremendous job regarding validation. Thanks for posting the link to your benchmarks and comparisons.  I am trying myself to perform some benchmarking and validation for Whole Exome sequencing. 
I am a little confused by your charts titled "Exome capture comparison" (http://imgur.com/a/X759f). In the first image, the caption says that you applied the same .bed file to all experiments. I would then expect that you are looking for the same constant number of variants (your truth set) in all experiments. Why do TP+FN not add up to the same number? They do in all your WGS comparisons.
Which "Exome" .bed did you actually apply here?
A related question is: Which .bed file does bcbio apply for qc (fastqc, qualimap)? The one provided with the "coverage" config item? Can I change that .bed file after I ran alignment and variant calling by deleting some directories in `work/` and repeating the job?
Now about the Edgebio Exome example that you provide with bcbio: Can you tell me which Kit this is (NGv3.bed)? Coverage seems to be quite low (if I can trust the results from fastqc/qualimap). Fastqc reports an error regarding read length distribution. Low coverage may also be the reason for so many FN (6%). 

Thanks again for making your comparison data public. It would be extremely valuable if the results from your validation examples could be made pubilc with every bcbio release.

Regards,
Ben

**Comment by matthdsm** [comment]
Hi Brad,

Is there an example pipeline to validate exomes against giab on hg38? Or can I just modify the example  exome pipeline to use hg38 instead of GRCh37?

Thanks
M

**Comment by chapmanb** [comment]
Ben and Matthias -- sorry about the delay in responding to this thread.

Ben -- we're working on writing up more details on the exome capture comparison which will hopefully help with context but to answer your specific questions:

- We put together a respository with the BED files used, including the older Nimblegen array here: https://github.com/AstraZeneca-NGS/reference_data
- The comparisons are done using a standard inclusive exome region across all the methods (Exome-AZ_V2). The validations are the interesections of this region and the covered regions from the specific capture. So where kits have lower numbers, they have less overall coverage across the region. So you need to consider both these numbers as well as coverage metrics in MultiQC reporting to get a full picture of how an exome capture kit performs. Often evaluating these is a tradeoff between total coverage and even-ness of depth and calling across regions that do have good coverage.
- Here is more documentation about the how the different BED file choices in the configuration get used for coverage estimation in the MultiQC report: http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#analysis-regions
- The EdgeBio data is getting a bit dated at this point so is lower coverage due to being a few years old. Hopefully we can make some additional test data available as part of this new exome comparison work.

Matthias -- we do have an hg38 whole genome validation set here: http://bcbio-nextgen.readthedocs.io/en/latest/contents/testing.html#human-genome-build-38, but not an exome. Practically, changing the `genome_build` to hg38 is all you need to do to run the exome comparison here on build 38.

**Comment by gabeng** [comment]
Brad,

Thanks for the additional info. That explains a lot.
* The BED repository is very helpful! In terms of most widely used kits the Illumina Nextera Rapid Capture and the Trusight One (albeit "just" a Clinical Exome) are also on my list. These are the ones that I encounter most frequently in a clinical setting.
* Would a comparison with a standardized reference not yield a better (absolute) measure of performance? Clinicians typically ask about fraction of bp covered in CCDS. Sure, the smaller kits would automatically perform worse, but it would be just one of many indicators to look at. It certainly is relevant in the clinic. As soon as I figured out how to obtain a decent .bed file for the most recent CCDS on hg19, I will add this to my validation procedure.
* Maybe you can clarify a few things that are not quite clear to me from the documentation (and some of these may be user errors, some bug reports - will gladly submit separate tickets if you feel that is appropriate). : 
  * I need coverage reporting to be performed with a .bed file different from the variant calling .bed, e. g. the set of CCDS. I thought the "coverage" key would be the thing to use.
  * Coverage seems to be calculated from a *_merged.bed file. How can this be different from the file defined in "coverage"?
  * Fastqc sequence length distribution always reports that all inserts have identical length. Qualimap creates a realistic histogram contradicting that.
  * Qualimap, however, reports coverage always with respect to the entire genome. Despite it being called with the .bed file as argument. This does not make sense for targeted sequencing. Since I have not found anyone else reporting this issue, I may be doing something extremely stupid.

Any help is much appreciated.

Regards
Ben

**Comment by gabeng** [comment]
Specifically, I am looking at Illumina data from NA12878 as described here: https://blog.basespace.illumina.com/2015/01/14/variant-calling-assessment-using-platinum-genomes-nist-genome-in-a-bottle-and-vcat-2-0/
* This is the MultiQC report https://s3-eu-west-1.amazonaws.com/bcbio-exome-validation/final/2016-11-27_NA12878-nextera-merged/multiqc/multiqc_report.html
Note that Fastqc reports a strange sequence length distribution that seems cut-off at 150bp. I do not quite understand why Qualimyp reports Genome coverage in the summary statistics.
* This is one of the Qualimap reports: https://s3-eu-west-1.amazonaws.com/bcbio-exome-validation/final/FC1-NA12878-01/qc/qualimap/qualimapReport.html

**Comment by chapmanb** [comment]
Ben;
Thanks for all the questions and discussion:

- I agree about coverage over a standard region being important and this is what 'Coverage Profile` and 'Coverage Profile Along Regions' are meant to assess. When evaluating we use these to determine how much of a standard region a capture kit covers, then use the validation to assess how well variants get called within the captured regions.
- `coverage` is the right place to put a standard BED file for assessment.
- `_merged.bed` is the same as the input but it collapses any overlapping regions (and cleans up headers and other things that can mess up downstream tools). So it's equivalent to your input.
- FastQC's 'Sequence Length Distribution' plot is the length of the reads, not the insert size distribution. So it's reflecting that you have 150bp reads with some trimmed/slightly shorter. MultiQC is the only one reporting insert size distribution.
- For QualiMap's coverage estimation, in 'Coverage Histogram' and 'Genome Fraction Coverage' I'll need to defer to @vladsaveliev He had just reworked all of this and I believe it is meant to show coverage across the BED target. Vlad, is this right? Ben, what version of bcbio are you using for this? We just re-worked a lot of this as part of the recent release so some improvements might be in the latest development version (`bcbio_nextgen.py upgrade -u development`).

Thanks again, hope this helps.

**Comment by gabeng** [comment]
Brad,
after updating to the development branch, the coverage is now reported correctly by QualiMap. 
Thanks!
Ben

**Comment by chapmanb** [comment]
Brilliant, thanks for confirming this is working correctly in the development version. We'll plan to have a new release soon with all these fixes. Please feel free to reopen the discussion if you run into any more problems.
