### ISSUE TITLE
Coverage parallel processing

### ISSUE THREAD

**Issue by gabeng** [chapmanb/bcbio-nextgen#1655]
Hi,

there have been several questions regarding parallel processing of steps inbetween alignment and variant calling, but I was not able to find an answer to my problem.
I am mostly working with targeted sequencing, WES samples in particular. I ran 12 Samples on a 32 core machine with 5 cores per job. bcbio started 6 jobs à 5 cores as expected. When alignment was completed, 5 jobs were started for coverage calculation with 1 core each which went extremely slow.
Alginment wall clock time:  3h 20min
Coverage wall clock time: 5h 20min

How can I optimize the total wall clock time in this setting? Should I adjust the parameters such that all samples run in parallel? In the documentation you recommend that for runs with few samples on a single machine the `cores` setting should match the total number of cores on the machine. That would slow this process down even more, I think. Any input is highly appreciated.

Regards,
Ben

**Comment by mjafin** [comment]
HI @gabeng I think I'm seeing the same issue as you and I think it's server specific. We have some 32 core servers from around 2011 that are connected to super fast storage via fibre links and they perform a lot worse in the coverage estimation and VarDict variant calling than older, NFS connected 12-core servers. I guess what I'm trying to say is that the issue is not with the storage per se but the server type maybe somehow (could be a red herring of course). Here are a few of my tests:
1. Three 8-thread coverage jobs on said 32 core server took several hours to run in parallel (each using ~50% of a CPU instead of the expected 600%-800%) but one 8-thread job on an identical server took 50 minutes. 
2. On a different kind, 40 core server the `goleft` coverage jobs were each using 600% CPU even when I was running 3 in parallel (so all good)

On a separate note, when I run VarDictJava in parallel, the 32-core servers ground to a total halt whereas I can use our old cluster of 12- and 8-core servers to process the exomes 30x(!) faster. Our HPC admins have been looking into the issue and can't pinpoint the exact cause. They claim there is no I/O wait and blame the architechture of the 32 core servers. But it's all anecdotal.

**Comment by gabeng** [comment]
Hi @mjafin,

thanks for your comment. If many threads of coverage calculation were started in parallel in my process, I would be fine. However, only 6 jobs with 1 thread (core) each are started resulting in about 20% overall CPU utilization. I suspect that the number of parallel coverage jobs equals the number of parallel alignment jobs (6 in my case). It also seems that coverage calculation cannot be/is not parallelized.
I am using an r3.8xlarge with EFS (NFS) on AWS. There is definitely no bottleneck with storage as far as I can tell. Those 6 cores are well utilized, too.

Regards,
Ben

**Comment by mjafin** [comment]
Brad's best to answer this but if you're on `0.9.9` it should be using more than one thread. If you look at the `bcbio-nextgen-commands.log` what does it say for `goleft` threads? Is it 5 or 1?

**Comment by chapmanb** [comment]
Ben -- thanks for the report and sorry about the problems. Miika is right on in that the coverage parallelization for single machine runs is greatly improved in the 1.0.0 release. The behavior you describe was how it used to work in 0.9.9 prior to including goleft for coverage estimation. If you are running the latest version and still running into this problem happy to debug further if you could pass along `log/bcbio-nextgen-debug.log` as a Gist (https://gist.github.com/). Hope this helps.

**Comment by gabeng** [comment]
Hi Brad,
I am using 1.0.0. This is the log file: https://gist.github.com/gabeng/18456aee48c334f5b1aca5d5b5c7ef2e
Thanks for taking a look at this!
--
Ben

**Comment by chapmanb** [comment]
Ben;
Thanks for passing that along, it looks like bcbio is calculating everything right and running 6 jobs with 5 cores each. There appear to be 12 samples and each block of 6 takes ~3 hours leading to the time in calculation you're seeing:
```
[:~] $ grep 'Calculate coverage' bcbio-nextgen-debug.log
[2016-11-28T02:10Z] Calculate coverage: FC1-NA12891-08
[2016-11-28T02:10Z] Calculate coverage: FC1-NA12892-06
[2016-11-28T02:10Z] Calculate coverage: FC1-NA12878-01
[2016-11-28T02:10Z] Calculate coverage: FC1-NA12891-05
[2016-11-28T02:10Z] Calculate coverage: FC1-NA12878-04
[2016-11-28T02:10Z] Calculate coverage: FC1-NA12878-07
[2016-11-28T05:12Z] Calculate coverage: FC1-NA12892-09
[2016-11-28T05:12Z] Calculate coverage: FC1-NA12891-02
[2016-11-28T05:12Z] Calculate coverage: FC1-NA12892-12
[2016-11-28T05:12Z] Calculate coverage: FC1-NA12878-10
[2016-11-28T05:12Z] Calculate coverage: FC1-NA12891-11
[2016-11-28T05:13Z] Calculate coverage: FC1-NA12892-03
```
 If you look at the commands:
```
grep goleft log/bcbio-nextgen-commands.log
```
is goleft using 5 cores (`--processes 5`) for each run? If not we can definitely investigate to see if we can improve usage there for this situation. Hope this helps.

**Comment by gabeng** [comment]
Dear Brad,

I apologize. You are absolutely right, bcbio does everything right. The issue is the I/O latency of AWS Elastic File System (EFS). I misinterpreted the performance specs of the standard configuration. I am now creating an SSD volume with my spot instances and this works as it should!
Too bad that EFS is not suitable for coverage calcluations (at least not in standard config), it was so simple to set up.

Ben
