### ISSUE TITLE
S3 metadata set to binary/octet-stream for html files

### ISSUE THREAD

**Issue by gabeng** [chapmanb/bcbio-nextgen#1682]
Hi,
I like the feature to automatically sync the results to an S3 bucket after processing finished. Unfortunately, some strange metadata is set during upload such that html files (multiqc reports etc.) cannot be opened directly in the browser from a webhosting-enabled S3 bucket. This would be so convenient.
Content-type should be text/html for html files. AWS cli does this correctly.

Thanks,
Ben

**Comment by chapmanb** [comment]
Ben;
Thanks for the feedback and noticing this issue. We had both aws cli based upload and gof3r upload enabled in parallel, but previously defaulted to gof3r since it was previously a more efficient approach. Now the aws cli implementation is as performant at splitting up uploads so it makes sense to swap over as the default. I pushed this fix in the latest development so if you update with `bcbio_nextgen.py upgrade -u development` is will hopefully do the right thing. Thanks again for the suggestion.
