### ISSUE TITLE
Are Freebayes VCF files hard filtered in bcbio? 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1684]
Hi, 

Are the Freebayes germline VCF files (analysis: variant2) hard filtered? 

Is see a difference in file size and record count between the unfiltered an filtered VCF files in the freebayes directory. 

- `final VCF file` = 15.250.349
- `work unfiltered VCF file` = 15.250.349
- `work filtered VCF file` = 15.298.302

What I get from the final VCF header is that during variant calling filtering is done on symbolic alt alleles and QUAL below 5. 
`##bcftools_filterCommand=filter -i 'ALT="<*>" || QUAL > 5'`

Then a soft filter is applied after variant calling
`##bcftools_filterCommand=filter -O v -T /work/bedprep/Project123-sort-callable-callableblocks.bed.gz --soft-filter FBQualDepth -e '(AF[0] <= 0.5 && (DP < 4 || (DP < 13 && %QUAL < 10))) || (AF[0] > 0.5 && (DP < 4 && %QUAL < 50)) || (%QUAL < 10898.0 && DP > 5449 && AF[0] <= 0.5)' -m + /work/freebayes/Project123.vcf.gz`

This only does soft filtering and results in records for which the expression is true to have  FBQualDepth  in the FILTER column. 

But why does the` filtered work VCF file` (and the `final VCF file`) then have less records than the `unfiltered work VCF file`?

For some of our variant callings the difference is thousands of variants, for others it's millions (might be related with quality of the reference and number of low qual variants ?)

The code also mentions that hard filtering is done in the documentation. That is also written to the log file. But in the "Hard filter" code I only see the command for soft filtering being created and executed. 
https://github.com/chapmanb/bcbio-nextgen/blob/98c12fdaa8ce6ab9c6c1fdfb4db39df9c7b548ff/bcbio/variation/vfilter.py#L120

So why does the `work filtered VCF file` have less records than the `work unfiltered VCF file`  if only soft filtering is done and no hard filtering? Or is there an additional hard filter step? Maybe mixed in with the soft filtering?

Thank you.

**Comment by chapmanb** [comment]
Neill;
Thanks for digging into this. The only intentional hard filter in bcbio for FreeBayes is the initial `QUAL > 5`, and the remainder should be soft filters adding flags to the FILTER column. Apologies for the confusion in the code documentation. I switched the language to say cutoff-based soft filtering, which is what we're doing, versus hard filtering. The "hard" was meant to distinguish from non-cutoff based methods like VQSR, but I can see the confusion.

Getting back to the issue, could you run:
```
zgrep -c -v ^# freebayes/*.vcf.gz
```
which would give a better sense of which files you're referring to. I'm not sure which the `work filtered VCF file` is, and how it gained more variants than the unfiltered.

During soft-filtering we do also apply a region based exclusion if you have `variant_regions` defined, which might explain losing some variants. bcbio can call outside of `variant_regions` depending on the parallelization breakpoints but then removes any of these during this step. Could that explain the differences you're seeing?

Thanks again for the discussion and hope this helps.

**Comment by NeillGibson** [comment]
Hi Brad. Thank you for the explanation and updating the docs.  I now indeed see that there is a `-T *callableblocks.bed.gz` in the bcftools soft filter command.  That is probably causing the filtered variants. 

I'll try to run that bcftools filter command without the `callable blocks bed` as the target.

With the `callable blocks bed`  I get ca 49K less variants for this smaller variant calling and millions less in a very big variant calling that has a large set of diverse samples and a large reference. 
```
zgrep -c -v ^# freebayes/*.vcf.gz
freebayes/Project_123-filter.vcf.gz:8,250,349
freebayes/Project_123.vcf.gz:8,298,302
```

**Comment by NeillGibson** [comment]
The target bed file causes the 48K filtered variants. Thank you.

**Comment by stephenturner** [comment]
I'm trying to go through the documentation now to find documentation/explanation about what the defaults are for the cutoff-based soft filtering that's used by default in the [freebayes / variant2](https://github.com/chapmanb/bcbio-nextgen/blob/master/config/templates/freebayes-variant.yaml) analysis. Any pointers? Thanks!

**Comment by chapmanb** [comment]
Stephen;
The description and details of the FreeBayes soft filters are here:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/vfilter.py#L121

It's a combination of a bcftools based cutoffs for low-depth variants and removal of high depth repeat variants. Hope this helps.

**Comment by stephenturner** [comment]
Thanks for that clarification!
