### ISSUE TITLE
heads up, bioconda vep recipe broken

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1687]
Hi Brad,

Just a heads up regarding the changes to vep. The current recipe in bioconda doesn't work out of the box, due a broken bioperl recipe. 

I'm trying to fix this right now, but I you have a quick solution, please go right ahead. I'm also planning an update to v87, so perhaps it'll be possible to do both at the same time.

M

**Comment by matthdsm** [comment]
PR for new vep with bioperl fix: bioconda/bioconda-recipes#3177

**Comment by chapmanb** [comment]
Matthias;
Thanks for the heads up and your work on this. We can definitely migrate to the fixed version when ready. Apologies, it looks like there has been a lot of churn in the Perl bioconda recipes since I initially put this together.

Once we have this in place I'd like to lock down on the VEP and dbNSFP versions. I'm sensitive to the amount of work we're forcing for upgrades by continually bumping versions on large, slow downloads and would like to provide some stability for users once we have everything working cleanly. Thanks again.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for the feedback, you might have noticed I asked you to be a reviewer on the PR. The reason I'm pushing a bit harder on the updates is because we're going to take bcbio into production soon, and it would be nice to have the latest and greatest. I don't suppose there will be any more upgrades soon, since all the new stuff has a somewhat slow refresh cycle and just got updated this month.

I might have some more suggestions and modifications down the line, but those won't affect any major functionality. That'll be something to discuss after the holidays however.

M

**Comment by matthdsm** [comment]
Recipe is fixed and merged!
