### ISSUE TITLE
CNVkit 0.8.2 - much faster for WGS cases

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1695]
Hello, by extension of my previous (now rightly closed) issue https://github.com/chapmanb/bcbio-nextgen/issues/1657, I'd like to report that @etal has published CNVkit `0.8.2` on bioconda and this release is now significantly faster on WGS samples while generating (nearly, as described in the [release notes](https://github.com/etal/cnvkit/releases)) identical results. In particular, the `call` step with a 3M variants WGS VCF file that took about 36 GB peak RAM before now  only takes about 3 GB (!) and also 10% of the run time. I strongly encourage bcbio to go with that update. 

In our optimized/hacked setup, I have also added the `-p` thread parameter the to CNVkit `coverage` and `metrics` commands to go with `4` cores each (side remark: shouldn't `coverage` be replaced by `goleft` by now?). This clearly helps runtime a lot and doesn't make trouble with memory requirements (<16 GB for WGS), so I recommend that multiple cores per CNVkit process should be offered as an option in bcbio as well and be derived from the core settings for CNVkit in the `system.yaml`, so that users can decide on their own how many cores to dedicate to the process.

Be minded that the [release notes](https://github.com/etal/cnvkit/releases) mention other changes under the hood, so perhaps we'd need testing with WES samples in bcbio as well to see if any of the modifications cause unexpected integration errors (have you checked by running the new release also within bcbio, @etal?)

**Comment by etal** [comment]
Wow, sounds like VCF parsing was taking up a huge portion of the runtime and using pysam for it was the right call.

The visible differences from v0.8.2 are minor enough that I went with a point release instead of 0.9. The commands gained some options but didn't lose any, and the change in binning will only bite you if you have a sloppy working directory, i.e. are not using bcbio. I haven't tested the changes myself, but:

- The `cn1`/`cn2`/`baf` changes might need to be addressed in bcbio.
- Annotating target bins with gene names from UCSC refFlat.txt was reimplemented and could look different. If you have gene models in another format 
- The default output file names could be different if the BAMs have multiple dots in the filename, but bcbio already handles this with the `-o` option everywhere.
- The VCF parsing should work better with the output of more callers, but please let me know if CNVkit still isn't loading a certain caller's VCF properly.
- Useful features in `access` (from an earlier release):
  - You can exclude low-mappability regions from the access BED with `-x`.
  - The `antitarget` command will drop any alternative/haplotype contigs in the genome (i.e. access BED) if they were not targeted, so `_remove_haplotype_chroms` may not be necessary anymore for exome and amplicon capture. Once the access and target BED files are clean, the additional chromosomes won't be included downstream.

I recall `goleft` used a binning approach that was nearly but not quite compatible with CNVkit's `coverage` command -- which uses one shot of `bedcov` in pysam/htslib under the hood, so the inner loop is unlikely to be much slower than `goleft`. CNVkit also counts all reads instead of filtering by Q30. Reducing any redundancy would be nice though.

**Comment by schelhorn** [comment]
Sounds great to me, @etal. Also, VarDict has been updated yesterday as well (on conda), and according to Miika it's _da bomb_ (okay, I'm paraphrasing). I suggest we go with both.

**Comment by mjafin** [comment]
VarDictJava 1.4.8 is indeed (da bomb) fresh out of the oven and has much improved performance when running multiple VarDictJavas on bigger servers. It used to spend a lot of time just waiting for information from the genome fasta and input bam file but both are now cached in a smart and RAM-efficient manner. We're getting really good performance on some servers that were previously unusable. Comically, it was the newer, shinier 32 thread servers that sucked and the 10 year old 8-12 thread servers that were much, much faster.

**Comment by chapmanb** [comment]
Sven-Eric and Eric;
Thanks for all the thoughts and suggestions. bcbio should work cleanly with 0.8.2 and I pushed a fix to the bioconda pysam recipe (bioconda/bioconda-recipes#3246) so it'll now get installed along with bcbio. It was a version issue causing 0.8.1 to be inadvertently preferred.

I also am testing fixes to drop bcbio specific parallelism and use `-p` for `coverage` and `segment` directly from cnvkit. That should enable better single machine parallelism (#1582) immediately. After the next release I'd also like to move coverage calculation to happen with goleft at a single point in the process, and will tackle that as well.

Thanks for all the thoughts and suggestions as migrate this to be quicker.

**Comment by schelhorn** [comment]
Thank you, Brad - closing.
