### ISSUE TITLE
How make migration of bcbio to another cluster or directory  

### ISSUE THREAD

**Issue by MIAOKUI** [chapmanb/bcbio-nextgen#1719]
Hi Chapmanb,

Our company just buy a new cluster. So I'd like to migrate bcbio from my old server to the new cluster. But the problem is the directory structure cannot be the same. So is there any way to make migration with different directory structures ? Or which config file should I change to make bcbio work nicely in new location ? 

Thank you for your help !

**Comment by chapmanb** [comment]
The best approach is to re-install bcbio on the new cluster. It's not easily re-locatable via copying due to full path specifications inside the configuration and anaconda directories. It would be a lot of work to enable this because anaconda, used to manage the tool installation, sets up full paths inside of scripts. We've instead been focusing on support for containers like Docker and singularily which provide a better long term vision for making this possible.

Hopefully a re-install works cleanly on your new system.

**Comment by MIAOKUI** [comment]
The only problem for me to re-install all of them is the network problem. In the new cluster, the network is very bad, cannot visit website outside China steadily and also cannot use vpn. So my strategy is install all of the packages on my personal laptop based on same directory structure and in-plant  all of them to the new cluster manually. But downloading still very slow.  I cannot figure out better way to do this .

**Comment by chapmanb** [comment]
Sorry about the issues. I understand the problem and wish we had a better way to work around it but don't have any sort of procedure for copying between systems because of all the places where absolute paths get used in the tool and data configurations. My only suggestion would be to write something to manually walk over all the files in the bcbio installation and replace the old absolute path on your machine with the new absolute path on the server. Sorry to not have a nicer way to deal with this but hope that helps.

**Comment by schelhorn** [comment]
What about making an [offline conda](http://stackoverflow.com/questions/31729731/how-can-i-install-a-conda-environment-when-offline) repo and copy that to the firewalled cluster and install from there? You'd need to seperately copy over all the bcbio references and databases as well, of course.

**Comment by MIAOKUI** [comment]
I think this is a good idea. I'll try it out. Thanks for this suggestions
