### ISSUE TITLE
Moniter progress and increase performance of Manta for structural variant calling. 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1721]
Hi, 

I am using manta to do structural variant calling for small cohorts of 100 to 200  WGS samples. 

Is there a way to monitor the progress of Manta?

I see manta output in the bcbio-debug.log file but I am not sure how to interpret this as in how much work is already done / still needs to be done. 

Both diploid and candidate VCF files are being created with a counting number. E.g. 
```
bcbiotx/tmp81flYH/manta/workspace/svHyGen/diploidSV.0186.vcf
bcbiotx/tmp81flYH/manta/workspace/svHyGen/candidateSV.0136.vcf
```
Can the number of VCF files, or the numbers in the VCF file names, be used as an indicator of progress. 

Also I noticed in the the `bcbio-command.log `that manta is submitted from bcbio as a single sge job with 10 cpu. I specified 60 cpu for bcbio.  10 cpu is the default job size that I have in galaxy/bcbio_system.yaml 
`bcbiotx/tmp81flYH/manta/runWorkflow.py -m local -j 10`

Does manta benefit from more CPU? Do you have an recommendation for the number of CPU to give to manta in `galaxy/bcbio_system.yaml `that it can make use of?

E.g.
```
manta:
    cores: 50
```

Thank you.

**Comment by chapmanb** [comment]
Neill;
Manta uses an internal workflow system called pyflow for running tasks, and the detailed logs for that should be in:
```
your_txworkdir/workspace/pyflow.data/logs/pyflow_log.txt
```
That's the best way to monitor the status of the job. It's pretty verbose so bcbio doesn't replicate all of the output to stdout/stderr for logging.

I'm not sure about the relative speed advantages of running 6 10-core jobs versus 1 60-core jobs and you'd probably have to benchmark to determine the best setting. Practically I haven't done a ton of digging into manta performance since it's fairly fast on its own. Are you seeing a lot of bottlenecks at this step? Thanks for the thoughts and digging into it, I'd be interested in hearing what you learn.

**Comment by NeillGibson** [comment]
Thank you Brad for the answer. 

In the manta log I found lines like these that indicate I think how many VCF files will be produced. 
`[WorkflowRunner] Adding command task 'generateCandidateSV_0255' to master workflow`

These log lines are also replicated to the bcbio-debug log. 

I think the number of these tasks that are submitted equals the number of VCF files that will be produced. 

```
grep "Adding command task 'generateCandidateSV" log/bcbio-nextgen-debug.log  | wc -l
256
```

Out of which 51 are finished or being written in my case:
```
find ./workspace/svHyGen/ -name candidate*vcf | sort | wc -l
51
```

I do wonder how these 256 split regions are calculated. Since the called SV's are probably limited to the split regions, i.e. cant span 2 of these split regions.

**Comment by NeillGibson** [comment]
The speed issue is that bcbio is not running 6 times a 10 cpu job but only 1 time a 10 cpu job for the generateCandidateSV jobs. 

So 50 cpu are idle.  

If possible and useful it would be nice if more cpu could be used for Manta.
By either running:
- 6 times a 10 cpu job
- 1 times a 60 cpu job

I am not sure the first of these options is (currently) possible in bcbio?

Otherwise I can set Manta jobs to 60 cpu in `galaxy/bcbio_system.yaml` but that would mean I need to run on a different sun grid engine queue. 

Is it the intended behavior that Manta only uses 10 cpu out of 60 for generateCandidateSV?  This would be 16 with the default job size in `galaxy/bcbio_system.yaml` 
If so would it be possible to switch that to 6 * 10 cpu jobs. (or 6 *16 with default job size in `galaxy/bcbio_system.yaml` )

Or would I be better of creating 60 cpu jobs for Manta in `galaxy/bcbio_system.yaml` ?
Or is Manta typically I/O limited or memory limited and does adding more CPU not increase the performance. I can also ask this in a issue at Manta of course. 

Thank you.

**Comment by chapmanb** [comment]
Neill;
Thanks for reporting back. I'm not too sure about the internals of how manta parallelizes the workflow, that all happens internally and I haven't dug into it in depth.

On the practical issue, if you're running bcbio with 60 total cores on SGE it should be giving you multiple engines to run with. I'm not exactly sure why it isn't doing that. Could you post the log lines around `Resource requests` for this job?
```
[2017-01-03T16:09Z] Resource requests: bcbio_variation, cnvkit, fastqc, gatk, gemini, lumpy, qsignature, sambamba, samtools, seq2c, snpeff; memory: 1.00, 1.00, 3.00, 1.00, 1.00, 1.00, 0.77, 1.00, 6.00; cores: 1, 4, 4, 1, 4, 4, 4, 4, 4, 4, 1
[2017-01-03T16:09Z] Configuring 1 jobs to run, using 1 cores each with 6.00g of memory reserved for each job
```
that could help us determine what bcbio sees. Practically, I have a fix in the latest development to better allocate memory for snpEff based on core usage, so you could remove or lower snpEff per core memory requirements:

https://github.com/chapmanb/bcbio-nextgen/commit/d7f28a2e168aa236f029a4e46524cabee23d725c

That sometimes drives less core usage for other tools as bcbio scales to fit memory with cores. 

Thanks for the help debugging this.

**Comment by NeillGibson** [comment]
Hi Brad, 

I have these 2 lines about the resources being requested:

```
[2016-12-30T20:21Z] gridmaster: Resource requests: bcbio_variation, fastqc, gatk, gemini, manta, qsignature, sambamba, samtools; memory: 3.00, 3.00, 3.50, 3.00, 3.00, 3.00, 3.00, 3.00; cores: 10, 10, 1, 10, 10, 10, 10, 10
[2016-12-30T20:21Z] gridmaster: Configuring 6 jobs to run, using 10 cores each with 35.1g of memory reserved for each job
```

Then I have these lines about Manta pyflow starting up and the resources it has. 
This also mentions that Manta is running in local mode, i.e. it's not trying itself to submit multiple jobs to a cluster.
```
[WorkflowRunner] Initiating pyFlow run
[WorkflowRunner] pyFlowClientWorkflowClass: MantaWorkflow
[WorkflowRunner] [RunParameters] mode: local
[WorkflowRunner] [RunParameters] nCores: 10
[WorkflowRunner] [RunParameters] memMb: 48258
```

The last 2 lines from `bcbio-nextgen-commands.log` are 
```
configManta.py --bam (for every bam file)   --referenceFasta= (pointing to my fasta)   --runDir= (the manta run dir)
[2016-12-30T20:23Z] node19: /bin/python /Project/Project123/work/bcbiotx/tmpVkFa9E/manta/runWorkflow.py -m local -j 10
```

So somehow my bcbio install  (version 1.0.1a0) is running Manta a single "local" job submitted to my cluster. 

Thank you for your support on this issue.

**Comment by chapmanb** [comment]
Neill;
Thanks for all the details, it looks like bcbio is doing the right thing here. It starts up 6 runners that each have 10 cores, so can run up to 6 Manta processes simultaneously. It runs each locally, as you noticed, which is the expected behavior. bcbio distributes the samples between machines, but doesn't try to use any native support in Manta for distributing further over the cluster.

Do you only have a single sample here, or have all the other samples in a processed finished and there is only one left? In that case, you're right that it'll only run one sample on 10 cores and then continue with processing. Could that be what you're seeing? If you need to push through a final sample, increasing cores to however many you have on single machines in your cluster will run manta local with more available cores and speed things up.

Hope this helps and explains what you're seeing.

**Comment by NeillGibson** [comment]
Hi Brad,

As far as I can tell the single 10 cpu Manta job is processing all 200 samples.  I don't see any evidence of Manta being run per sample.  I don't even know if Manta can be run in local mode over multiple samples. 

Reasons why I think the single Manta job is processing all 200 samples:
* All the created diploidSV.{number}.vcf are multi-sample and have genotypes for the 200 samples
* According the  `bcbio-nextgen-commands.log`  only 1 manta job is submitted. 

Last 3 lines from the  `bcbio-nextgen-commands.log`  :
```
bcbio-1.0.0/galaxy/../anaconda/bin/tabix -f -p bed /work/bcbiotx/tmpdNRo3W/Sample-coverage.callable-callableblocks-merged.bed.gz
configManta.py --bam (repeated for all 200 bam files)   --referenceFasta= (pointing to my fasta)   --runDir= (the manta run dir)
[2016-12-30T20:23Z] node19: /bin/python /Project/Project123/work/bcbiotx/tmpVkFa9E/manta/runWorkflow.py -m local -j 10
```

**Comment by chapmanb** [comment]
Neill;
Thanks for the details. Apologies, now I see what is happening. You're running all 200 samples as a single batch. You're right, that will only get processed by a single manta process. It can split up multiple jobs if you have many batches but needs to hand over each batch to manta to process.

In this case, it will be more efficient to increase the cores to 60 (or whatever you have on a single machine in your cluster) so that bcbio can run a single manta job with 60 total cores.

Sorry for missing earlier this was being run as a single batch and hope that helps speed up the analysis.

**Comment by NeillGibson** [comment]
Ah ok. Thank you for the information. Then I know that creating larger single Manta jobs is the way to go. 

Thank you.
