### ISSUE TITLE
bcbio server

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1742]
Hi Brad,

while rummaging through the code, I encountered a 'hidden' server module. Is this this code still functional and for what was it used? It would help us TREMENDOUSLY is we could start bcbio as a server to which we can send analysis requests. If this code has aged, which steps need to be taken to revive this?

Example: our plan is to (eventually) package everything into a docker image, which we would run on [Marathon](https://mesosphere.github.io/marathon/). It would be great to be able to send an HTTP request to the running container to start an analysis. Include full iRODS integration into that (down- and upload), and some JSON api compliance and we're golden.

Thanks! And thanks for keeping gems like that in your code!
M

**Comment by schelhorn** [comment]
Arvados is an alternative.

**Comment by matthdsm** [comment]
Yes, we know, but we've already deployed several services to Marathon, and would eventually like to be able to dynamically schedule bcbio runs on our Mesos cluster. As far as I know, Arvados does not support Mesos and we don't have the resources to run both side by side. Tempting as it may be from my point of view, currently Arvados isn't an option for us =(

**Comment by matthdsm** [comment]
The best move for us would be to be able to move completely to CWL and run it on Mesos using Toil, but all of our tries so far to do that have failed, sadly

**Comment by brainstorm** [comment]
@matthdsm Sorry for the issues you are having. What you mention regarding CWL/Toil is what we're moving towards, for instance, I'll be testing Toil/AWS/bcbio relatively soon.

Could you describe a bit more what have you tried with CWL/Mesos/Toil and how it failed? Did you file any of the issues you had to BD2kGenomics (https://github.com/BD2KGenomics/toil/issues)?

**Comment by matthdsm** [comment]
hi @brainstorm,

It's been a while since we first tried, and we didn't have the time to test very thoroughly. Our main issue started with the way the mesos plugin needs to be installed and the mesos version against which it was tested (very old). We put it on the back burner for future reference and focused on added functions to bcbio first

**Comment by chapmanb** [comment]
Matthias;
Thanks for starting this discussion. I'd recommend not using the internal server, which don't really do too much beyond dispatching local jobs. I'm not sure it provides the functionality you'd need and I don't think building Mesos/Marathon support into bcbio is the right direction to go.

CWL/Toil/Mesos support seems to be a better path to getting the support you'd need. Roman is taking a look at it now and I think working through that will provide a more useful long term solution for you. If there are blockers in terms of mesos plugins/versions it would be worth raising those with the Toil team and then make decisions about suitability.

Sorry to be pushing back on your good ideas, but my experience is that to support and maintain these type of complex external interactions the best plan is to collaborate with external communities doing this work rather than trying to create everything needed inside bcbio.

**Comment by matthdsm** [comment]
Hi Brad, 

I totally agree that CWL is the way to go, and collaboration is key. I took this conversation to Toil in BD2KGenomics/toil#1432.

I seems there's still some work to be done on the Toil side. I'll close this issue and take this further with the people there.

M
