### ISSUE TITLE
Getting data from external source

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1747]
Hi Brad,

I know you've mentioned in the past that you'd like bcbio to move away from the all in one model, but I'd like to expand the iRODS module to be able to get files too.

I know there was support for getting data from AWS in the past, but that code was removed. Would you be completely opposed to adding in download option? And more importantly, would you be willing to get me some info on how to do this?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
I don't have much practical experience with iRODS so I'm not 100% sure this advice is on target, but if you want to treat it as an S3-like objectstore, we do have a standardized interface to plug it in:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/distributed/objectstore.py

You'd subclass `StorageManager` and implement the required functions for querying/downloading from iRODs. Then if you specified filenames with something like `irods://path/to/file.txt` bcbio would be able to grab and download the files locally for processing. This is how the S3 download currently works.

Hope this helps for providing some direction to support this.

**Comment by matthdsm** [comment]
Hi Brad, 

I think iRODS can be handled more as an external filesystem, than as an objectstore. I'm not aware of any options to reach iRODS by URL as you suggested (although that would be an ideal way of working with the data). The iRODS cli has a set of unix like commands prefixed with `i`  (eg. `mkdir => imkdir`) to control files in the repository. I you could point me in the right direction to how this is handled locally, perhaps I can cook something up that uses the iCommands.

Thanks!
M

**Comment by chapmanb** [comment]
Matthias;
Is your desired approach to run the entire analysis on an iRODS filesystem, or to copy inputs from iRODS, run on some kind of temporary scratch filesystem, and then copy back into iRODS on upload?

If you want to run the entire analysis on an iRODS filesystem you'll need some sort of FUSE mount to make, since bcbio and all of the tools it calls assume a standard filesystem. There is no abstraction point for subbing in new commands for mkdir, for instance.

If you want to copy files to a non-iRODS filesystem, then this is the approach I described above. There is no need to access via URLs, you just need to implement the functions in `StorageManager` to copy a file from iRODS into the local directory. That can be via a command line program or whatever you want, all bcbio cares it that you return a copy to a local file it can process on.

Hope this helps

**Comment by matthdsm** [comment]
Hi Brad!

Thanks, that's just the info I needed! I'll get to it right away.

M

**Comment by matthdsm** [comment]
related PR #1758
