### ISSUE TITLE
checking file format of input files

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1760]
Hi Brad,

Just a quick question. I noticed that when we start a new run, the compressed fastq files we use as input are decompressed and then recompressed in bgzip format. This takes about 20 min per file.

However, the input files we use are already in bgzip format. Do you suppose it would be possible to check the compression format before recompressing the files? This would save a lot of time when a lot of samples need to be processed.

I think this is something a lot of users will benefit from, since bcl2fastq by illumina outputs bgzf by default.

Thanks
M

**Comment by schelhorn** [comment]
Bcbio should already do that; at least there is logic that is supposed to check the format.

**Comment by matthdsm** [comment]
Right, just went through the source code quickly. Turns out re-bgzipping everything is default because of some issue with grabix [here](
https://github.com/chapmanb/bcbio-nextgen/blob/c21d0e86bd1ac2347f64545f154c7bc152a90684/bcbio/ngsalign/alignprep.py#L548).

I'll see if I can re-evaluate this approach and perhaps we can save some time.

**Comment by matthdsm** [comment]
Seems this issue was already metioned in arq5x/grabix#17, but is still without a fix. I suppose we'll have to wait this one out then. Closing!
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for bumping this. I had been working on this on the side and have a reproducible test case so finalized that and added it to the grabix issue you identified. It would be great to have this fixed as we do potentially waste a lot of time here since we don't have a way to reliably detect what is correctly bgzipped so need to re-prep everything. I'll re-open this to track progress, thanks again for pushing the issue.

**Comment by chapmanb** [comment]
The latest development version of bcbio now re-instates this checking to coincide with a fixed grabix tool that handles Illumina bgzip inputs. Please let us know if you run into any issues at all.
