### ISSUE TITLE
Little to no parallelisation during goleft depth step

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1765]
Hi Brad,

I'm running a standard variant pipeline on 48 exomes, using stable v1.0.0 and I'm noticing a huge slowdown during the goleft depth step. The pipeline has been stuck on this step, with no parallelisation whatsoever. It seems bcbio is traversing over each file, one by one, using just one core, instead of the assigned 14.

Any idea what could be causing this? (no idea if there was a fix in latest release, but while the pipeline is running, I can't do an upgrade)

Thanks
M

Update:
The pipeline started coverage analysis on 01/13, still running as we speak.

**Comment by chapmanb** [comment]
Matthias;
Sorry about the issue, I'm not sure what is going on here. Are you re-running an analysis in a previous directory so it's not parallelizing? If so, removing `checkpoints_parallel/*.done` should let bcbio know you want to run in parallel again and avoid only allocating a single core for this step.

If not, we'd need to see some logging output to have a better idea of how bcbio is assigning cores and what might be happening wrong here. It would also be great to update bcbio when you have an opportunity to try and catch any fixes that have been put in place since the 1.0.0 release.

Hope this helps.

**Comment by matthdsm** [comment]
Hi Brad, 
Thanks, removing the checkpoints fixed the issue for me. Would it be possible to do this automatically when restarting an analysis?

Thanks
M

**Comment by matthdsm** [comment]
OK, I've no idea how that old code stuck around there, but I manually removed `alignprep.py` and replaced it with the one in the repo, and now everything seems to run smoothly. Perhaps there's been some kind of issue with the the installer/egg/conda/whatever.
I'm doing a fresh install locally, and will check if this also contains the old code.

M

**Comment by chapmanb** [comment]
Matthias;
I've been thinking about your initial issue here, running multiple cores in a previous work directory, and decided it's sufficiently confusing to change the behavior. Now for local multicore runs it will always use the specified cores regardless of if a job was run before. For IPython runs, it still uses checkpoints as these are helpful in avoiding spinning up an extra cluster just to check that everything finished. However, there is less benefit for local runs and the behavior has confused several people in the past. Hopefully the new settings make more sense for usage going forward.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for the fix, I'm sure this will help a lot of people out (me included)!

M
