### ISSUE TITLE
VEP still needs some fixes

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1766]
Hi Brad,

I've opened this issue because I've found some things that still bother me when using VEP. I'll try to fix most in an upcoming PR, but I'd like some comments from you/anyone interested. Feel free to strike through anything you're opposed to

- [x] add `dbscSNV` to the plugins used by default. Since `dbscsnv`has been added as datatarget, we can assume the user wants the annotation if it has been downloaded. Same principle as `dbnsfp`.
- [ ] the genesplicer plugin isn't included, even though the executable is installed and the option is included in the list of activated plugins.
- [x] ~~speaking of plugins. I feel we should move the plugin selection away from `bcbio_system.yaml` and into the analysis config. Does this config support nested options?~~
- [x] ~~there should also be an option to disable default options~~
- [x] ~~there should be a function that lists all arguments vep uses and removes the duplicates. it should perhaps also filter out options that are set using different arguments (eg `effects_transcripts`)~~
- [ ] deprecate the use of the `--fields` flag, since all this does is format the CSQ tag, without any added benefit.

I'm hoping to hear your thoughts on this. I'd like to get all the kinks worked out so we can clinically validate everything by May.

Thanks!
M

**Comment by matthdsm** [comment]
Another question. Is there a reason arguments that contain a whitespace are added to the arguments list with 2 separate entries? Or is this just code styling? Sticking the 2 together woud greatly simplify the process of cleaning up the arguments list.

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for continuing to work on the VEP integration. In general, I'd like to push back a bit on introducing a ton of configuration knobs for VEP. We try to avoid this approach in bcbio and focus on having a default approach that works for most cases with minimal tweaking where needed.

Is there any downside to running all of the plugins as long as the data is installed? If not, we should just pile everything on and let folks sort out what they need in downstream analysis. The temporary configuration in bcbio_system.yaml was more to test and develop this but it would be great to settle on more of a standard approach to take here so other people don't need to push all these buttons to get things to work.

If we have a add everything approach this changes a lot of your needs since we don't need to have functions to micromanage argument parsing and should make the code simpler. Do you think this would work? Thanks again for the discussion.

**Comment by matthdsm** [comment]
Hi Brad, 
I surely don't mind adding all options, especially for VEP itself. We could simplify the code by leaving out the expansive list of annotation arguments and just adding `--all`, which amounts to just a bit more fields than we currently have. This argument expands to a fixed set and does not vary between versions of VEP. This also doesn't affect runtime very much.

For the plugins however, I might see another scenario. I don't mind having them all running all the time, because that's just what we need, but other users might have little use of the info from maxentscan and genesplicer, and these slow VEP down significanly. So I would keep an option available to disable some plugins, in whichever form you like. If we keep it in the bcbio_system.yaml, users can define their own defaults, based on their use case. That would work for me. 
As for the dbNSFP fields, all these do is increase the size of the resulting vcf, so I'd also go with an "add all" approach. I would, however, leave out the population statistics from dbNSFP, since these can be dated in comprarison with the ones from VEP.

I'll work on the changes and create a PR, then we can discuss this further.

M

**Comment by matthdsm** [comment]
hi @chapmanb 

I've identified the issue with the genesplicer plugin. It seems the genesplicer training dir isn't included in the `genome_resources` array. I'm not really sure why this is, but this is the thing stopping the plugin from working. Could you point me in the right direction?

Thanks
M

**Comment by chapmanb** [comment]
Followed up on this in #1771, so closing this issue to avoid duplicate conversations.
