### ISSUE TITLE
multiqc report stats

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio-nextgen#1773]
Hi,

Can you please explain the follwing the qc stats in the multiqc report

Error rate (from CIGAR)
% Failed 
M Seqs from FastQC ...

**Comment by chapmanb** [comment]
Diya;
Thanks for the questions. The best way to investigate MultiQC metrics and their origin is to click on 'Configure Columns` in the `General Statistics` report. This will tell you what tool the metric comes from and provide a description. For your examples:

- Error rate (from CIGAR) -- this is from samtools stats and reports the errors found (from CIGAR strings) versus total bases.
- % Failed -- The percentage of failed modules in the FastQC report.
- M Seqs from FastQC -- Total sequences (millions) in the FastQC report. We downsample for FastQC to avoid long runtimes so this will not necessarily be accurate

If you update to the latest development version of bcbio these should all be hidden since they are not especially helpful top level metrics. Hope this helps.
