### ISSUE TITLE
bcbio 1.0.1 release can hang on grabix index due to testing code in tarball

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1779]
Hi Brad,

Sorry for the very ominous title, but I needed to get your attention. Apparently, some wrong code snuck into the python egg that was uploaded to PyPi. When you download the tar.gz from PyPi, the code in `bcbio/ngsalign/alignprep.py` does NOT compare to the code on GitHub. This causes all upgrades and clean installs of tagged versions to have faulty code.

Thanks for fix this ASAP.
M

**Comment by chapmanb** [comment]
Matthias -- thanks much for the report. This is due to testing we were doing around release time for avoiding bgzipping but as is it can cause hangs with grabix indexing if a bgzip input is supplied from Illumina. I've submitted a patch to the conda package which should resolve this and will report back and close when the bioconda build process finishes.

I also adjusted the title to be reflective of the issue and less sensationalistic. You have my attention when you submit reports so there is no need to try to escalate.

Thanks again for identifying this.

**Comment by chapmanb** [comment]
Matthias -- thanks again for the heads up. If you update to the latest stable (or development) versions of bcbio you should now get patched code without any potential bgzip/grabix issues. Thank you again for identifying this and let us know if you run into any other issues.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for fixing this so quickly and sorry for the competely overblown title. The issue kinda broke our production deployment, so I wanted to stress the urgency. Wont do it again!

Sorry again and thanks
M
