### ISSUE TITLE
How to accumulate QC files over multiple bcbio runs?

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1808]
Hi Brad, 

We want to accumulate the QC files of the increasing cohorts of samples that we sequence. 

We re-variant call all samples when our cohorts expands (we get new samples)  to get a square genotype table over all samples.  
This leads to fastqc and samtools stats being run for samples for which we already have fastq and samtools stats files. See https://github.com/chapmanb/bcbio-nextgen/issues/1807

When a (re)variant calling is finished we would like to copy the samtools and fastq zip files to another directory were we accumulate them so we later can generate on-demand (aggregated) reports on those files with multi-qc or other tools. 

The only way we current see to do this is to do a find exec on the stats files in the bcbio final directory to copy them to the accumulation directory. E.g.
```
find /bcbio_run_123/final/ -name *zip -exec cp {} /accumulatated_QC_files/fastq \; 
find /bcbio_run_123/final/ -name *txt -exec cp {} /accumulatated_QC_files/samtools \; 
```
This would be easier if the samtools and fastq file names include not only the sample name but also `samtools` and  `fastq` in the name. These find execs currently select not just the intended QC files but also other files. 

Another option would be that bcbio outputs a list of QC files per sample. I am not sure how easy / difficult it would be to implement that but it sure would be useful for accumulating the QC files over multiple bcbio analysis runs. 

Thank you. 

Neill

**Comment by chapmanb** [comment]
Neill;
Thanks for all this discussion, definitely re-running/combining from multiple projects is not a strong point of bcbio and happy to try and improve this.

The simplest way to do this right now is to save the sample qc directories from `work/qc/sample-name`. These are equivalent to the directories in `final/sample-name/qc` but named in an easier way for dropping into a new run. Putting them into `work/qc` before running will skip re-calculating them and include them in the final MultiQC report.

Unfortunately we don't have much flexibility on file naming in many cases since MultiQC needs to use the filename to determine the sample. So if we call a file `samplename-samtools.txt` it will call is `samplename-samtools` instead of `samplename`. This is true for any files where the same name is not embedded in the output report somewhere. So keeping the directory structure is the easiest way to approach it.

There is also #1708 which aims to something similar and make it easier to run a consolidated MultiQC following the initial run. This would be helpful in parallel to explicitly saving the work directories in re-runs, so you can re-combine with MultiQC without a re-run.

Does saving/copying the QC directories work for what you'd need?

**Comment by NeillGibson** [comment]
Thank you Brad for the quick answer. I think we will try r-syncing the bcbio work QC directory to and from our QC accumulate directory per species and reference genome.

**Comment by lpantano** [comment]
Hi @NeillGibson 

I will close this guessing you got it working. We changed a lot the QC in the last months so probably that helped as well. Let us know if you find more issues.

Thanks!
