### ISSUE TITLE
ATAC-Seq short fragment bam and peak call

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1820]
Hi Brad,
I have a question I have seen that you have add an ATAC option to the chip-seq pipeline. I think this is really useful. I was wondering if it would not make sense to make the peak calling only on short fragment (the one that do not span the nucleosome). I think would be nice if it would be possible to configure a parameter (maybe via YAML configuration) of the maximum length of the fragment, and have a bam of only short (open region) ATAC fragment and do the macs call on this. 

What do you think?

Thanks 

Alessandro

**Comment by lpantano** [comment]
Hi,

I implemented that because we had a couple of project with that, and I did a simple implementation according ATAC-seq first developers of the protocol.

I am not in the position to decide that, but if you are working on that, and you can try to compare if that makes sense or not, I can certainly add someway an option inside resources for macs2 when running ATAC-seq to keep only short fragments in the BAM files. 

Do you have any insight in what should be the default value? something that is reasonable? 

thanks!

**Comment by apastore** [comment]
Thanks Lorena!

the nucleosome length its 180bp, so read pair that are bigger than (end to end) this are spanning multiple nucleosome. I usually set a insert size go 50 bp as a cutoff. 

I also would be nice to output normalised bw file. there is a package call deeptols that is really useful for this. Would you like to consider it?

Thanks a lot
Alessandro

**Comment by lpantano** [comment]
sounds good. I will work on adding that. 

About the deeptools, i know about it. I need to look if is already in bioconda and if you want to suggest some specific commands, I can do a TODO list. That probably will take more time since we would need some more chipseq project to work on that.

thanks!

**Comment by apastore** [comment]
Hi Lorena, Thanks!
deeptools is in bioconda. 

I use deeptools in this way for chip seq (SE and PE) 

Single End Bam
			bamCoverage -b bam/${chip}-ready.bam -o bw/${chip}.bw \
			--binSize 20 --normalizeTo1x ${genomesize} \
			--smoothLength 30 \
			--ignoreForNormalization chrX chrY
			--extendReads 250 \
			--centerReads

Pair End Bam
		bamCoverage -b bam/${chip}-ready.bam -o bw/${chip}.bw \
		--binSize 20 --normalizeTo1x ${genomesize} \
		--smoothLength 30 \
		--ignoreForNormalization chrX chrY \
		--extendReads  \
		--centerReads

Thanks!
Alessandro

**Comment by chapmanb** [comment]
Alessandro and Lorena;
Thanks for looking at this. How is the performance and resource usage of deeptools for whole genome inputs? We looked at this a while ago and ran into extremely high memory usage for bigwig creation. We had automated bigwig generation and had to remove it as a result of this. This used UCSC's `wigToBigWig` but I'm not sure if there are fundamental challenges with bigwig writing that require holding a lot in memory. It might be worth doing some manual testing before trying to integrate.

**Comment by apastore** [comment]
Thanks Brad!
I normally allocate 10G for two process with  Chip-seq, ATAC-seq and RNA-seq.

**Comment by chapmanb** [comment]
Alessandro;
Thanks much. What types/sizes of files does your 10Gb limit work for? Have you investigated with deeper depths or whole genome files? It would be helpful to have a range on memory bounds for different file types. Thanks again.

**Comment by apastore** [comment]
Hi Brad, 
My bam are around 5 Gb for Chip-seq and Atac-seq, for RNA-seq we usually aim for 50M to 100M reads (it depend on the application).
I use deeptools for epigenetic project, for bw generation and for the Count Matrix.
I have no experience at all on Whole Genome Data with deeptools, so I can not comment on this. 

Thanks 
Alessandro

**Comment by lpantano** [comment]
I'll follow up here: https://github.com/chapmanb/bcbio-nextgen/issues/1831
