### ISSUE TITLE
Option to source custom environment script in batch job

### ISSUE THREAD

**Issue by andreyto** [chapmanb/bcbio-nextgen#1825]
On my Torque cluster, for whatever reason, `~/.bashrc` is always sourced when the batch job starts. In my `~/.bashrc`, I set up the PATH to use a Conda install that is different from the one inside BCBio. It would be inconvenient for me to remove the other Conda from `~/.bashrc`. As a result, BCBio `ipython` jobs get the PATH that starts with the other Conda, even though `-V` switch is used with `qsub`.

Would you be open to providing an extra option `--job-env` to `bcbio_nextgen.py` such as:
```
bcbio_nextgen.py bcbio_sample.yaml -t ipython -n 12 -s torque -q queue --job-env job_env.sh
```
that would result in this at (https://github.com/roryk/ipython-cluster-helper/blob/master/cluster_helper/cluster.py#L690):
```
#PBS -V
#PBS -N {tag}-e
{resources}
cd $PBS_O_WORKDIR
source {job_env}
{cmd}
```

That would allow working around various peculiar setups on the clusters, and also address issues previously raised about the compatibility with LMOD ("modules") scripts, which rely heavily on manipulating the LD_LIBRARY_PATH. Because LD_LIBRARY_PATH is squashed by the kernel on remote execution, the `-V` option to `qsub` does not propagate that variable, and `lmod` often has to be issued inside each batch job.

I can submit a pull request.

**Comment by chapmanb** [comment]
Andrey;
Thanks for the suggestion. On one side, I feel like this is something the cluster setup should inherit from the parent environment rather than needing a separate setup script. There are a couple of edge cases like `LD_LIBRARY_PATH` that we work around but otherwise this is the cleanest and simplest way to describe the environment bcbio has in the controller and worker nodes. I'm not totally opposed to adding a workaround but also am worried about adding in a potential way to cause hard to debug issues in engine runs if sourced bash files change the path or otherwise disrupt the working bcbio setup in the parent environment.

Is it possible to first debug on your side to determine why your environment gets reset on job submissions? If you're totally stuck happy to talk more about a PR to add this workaround in.

**Comment by andreyto** [comment]
Brad,

The way the environment gets reset is like this.

In your code for cluster_helper/cluster.py, you have:

```
"""#!/bin/sh
#PBS -V
#PBS -N {tag}-e
{resources}
cd $PBS_O_WORKDIR
{cmd}
"""
```

and this gets submitted with:

```
        submit_cmd = "qsub < %s" % self.batch_file_name
        for i in range(n):
            output = subprocess.check_output("qsub < %s" % self.batch_file_name,
                                             shell=True)
```

Not quite clear why submit_cmd is defined but then a separate string literal is used instead. Regardless, the key effects are:

The PBS script shebang tells it to be executed with `/bin/sh`, but the job is not submitted with `qsub -S /bin/sh`. Instead, it is submitted as simply `qsub < script`.

When I run a simple `printenv` test job with options like that (outside of BCBio) on my Torque cluster, I see that:

- `SHELL=/bin/bash`
- `~/.bash_profile` gets sourced, and the PATH gets redefined from the profile on top of the original values propagated by the `-V` switch. Torque starts the shell as a login shell. I think this is Torque's default behavior. 

If I submit my test job instead with `qsub -S /bin/sh`, then:
- `SHELL=/bin/sh`
- `~/.bash_profile` does not get sourced (expected behavior for `sh`)

So, the shebang in the script does not have any effect. I do not know if this is the expected behavior of Torque. This brings me to my general argument:

I have worked on a number of clusters, including those on the XSEDE. There are some peculiarities in how each batch system is configured. Usually it is close to impossible to get the admins change the config. Especially with the `module` system used widely on XSEDE and other big clusters, some variables they define just do not get through with `-V`. This is why I like to have an optional escape hatch where I can control the environment at the destination if I have to. Not having it is actually more like to lead to hard to catch problems when the wrong Conda install is used by the jobs.

If I understand it correctly, Galaxy provides the means like that with the `<env>` element in (https://wiki.galaxyproject.org/Admin/Config/Jobs).

There are obviously workarounds other than changing your code. Right now, for example, I replaced the `/.../bcbio/anaconda/bin/python` with a script bellow, which results in the IPython engine started with the right environment. But this is a hack.
Thanks,
Andrey

```
#!/bin/bash
#move the original python binary (not a symlink) to python_exe; then
#replace python symlink with this file.
#this will make sure that the right Conda environment is used
#when ipython agents are started by ipython parallel cluster
#even if another Conda is default in the PATH in .bash_profile
this_dir=$(cd $(dirname "$0"); pwd)
export PATH="$this_dir:$PATH"
exec "$this_dir/python_exe" "$@"
```

**Comment by chapmanb** [comment]
Andrey;
Thanks for the discussion, this helps a lot to clarify what is going on. It seems like the issue might be with our PBSPro implementation so we don't end up clearing the parent environment via the subprocess. If possible, it'd be nice to fix that so it "just works" which will help other PBSPro users as well.

Before we dig into that, though, I'm not totally clear if you're using PBSPro or Torque. If you're using `-s torque` as in the initial post, it should use the TorqueController/Enginer: 

https://github.com/roryk/ipython-cluster-helper/blob/master/cluster_helper/cluster.py#L557

Which doesn't use the separate subprocess call you mention above or the cluster scripts you mention. Is it possible you're specifying pbspro instead of torque and just switching over would fix it?

If we do need to debug PBSPro, I'll have to bring @roryk into the mix as I know he worked on that one. PBSPro has been one of our trickier integration as we don't actively have access to that cluster scheduler so have had to do a lot of development and testing via GitHub issues which is always more challenging. Rory, does PBSPro lack array submission support, so we have to loop through and manually submit the jobs?

Thanks again for the discussion and helping try to make the bcbio integration better.

**Comment by andreyto** [comment]
Brad,

You are right - I was looking at the wrong code. I did not realize that there was a separate class for the Torque. I just assumed that Torque and PBS were sufficiently similar to be handled by the same code. I have Torque on my cluster, and I have been using `-s torque` with BCBio. 

However, it appears that as far as this issue is concerned, the Torque code ends up with the same thing as PBSPro code. Torque class inserts `#!/bin/sh` into the job script (https://github.com/roryk/ipython-cluster-helper/blob/master/cluster_helper/cluster.py#L639), but it does not use `-S /bin/sh` option to `qsub` anywhere in Torque-related code as far as I can tell (https://github.com/roryk/ipython-cluster-helper/blob/master/cluster_helper/cluster.py#L560). BTW, the code does use `-S /bin/sh` for the SGE (https://github.com/roryk/ipython-cluster-helper/blob/master/cluster_helper/cluster.py#L252).

So, the fix to my current problem should be as simple as adding `-S /bin/sh` to the Torque qsub, either as a command line switch or as a special comment in the job script. This will turn off sourcing of the home directory profiles and let the environment variables passed with `-V` script keep their values.

This will not solve the problems for people who rely on `LD*` variables created by modules system.

**Comment by chapmanb** [comment]
Andrey;
Thanks so much for the detailed investigation. I pushed an updated ipython-cluster-helper version that will use /bin/sh and pass along `LD_*` variables in Torque/PBSPro. If you update with:
```
bcbio_conda install -c bioconda ipython-cluster-helper
```
(or upgrade all of bcbio with `bcbio_nextgen.py upgrade -u development`) it will get the latest version that I hope will do the right thing now. Thanks again for all the help debugging and let us know if you run into any other issues.

**Comment by andreyto** [comment]
Brad,
Thanks a lot for the fix!
