### ISSUE TITLE
Installation: support (if possible) resuming transfers for dbNSFP

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1835]
The size of dbNSFP is unbelievably large, and not all institutions have perfect network connections (for one, mine doesn't). I've been trying to update this on one of our clusters for about 5 days, and every time the connection fails I have to resume from the start, because the ggd script wipes and starts from scratch.

This should - if possible - be reworked to use existing, partially downloaded files.

**Comment by chapmanb** [comment]
Luca;
Thanks for the suggestion. We don't clear the download but didn't have the curl flag set to continue the download. I added that to the recipe which I hope will allow you to restart in the case of network failures. This is my best attempt to fix and I'm not 100% sure it will work since the dbNSFP download is complicated and requires cookie authentication via Google Drive, so it might not be possible at all to continue interrupted downloads. Fingers crossed it will work for you.
