### ISSUE TITLE
Ensembl HGVS vs Refseq HGVS in germline variant calling pipeline

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1847]
Hello!

Thank you for the excellent pipeline!

VEP in variant calling pipeline reports HGVS annotations along the ensembl transcript, i.e.:
ENST00000357730.2:c.1392+1G>A for 
ch1 44466835 C T

It is correct, but some people used to RefSeq annotations, i.e.:
c.1347+1G>A NM_001261380.1

It is easy to force VEP to produce RefSeq annotations:
1. unpack Refseq cache:
ftp://ftp.ensembl.org/pub/current_variation/VEP/homo_sapiens_refseq_vep_87_GRCh37.tar.gz
to 
bcbio/genomes/Hsapiens/GRCh37/vep
2. run VEP with `--species homo_sapiens_refseq` parameter.

Is it possible to add this functionality to the variant calling pipeline, just to have an option hgvs:ensembl/refseq?

Many thanks!
Sergey

**Comment by chapmanb** [comment]
Sergey;
bcbio has been moving to consistently use the Ensembl/GENCODE representations rather than RefSeq. GENCODE is generally considered more comprehensive so handles a wider variety of cases:

https://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-16-S8-S2

and we offer the `effects_transcripts: canonical` flag to limit these to a smaller RefSeq like set:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#variant-annotation

Would this work for your use case?

**Comment by naumenko-sa** [comment]
Hi Brad, 

thanks for the article, it is a good reason! 

Personally I'm also prefer Ensembl annotations, and I agree that it is the better way. 
And I'm using ensembl transcript ID's to get many additional annotations, absent in VEP/GEMINI - Exac scores, OMIM, Orphanet, etc. I need ENSEMBL anyway.

Sometimes clinicians are more conservative, they used to RefSeq coordinates and IDs :). 

Ok, I in the meanwhile I'll just use a script to calculate RefSeq coordinates for the report, and in the future I hope we will completely switch to Ensembl/GENCODE in the project!

Thank you for you time!

Sergey
