### ISSUE TITLE
Help wanted, adding defaults to vcfanno config

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1849]
Hi Brad,

I'm trying to add another built in vcfanno config (cfr. `vcfanno: [gemini,otherdefault,custom.conf]).
Could you give me some pointers where and how I should add this? I'd like to do some tests and see if it's something that worthy for production.

Thanks 
M

PS, congrats on the new release, I've been looking forward to it.

**Comment by chapmanb** [comment]
Matthias;
Thanks for offering to contribute additional configurations to bcbio. There are three things you need:

- A vcfanno configuration file that defines the annotation approaches for each genome you support. Examples are here: https://github.com/chapmanb/bcbio-nextgen/tree/master/config/vcfanno
- Add the vcfanno configuration file to the ggd-recipe used to install these for bcbio: https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/vcfanno.yaml
- ggd-recipes (https://github.com/chapmanb/cloudbiolinux/tree/master/ggd-recipes) for all data files used in the annotation.

The last is the one that takes the most work since we'd need to have bcbio installing these to make them available to your configuration script. We'd like these to be general purpose and configurable if large. Do you have an example of what you'd like to contribute? That would help with discussing specifics. Thanks again.

**Comment by matthdsm** [comment]
Hi Brad,
Thanks for the info. I'm looking into making dbNSFP and dbscSNV available for both vep and snpEff users.
Ideally, I'd remove dbNSFP/dbscSNV from the VEP plugins and add a config for vcfanno.
That way, users can annotate with everything from jpopgen using `vcfanno: [gemini,jpopgen]`.

We're using both resources quite intensively and already worked around some caveats etc, which VEP doesn't seem to handle. If you approve, I can submit a PR at cloudbiolinux with the config we're using.
A ggd recipe for the data itself is already available.

Cheers
M
