### ISSUE TITLE
Questions: Altair PBS and other

### ISSUE THREAD

**Issue by silvanopiazza** [chapmanb/bcbio-nextgen#1856]
Hi to all, 
I have some questions and not a issue. 
Please forgive me if this is not the right place/way to ask them. If this it is the case, I will do it in the correct way next time based upon your suggestions.
I am planning ti use BCBIO pipeline on the HPC cluster of my University, and one again please forgive my simple questions.
To keep thing easy to install and maintained my idea is to use the docker version of bcbio.
This is compatible within a cluster environment?
My HPC cluster uses the Altair PBS. Is this ok or  is that a problem? 
Is there some additional documentation about BCBIO setup/use in addition to readthedocs and papers?
Thanks to all
Silvano

**Comment by brainstorm** [comment]
Hello @silvanopiazza,

Thanks for reaching out to us!

In actual fact, [ipython-cluster-helper](https://github.com/roryk/ipython-cluster-helper/blob/33c9eb1fdeb5816c87a5c0b685291673ac685cad/cluster_helper/cluster.py#L726), the backend that runs cluster jobs does support PBS plus we are running preliminary jobs in a HPC cluster in Australia that has PBS too.

Perhaps you got confused because the official documentation does not mention it?:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#ipython-parallel

The official documentation above should be the reference, but feel free to ask if you find issues while setting it up.

**Comment by chapmanb** [comment]
Silvano and Roman;
Thanks for the questions and apologies about the documentation oversights. I pushed an update to mention the PBSPro support as well.

For cluster runs, we recommend using the standard installation:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

Most HPC environments are not set up to run Docker right now, so this is the better support and easier to maintain approach. Please let us know if you have other questions.
