### ISSUE TITLE
Normals missing in bcftools stats in paired settings

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1874]
It seems as if the multiqc `bcftools` stats generated for paired samples (with shared normals, in my case) do not include the normal samples - these are missing from the output. In contrast, the fastqc, general, bcbio, and samtools stats all include the normal samples. Could the normals be added to the `bcftools` stats as well?

**Comment by schelhorn** [comment]
Alright, after looking into this in more detail I learned that the `bcftools stats` command is of course running on the somatic-filtered VCFs and extracts the somatic tumor calls. Since the single-sample/unpaired calls are not stored in a separate VCF, no variant stats are available for normals in general. That is contrast to the other Samtools etc. stats that are of course ran on the BAM files. Is that about correct? Sorry for being so slow today.

**Comment by lpantano** [comment]
Hi,

sorry about that. at some point there was this code:


   if not vcf_file:
+        vcf_file = data['variants'][0].get("germline", None)

https://github.com/chapmanb/bcbio-nextgen/blob/69bb98ac8abb3ab68ab320410ef584df696124d3/bcbio/variation/coverage.py#L280

but with all the re-organization I think it got lost somehow. Brad, do you remember to migrate bcf stats code? Do you think this same code will fix this?

**Comment by chapmanb** [comment]
Sven-Eric and Lorena;
Sorry about the confusion here. We've moved germline calling to happen via separate variant callers rather than being extracted from the original tumor calls:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#somatic-w-germline-variants

This improves germline calling but is a different behavior than previously. If you add in germline calls, bcbio will split the normal sample after alignment and have variant calls for `your-input-germline` in the output tables.

I'd also like to enhance the MultiQC output to differentiate somatic germline calls explicitly, but hopefully in the short term this works to identify the outputs you're looking for. Please let us know if anything still seems off. Thanks much for the discussion.

**Comment by schelhorn** [comment]
Thanks, understood. Closing.
