### ISSUE TITLE
RFC: Benchmark cell-free DNA analysis on panels

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1880]
And another RFC for today: in bcbio we have all components for doing cfDNA/ctDNA variant calling on deep barcoded panels (using, for instance, UMI-guided concensus read generation plus vardict for variant calling). Is there a wider interest in implementing (or parameterizing the existing) variant calling workflow on public barcoded cfDNA read data and benchmark it?

**Comment by mjafin** [comment]
Hi Sven-Eric,
How would you determine what's a good result in such a benchmark? I don't think NA12878 or other existing reference standards (like Horizon's pseudo ctDNA standard) really capture the difficulties of ctDNA sequencing in the clinic. 

We've been sequencing panels (deep) and exomes (not so deep) for matched FFPE and plasma samples and noticed that a lot of the low AF-noise can be gotten rid of in panels by using more stringent settings in the consensus read forming method (fgbio). The same settings don't work for lower coverage panels like exomes as most data would get thrown out.

**Comment by schelhorn** [comment]
Well, we are doing somewhat-deep exomes on our own as well and generating 5kx clinical cfDNA analysis with another CRO. For the purpose of this benchmark, I'm hoping to get either public-use clinical cfDNA data from ENA that is matched with one or multiple tumor tissue biopsies, or heavily diluted mixture samples from artificial spike-ins. That doesn't get rid of the truth problem completely but allows at least for some comparisons. We have also tested five cfDNA CROs each with their proprietary library prep in a spike-in setting, but I'm not sure if we get the raw data including the barcodes since that again is the 'secret sauce' of the vendors. In a manner this secrecy of the vendors is also why I would like to do this in a more transparent manner using public code and data. We need some best practices in the field to be able to benchmark library preps and achieve reproducibility of the analyses.

**Comment by chapmanb** [comment]
Sven-Eric and Miika;
If we can identify useful benchmarks it would be great to validate and parameterize this within bcbio. As you mention, we can currently do this with bcbio pipelines but don't have a good handle on our sensitivity/specificity or a way to tune. Because there is often a focus on calling CNVs and other SVs in addition to small variants, I've been thinking of this as a harder subset of the heterogeneity problem so was hoping that some of the validations planned there will help with this. But having more validation test sets is always welcome and the more we can open this up the more we can hopefully improve it. Sven-Eric, if you can pull out truth sets we can share definitely happy to work with those.

**Comment by schelhorn** [comment]
Excellent, thank you. I will close this issue now and re-open once I have a suggestion for a validation set.

**Comment by audyavar** [comment]
Is the ctDNA pipeline implemented in bcbio? Is there a way to specify that the exomeseq data is from ctDNA to add increased sensitivity for false-positives?

**Comment by chapmanb** [comment]
We don't have a specific ctDNA pipeline in bcbio. For small variant calling we typically deeply sequence and call using VarDict with a low `min_allele_fraction` to try and capture low frequency events. Hopefully that's helpful for identifying events in your ctDNA samples.
