### ISSUE TITLE
Installer does not build or download hisat2 index (missing documentation on why?)

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1885]
I found this out the hard way when I tried to align against the hg38 genome: there's no index available nor one is built. 

I assume that it is because building a hisat2 index requires massive amounts of RAM if you include SNPs, but in that case it should be at least documented.

**Comment by chapmanb** [comment]
Luca;
Sorry about the issues. Did you specify to build a hisat2 index during install/upgrade:
```
bcbio_nextgen.py upgrade --data --aligners hisat2
```
and run into an error or another problem? Happy to try and debug more with details about what happened.

**Comment by lbeltrame** [comment]
I did that, and apparently it did not download anything. From what I see, if the `hisat2` folder is present, no index is downloaded, if not, it is downloaded.

**Comment by lbeltrame** [comment]
Spoke too soon:

```
Running GGD recipe: hg38 hisat2 12-07-2015



xz: /lib/x86_64-linux-gnu/liblzma.so.5: version `XZ_5.2' not found (required by xz)
tar: Child returned status 1
tar: Error is not recoverable: exiting now```

**Comment by chapmanb** [comment]
Luca;
Thanks for digging further and for identifying the underlying issue. We were assuming you had a functional system wide `xz` and in older install approaches we'd fail with this error and then skip on the next build due to having the directory present. hg38 uses the better approach of ggd-recipes so catches the error and will fail to continue. I pushed a fix to install xz into the exposed bcbio tools which should hopefully use that working version and avoid the problem. An update with `--tools` should hopefully include that in the right place and work cleanly. Thanks again for the help debugging.
