### ISSUE TITLE
Missing cnvkit calls in final/

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#1917]
Hi,

I was running cnvkit in parallel mode. I think cnvkit finished cleanly - .cns files have been generated in work/structural/(sample)/cnvkit/raw.
However none of the cnvkit files copied over to the final/ folder. I can't find an error message.
Could you look into it pls? Thanks!

**Comment by chapmanb** [comment]
Sorry about the issue, is this using the 1.0.2 release or latest development version? I believe there was a bug in the last release which was fixed in #1858 if you can update to the latest development:
```
bcbio_nextgen.py upgrade -u development
```
We're hoping to have a new release soon with this fix. Happy to dig more if this doesn't explain it.
