### ISSUE TITLE
How to configure YAML to run CNVKit as input for Lumpy.

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1934]
Hi am trying to run CNVKit and Lumpy together to call structural variants.  I would like to use the CNVKit copy number calls prior evidence input for Lumpy. 

I am using bcbio 1.0.3a and this is my YAML:

```
# Template for whole genome Illumina variant calling with FreeBayes
# This is a GATK-free pipeline without post-alignment BAM pre-processing
# (recalibration and realignment)
---
details:
  - analysis: variant2
    genome_build: my_genome
    description:
    # to do multi-sample variant calling, assign samples the same metadata / batch
    metadata:
      batch: Project123_CNVKit_Lumpy
    algorithm:
      aligner: false
      mark_duplicates: false
      recalibrate: false
      realign: false
      svcaller: cnvkit,lumpy
      ploidy:
          default: 2
      nomap_split_targets: 3000
      effects: false
      tools_off:
      - gemini
      # for targetted projects, set the region
      # variant_regions: /path/to/your.bed
```

Using this YAML bcbio skipped structural variant calling, not running cnvkit or lumpy.  I started the analysis from existing BAM files. 

```
[2017-05-15T22:41Z] multiprocessing: split_variants_by_sample
[2017-05-15T22:41Z] Timing: prepped BAM merging
[2017-05-15T22:41Z] Timing: validation
[2017-05-15T22:41Z] multiprocessing: compare_to_rm
[2017-05-15T22:41Z] Timing: ensemble calling
[2017-05-15T22:41Z] Timing: validation summary
[2017-05-15T22:41Z] Timing: structural variation precall
[2017-05-15T22:41Z] Timing: structural variation
[2017-05-15T22:41Z] Timing: structural variation
[2017-05-15T22:41Z] Timing: structural variation ensemble
[2017-05-15T22:41Z] Timing: structural variation validation
[2017-05-15T22:41Z] multiprocessing: validate_sv
[2017-05-15T22:41Z] Timing: heterogeneity
[2017-05-15T22:41Z] Timing: population database
[2017-05-15T22:41Z] Timing: quality control
```

Is there something wrong with the YAML. Should I have specified in another way to use both cnvkit and lumpy. 

There is no error or warning in the log about invalid entry for svcaller. 

Thank you.

**Comment by chapmanb** [comment]
Neill;
Thanks for the report. The underlying issue is that the `svcaller` specification should look like:
```
svcaller: [cnvkit, lumpy]
```
Supplying without the list brackets as `cnvkit,lumpy` gets interpreted as a single string so bcbio never gets the SV callers to run. We should have been raising an error to let you know that this doesn't get parsed right, and I pushed a fix to the latest development to do that.

You'd also need to add:
```
tools_on: [lumpy_usecnv]
```
http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#tweaking-defaults
to use CNVkit as input to Lumpy. This is no longer the default as it slowed down that didn't want this feature (since CNVkit and Lumpy can't run in parallel in this setup). Hope this gets things working correctly for you.

**Comment by NeillGibson** [comment]
Thank you for the information!
