### ISSUE TITLE
cutadapt trim first 10 base on second read 

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1971]
Hi Brad, I have one question is possible to trim the first 10 base of the second read in a varinat call run? I have set trim_reads: true and set the cutadapt option -U 10 in the resource section but I still not get the trimmed fastq.

do you have any suggestion ?
Thanks a lot 

- algorithm:
    aligner: bwa
    ensemble:
      numpass: 2
    mark_duplicates: true
    remove_lcr: true
    trim_reads: true
    variantcaller:
    - vardict
    - mutect2
    - freebayes
  analysis: variant2
  description: 2680-2
  files:
  - 2680-2_CTTGTAAT_1.fastq.gz
  - 2680-2_CTTGTAAT_2.fastq.gz
  genome_build: hg19
  metadata:
    batch: 2680-2
    phenotype: tumor
fc_date: '2017-06-06'
fc_name: FL
resources:
  cutadapt:
    options:
    - -U 10
    - -p

**Comment by chapmanb** [comment]
We're hoping to include trimming into variant calling prior to the next release, hopefully getting it finished over the next week. We've previously relied on bwa soft-clipping to remove adapters since it does a solid job but are seeing more cases where trimming upstream can be helpful and would like to incorporate this.

If you need it prior to being able to include in bcbio you could trim upstream and then feed into bcbio, which is the standard workaround right now. Thanks again for the discussion and encouraging us to support this.

**Comment by apastore** [comment]
Thanks a lot!
Alessandro

**Comment by chapmanb** [comment]
Alessandro;
Thanks again for the suggestion. This is now available in the latest development version of bcbio, including passing custom options to cutadapt:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#read-trimming

 Looking at your example above, you should remove the `-p` specification in your YAML but otherwise it should work as desired. Please let us know if you run into any problems using this and thanks again for the suggestion.

**Comment by chapmanb** [comment]
Alessandro;
If you're looking to do defined end trimming as part of variant calling, the latest development version now has a faster way to do this using `trim_ends`:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#read-trimming

So you'd supply:
```
trim_ends: [0, 0, 10, 0]
```
To trim from the 5' end of read 2. This is integrated with fastq preparation so much faster than cutadapt if you don't need adapter trimming. Hope this is useful.
