### ISSUE TITLE
Clinvar annotation in gemini.conf for hg19

### ISSUE THREAD

**Issue by alexbaras** [chapmanb/bcbio-nextgen#1974]
I started getting an error from vcfanno about 5-6 days ago (~ 6/8/2017) appended below

while at first i thought something was wrong with the path to clinvar_20160203.tidy.vcf.gz, it turns out that that file is not fact there but clinvar_20170130.tidy.vcf.gz is

after updating the annotation record for clinvar in gemini.conf in hg19, things started working again

note this issue persisted on a fresh install i did yesterday (6/10/2017)

i wanted to confirm i had fixed this correctly

Thanks!

-Alex

=============================================
vcfanno version 0.2.6 [built with go1.8]

see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:112: [Flatten] unable to open file: /usr/local/share/bcbio/gemini_data//usr/local/share/bcbio/gemini_data/clinvar_20160203.tidy.vcf.gz in /usr/local/share/bcbio/gemini_data
alex@ares:~/NGS/bcbio/work$ /usr/local/share/bcbio/anaconda/bin/vcfanno -p 12 -lua /usr/local/share/bcbio/genomes/Hsapiens/hg19/config/vcfanno/gemini.lua -base-path /usr/local/share/bcbio/gemini_data /usr/local/share/bcbio/genomes/Hsapiens/hg19/config/vcfanno/gemini.conf /home/alex/NGS/bcbio/work/gemini/15-1303-AS_5_LCP-ensemble-decompose.vcf.gz

**Comment by chapmanb** [comment]
Alex -- thanks much for the heads up on the issue and the fix. I pushed this to the vcfanno project and updated the bcbio install recipes so a `bcbio_nextgen.py upgrade --data` will ensure you have the right configuration. Thanks again.

**Comment by alexbaras** [comment]
no problem,

could you send me good example configuration file for tumor only somatic mutation calling the flags likely germline variants?

i was having trouble doing this on my own

thanks

-Alex

**Comment by chapmanb** [comment]
Alex;
Happy to help with setting up your configuration file, what issues are you running into? For tumor only you use the standard configuration (http://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#cancer-variant-calling) and only have a tumor sample (`metadata: tumor`). Filtering of potential germline variants present in 1000 genomes and ExAC happens automatically as long as you have GEMINI available for your installation (http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#customizing-data-installation). I could provide some more specific pointers if you can make the sample YAML file available you're having trouble with. Thanks much.

**Comment by chapmanb** [comment]
Alex;
Thanks for sending the files and configuration by e-mail. I'm following up here in case it's helpful to anyone else or if other people can provide suggestions. The relevant part of the configuration is:
```
    ensemble:
      format-filters: [DP < 50]
      numpass: 2
      use_filtered: true
```

> 1. am i looking at the right VCF? i think its the sample labeled folder and then the [sample-name]-ensemble.vcf.gz

Ah apologies, I didn't realize you were talking about the ensemble file. The actual filtering of germline variants happens at the individual caller level, not here. The information does get transferred along so you can use it for post-filtering at this point.

> 2. in my yaml i thought i was filtering for DP > 50; it doesn't seem so (yes i am allowing filt variants through to specifically see the filt flag in the vcf for those)

Sorry for the confusion, there are two ways of doing ensemble calling (http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#ensemble-variant-calling) and format-filters only applies to the older method. My recommendation is to provide filtering post-ensemble outside of bcbio with bcftools instead of trying to use the older approach.

> 3. on the same line, i thought the possible germline would have been marked too but they don't seem to be?

They get marked in the individual samples but because you specified `use_filtered: true` have the filters removed in ensemble. The information to filter is there in the `EPR` field. 

My best suggestion is to do your custom filtering as a post-processing step after bcbio finishes. Using bcftools you could filter as desired with:
```
bcftools filter -e 'DP < 50' 15-1303-AS_5_LCP-ensemble.vcf.gz -m + -s DepthFilter | bcftools filter -e "EPR[*] != 'pass'" -m + -s GermlineFilter -O z -o 15-1303-AS_5_LCP-ensemble-filtered.vcf.gz
```
Hope this helps

**Comment by alexbaras** [comment]
finally getting back to this ... i see now where the germline stuff could be filtered out, thanks

however, it would seem that some filtering would be needed before annotation though?
even on gene panel testing i would have >1000 variants to annotate that would never pass depth and VAF thresholds first

thoughts?

**Comment by alexbaras** [comment]
can you send some CNVKit calling examples for tumor only?

thanks

-Alex

**Comment by chapmanb** [comment]
Alex;
For tumor only CNVkit calling, the setup is the same as described above: a single sample labelled as `phenotype: tumor`, then add `svcaller: [cnvkit]`. There is nothing special about tumor-only CNVkit calling compared to single sample CNV calling since we don't have population databases to try and remove germline and noisy regions.

For your filtering question, I'm not sure what you're asking. You'll absolutely need to do additional filtering beyond what bcbio provides since we can't effectively remove all germline mutations. Anything germline in your cohort that is not in population databases at a high frequency will not get flagged. You'll likely want to prioritize based on variant impact or a set of genes of interest. Hope this helps.

**Comment by alexbaras** [comment]
For variant filtering

What I mean is I would filter out things below say ~ 3 % VAF before ever trying to annotate those further

Or else you would have a ton of noise to annotate for no reason because they would filtered out based on sequencing data criteria (vaf is this example)

Make sense?

On Jun 30, 2017 6:11 AM, Brad Chapman <notifications@github.com> wrote:

Alex;
For tumor only CNVkit calling, the setup is the same as described above: a single sample labelled as phenotype: tumor, then add svcaller: [cnvkit]. There is nothing special about tumor-only CNVkit calling compared to single sample CNV calling since we don't have population databases to try and remove germline and noisy regions.

For your filtering question, I'm not sure what you're asking. You'll absolutely need to do additional filtering beyond what bcbio provides since we can't effectively remove all germline mutations. Anything germline in your cohort that is not in population databases at a high frequency will not get flagged. You'll likely want to prioritize based on variant impact or a set of genes of interest. Hope this helps.

**Comment by chapmanb** [comment]
Alex;
That definitely makes sense. However, all of that processing by VAF and other external annotations is primarily done post-annotation since it's project specific, and is the primary reason we integrate with interactive tools like GEMINI. Hope this helps.
