### ISSUE TITLE
ipython: weird behaviour when parallelizing

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1982]
Hi Brad,

We're seeing some strange behaviour during our tests using iPython.

We use ipyparallel to schedule our bcbio jobs using torque. We have 3 nodes, 2x 15 cores/32GB and 1x 7 cores/8GB. In earlier version, we would run the submission job on the smaller node, and iPython would then spread the analysis jobs over the 2 bigger nodes. Since the update, we're noticing that iPython submit much more jobs with smaller requirements, instead of running the less jobs with more requirements.
Example:
bcbio 1.0.2 and before, during annotation with VEP , ipython submitted 4 jobs, using 7 cores each on the bigger nodes. In the latest version, the same happens, but using only 4 cores.

Any idea why this could be? There have been no changes to our cluster. Did something change upstream? Could this have anything to do with the version of ipython-cluster-helper used by bcbio? (I noticed the conda recipe doesn't use the latest version).

Thanks for the help
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for the report and sorry about the scheduling differences. If cores changed, it sounds like bcbio is probably scaling down to match the memory usage. If you have a heterogeneous cluster with different types of machines, it could report different memory/core usage for your two machines: 2Gb/core for the bigger nodes and 1gb/core for the smaller.  Since bcbio tries to determine memory per core by scheduling a job, which one it picks would be influenced by where the job got placed.

I'd recommend manually setting the system cores/memory you want for representing machines in your queue to avoid this:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#determining-available-cores-and-memory-per-machine

Hope this helps get it running reliably for you. Please feel free to re-open if this doesn't fix the issue.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for the reply, some small config changes have had some effect. Just a quick follow up question. In `bcbio_system.yaml` it is possible to manually set machine resources like so:
```
resources:
  machine:
    memory: 48.0
    cores: 16
```
The question now, can we replace `machine` with the FQDN of the different nodes in the cluster and specify the `machine` param for each node? I think this would make sense for heterogenous clusters.
If not, how would you feel about implementing such feature? Would it be at all possible without any major changes in the code?

Thanks 
M

**Comment by matthdsm** [comment]
Alternatively, if it's not possible to specify the different nodes, would you recommend setting the `machine` param to the spec of the biggest or smallest node?
I suppose setting the specs to the smallest node would cause ipython to submit multiple jobs to the bigger nodes (if resources allow it)? 

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
We don't have a way to specify by node type, and in general don't have the capability to schedule like that with our implementation. We're providing one batch script request to the cluster with resources, not machine specific ones, so can't fine tune to get multiple different engine types spun up together. I'd generally just try to come up with a specification that allows you to maximize usage across your cluster. As you said, specifying the smaller node specs will result in multiple jobs on bigger nodes so that does maximize total cores available. Alternatively if you'd rather use bigger machines with bcbio and leave smaller ones for other jobs you can specify to your larger machines. Hope this helps.

**Comment by matthdsm** [comment]
Allright, thanks for the info!
M
