### ISSUE TITLE
MaxCov bam files are recreated if analysis fails and is restarted at GATK4 gVCF import stage. 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2022]
Hi, 

The MaxCov bam files are recreated if analysis fails and is restarted at GATK4 gVCF import stage. 

Creation of gVCF files worked, I have a `gatk-haplotype` directory with gVCF files.  Then the GATK4 gVCF GenomicsDBImport command failed.  In my case because of issue https://github.com/chapmanb/bcbio-nextgen/issues/2021 but I can imagine  GenomicsDBImport  might also fail for many other possible reasons. 

Restarting bcbio at the GenomicsDBImport  step (and also later steps?) causes all the MaxCov bam files to be recreated, which takes substantial amount of time. 

Could the MaxCov bam files be kept untill the entire analysis is finished?

Maybe by replacing the current final BAM files? Only difference with current final bam files is that reads in high coverage areas have a QC failed flag?

Or by only deleting these MaxCov bam after all other analysis is done, i.e. at the copy to final directory step? So that they can be re-used in the case of an analysis crash and restart. 

Also creation of the MaxCov bam files currently seems to be single threaded and running on the cluster master machine, instead of in parallel via  jobs on the cluster machines. 

Thank you.

**Comment by chapmanb** [comment]
Neill;
Sorry about the problem. The maxcov is the new approach to avoiding extremely slow runtimes in repetitive regions. Because you are on a re-run it doesn't re-submit this to the cluster but if you remove `checkpoints_parallel` it will do the right thing.

I've been testing this on whole genomes and agree that the separate step is running slower than I'd like. I'll work today on adding this as part of the alignment merging step which should avoid it being the bottleneck and also avoid needing the extra step during re-runs. Apologies about the issue with your testing.

**Comment by NeillGibson** [comment]
Ok thank you for the advice and good to know that the high depth read flagging will be done during alignment in the future. 

One concern that I have is that our existing collection of archived BAM files then probably has to be replaced with the  MaxCov bam files. 

Otherwise either the MaxCov bam need to be recreated for every re-analysis that runs on the expanding set of bam files.  (by checking the bam header for if highdepth has been marked in this bam)

Or the re-analysis would run in to troubles in the high depth region, because it assumes high depth has been marked but can't use the new strategy because in reality no highdepth reads have been marked.

**Comment by chapmanb** [comment]
Neill;
Thanks again for the feedback. The latest development version now does this maximum coverage downsampling as part of the post alignment sorting/merging so will avoid the separate single core penalty and problem with re-runs. If you update to that it should now skip this and proceed directly on with your analysis.

Practically this fixes edge cases where callers are very slow on high depth regions. The older approach was doing a pretty poor job of catching these (hence the change) so I'd only re-run samples for applying maximum coverage downsampling if you're running into issue. If not, you should be able to proceed as before and hopefully all will work cleanly.

Thanks again for the feedback and please let me know if you run into any issues at all.

**Comment by NeillGibson** [comment]
Hi Brad. Does this mean that variant calling using bcbio (starting from existing bam files) is from now on only compatible with MaxCov annotated bam files?

i.e. If I start variant calling from existing bam files that are not MaxCov annotated do I have a high chance of running into trouble in high depth regions?

Thank you.

**Comment by chapmanb** [comment]
Neill;
No, I think you'll be fine with most samples. The previous high depth approach wasn't doing a great job of capturing these regions so analyses have been working well despite it rather than because of it. We analyzed a bunch of slow ones doing a poor job and this tackles it more comprehensively, so I'm hopeful this will improve it going forward but you can keep moving with samples that already ran well. It also only affects callers that don't downsample internally like VarDict so is a small, but frustrating, subset of cases. Hope this helps.

**Comment by NeillGibson** [comment]
Thank you for the extra information. Was wondering if I needed to recreate all already existing bam files that we have. Good to known that this probably not necessary.
