### ISSUE TITLE
GATK4: catVariants is renamed to GatherVcfs, fall back to bcftools concat causes downstream issues

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2023]
Hi, 

In GATK4 catVariants is renamed to GatherVcfs. I can't find GatherVcfs in the current bcbio code. 

The gVCF files that go in to GenomicsDBImport using the current bcbio have been concatenated using bcftools concat. 

GenomicsDBImport subsequently crashes with the following error. 
`htsjdk.tribble.TribbleException: Could not decode field MLEAF with value nan of declared type Float`

I used GatherVcfs (which has an automatic nice and fast naive vcf.gz concat!):
`gatk-launch GatherVcfs -I my_sample_01-files.list --output my_sample_01.vcf.gz`

The are some records left in the merged gVCF files that have `MLEAF=nan` , based on `bcftools query -f '%MLEAF\n' | sort -u`

GenomicsDBImport seems to be happy with the GatherVcfs  concatenated gVCF files. 

There is an issue open btw at GATK4 github about renaming GatherVcfs again in GATK4 official release, to distinguish it from Picard GatherVcfs ,  just so you know.

**Comment by chapmanb** [comment]
Neill;
Thanks much for the pointer. The latest development version incorporates this, which appears conceptually similar to `bcftools concat --naive`. I also fixes the GATK merge issue which was due to non-diploid calls from chrM in the first file missing a phasing attribute, so they can take advantage of these methods. I'll follow the GatherVcfs issue on the GATK codebase and swap over when they change the naming as well. Thanks again.
