### ISSUE TITLE
'EOF in multi-line statement'

### ISSUE THREAD

**Issue by alexanderaivazidis** [chapmanb/bcbio-nextgen#2028]
Hi,

I am getting an error message that is hard to give any meaning to for me. It comes up when I am running the RNA-seq pipeline on 24 cores and 48GB of RAM. If I don't use multiple cores, the message does not show up... Also it seems like the pipeline keeps on running despite this error message, so here it is:

[2017-08-01T10:37Z] Running STAR aligner on /ngs/projects/CVMD/CVMD_0008_PublicSingleCellRNA/datasets/PRJEB15398/ERR1629983_1.fastq.gz and /ngs/reference_data/genomes/Hsapiens/hg38/star/

An unexpected error occurred while tokenizing input file /opt/az/chapmanb/bcbio-nextgen/1.0.4/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.pyc
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (32, 0))

An unexpected error occurred while tokenizing input file /opt/az/chapmanb/bcbio-nextgen/1.0.4/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.pyc
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (32, 0))

I have seen something similar came up in a previous issue (https://github.com/chapmanb/bcbio-nextgen/issues/672) and there the advice was to update bcbio, but I definitly have the most recent version installed at the moment. Thanks for your help!

Alexander

**Comment by chapmanb** [comment]
Alexander;
Sorry about the issues and thanks for the report. The `EOF` message is pretty generic multicore failure output so is unfortunately not helpful in remotely diagnosing what went wrong. You might have to dig earlier in the run to see what is going on. My guess would be that there are some kind of memory issues since STAR is pretty memory hungry.

I also don't believe STAR is currently recommended for hg38 data because of all the alternative contigs. I'm cc'ing in @roryk to confirm, but suggest you use hisat2 instead of STAR for hg38.

Hope this helps.

**Comment by alexanderaivazidis** [comment]
Thanks, it looks like memory was indeed the issue! Thanks also for reminding me not to use Star with hg38, I forgot about that.
