### ISSUE TITLE
installing bcbio into existing conda environment

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#2051]
Hi Brad,

Since we're very happy with bcbio in our isolated production environment, we'd like to make it available to our researchers. However, we already have a conda environment with various software packages installed. Is it possible to "add" bcbio to an existing conda environment? I've already installed the package through bioconda, but I've no idea where to put all of the config files.

Thanks
M

**Comment by chapmanb** [comment]
Matthias -- thanks for the discussion. We generally don't recommend this approach since bcbio does rely on specific versions of some tools. It seems likely to get things in an incompatible state manipulating the environment regularly outside out the bcbio update process. Since it's not a big disk space hit, we prefer to treat bcbio and the tools as a separate environment that users can inject into their path as needed. You could share bcbio this way as a module, which is how most HPC users manage and share bcbio. Hope this helps.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for the reply. I already had a slight suspicion this would be the case. We'll have to go that way then.

Thanks again!
M
