### ISSUE TITLE
Processing qseq illumina files

### ISSUE THREAD

**Issue by eyalbenda** [chapmanb/bcbio-nextgen#2054]
Our core facility supplies us with links to download qseq files, which we then need to convert to fastq, demultiplex, convert phred scores etc. 
So far we've only supplied fastq as input to bcbio, I wanted to know if bcbio-nextgen supports raw qseq processing and if so how to configure it as input.

**Comment by chapmanb** [comment]
We don't handle qseq and demultiplexing as part of bcbio, since most folks handle this upstream using Illumina software. We used to have some basic functionality for integrating with sequencers and running bcl2fastq but it hasn't gotten much work in a while as we focus on downstream processing from fastqs. Most of the setups now are so complex with barcoding that you really need samplesheet and LIMS integration to do it reliably.

Sorry to not have this in place but hope this helps.
