### ISSUE TITLE
Gnomad Exome/Genome frequencies

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#2061]
Hi Brad,

Since the v90 release of Ensembl, there's a vcf available with both the genome and exome frequencies from GnomAD for both GRCh37 and hg38.

Would you be interested in using these resources in the pipeline? These can easily be added to the vcfanno `gemini` config, replacing ExAC.
see http://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad

Cheers
M

**Comment by matthdsm** [comment]
Small note, the vcf file is about 28GB, so adding this will have some impact on storage.
If we're sticking to the exome data, this is included in the VEP cache, so no additional work is required then.

M

**Comment by chapmanb** [comment]
Matthias;
It would be great to add the gnomad exome frequencies pre-built into VEP. That sounds like a no overhead option that would add additional information for those using VEP. I'd suggest supplementing the existing ExAC annotations for now (instead of replacing them) so folks can migrate their downstream scripts that process these.

What were you thinking of for supporting the full gnomad VCF? I'd be open to including this as a separate download under the `--toolplus gemini` flag and incorporating into the vcfanno recipes.

Thanks again for looking into this.

**Comment by matthdsm** [comment]
Hi Brad,

The GnomAD exome data was added automatically when upgrading to vep 90 and with the flag added in chapmanb/bcbio-nextgen#2060, so that's already done.

I think adding the full GnomAD vcf as a datatarget option would be great, that way users can decide for themselves if they want to take the storage hit or not. I'll prepare a PR for cloudbiolinux with the GGD recipe for GnomAD. This will be hg38 only, since GnomAD is already incorporated into gemini on GRCh37.

M

**Comment by matthdsm** [comment]
ref chapmanb/cloudbiolinux#256

**Comment by matthdsm** [comment]
ref #2063

**Comment by matthdsm** [comment]
Closing, since both the exome and genome set was added.

Thanks for all the work!
