### ISSUE TITLE
Genome graphs RFC

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#2088]
So there is another [graph-based variant caller](https://github.com/nygenome/lancet/blob/master/README.md), this one claiming superiority over `strelka2` (and featuring a non-free license). Is this something that is of interest to this community or are these approaches not mature/integrated/standardized enough? 

It's the future I'm sure, so the question is not if but when us Bioinformatics cores are making the switch, I guess.

**Comment by ohofmann** [comment]
I've kept an eye on this one. My main worry is that I didn't see any activity in that repo for almost a year except a flurry of updates around the preprint. If this is still under active development I'd be interested, but happy to wait a bit longer to see where it goes.

**Comment by schelhorn** [comment]
Agreed.

**Comment by chapmanb** [comment]
Sven-Eric and Oliver -- thanks much for this discussion. I'm excited by all the work on graph-based callers and am looking forward to integrating and testing these. In addition to lancet, I've wanted to look at vg (https://github.com/vgteam/vg) and graphtyper (https://github.com/DecodeGenetics/graphtyper).

The one challenge right now is that we need to incorporate better publicly available test datasets into standard bcbio validations so that we can demonstrate the global usefuless (or lack thereof) of moving to these methods. The DREAM synthetic 4 validation is okay but has some biases that are not reflective of real calls, and the NA12878/NA24385 mixture we've used appears to have a high false negative rate due to date quality in the NA24385 sample. Lancet's virtual tumors look useful and worth investigating, but won't be a very good way to assessing Lancet since it's been optimized for these.

Practically, Lancet's license is academic only so I'd prioritize graphtyper or vg as choices that could be used more broadly.

Thanks again for this discussion.

**Comment by schelhorn** [comment]
Thanks for the comments - I'm closing this for now and am happy to continue the discussion once broad interest in this topic renews (probably in a year or so, by my estimate).
