### ISSUE TITLE
Heads up: breaking changes in mosdepth

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#2094]
Hi Brad,

I just updated the conda recipe for mosdepth to the latest version (v0.1.9). This release includes some breaking changes compared to the old behavior. I suspect this will have some effect on usage of mosdepth in bcbio.

Just so you know, before any issues arise in new installs.

Cheers
m

**Comment by chapmanb** [comment]
Matthias -- thanks much for the heads up and putting in a bioconda update. I've been working with Brent on this new version and have an update to bcbio callability calculations to go along with it. I just sent a dueling PR for mosdepth in bioconda based on what I had locally since it also requires fixes to the install.sh patch in addition to bumping the version. Hope that works, it seemed easier than trying the git magic to get them into your branch. Once that's built and available I'll check in the coordinated bcbio fixes and close this. I'll appreciate any testing on the updated approach. Thanks again.

**Comment by matthdsm** [comment]
Hi Brad,

Good to see you were already prepared. It seems the build of my conda recipe had failed so thumbs up for yours! 👍 

If we find any issues during testing, I'll be sure to let you know!

Cheers
M
