### ISSUE TITLE
Mosdepth in v1.0.5

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#2105]
Hi Brad,

I noticed our production install of bcbio uses an general call to Mosdepth during QC. However, this causes bcbio to use the wrong version (latest, in our main env) instead of the one in the bcbio env.
Do you suppose this could be fixed in the 1.0.5 tag?
If not, would a manual fix with something like this work to get the version from the bcbio env?
`mosdepth = config_utils.get_program("modepth", data)`

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
Unfortunately we don't have version pinning tied to releases right now so this is likely the source of the trouble. I'm hoping to test and stabilize the current development and push a new release to resolve this. In the short term, the best approach is to ensure that your PATH is set so that it points to the 1.0.5 before your main environment. We're generally trying to avoid ad-hoc setting config_utils paths since it's not done consistently throughout bcbio.

Sorry about all the changes surrounding this. I'm hoping it'll all be worthwhile to folks with the speed improvements in the latest development version.

**Comment by matthdsm** [comment]
Hi Brad,

Thanks for the info. We try to keep both environments apart, and the path is set to include only the bcbio env. I suppose it's an issue with PBS resetting the path to default I suppose.

Cheers
M
