### ISSUE TITLE
PAR1/2 generally excluded with hg19 + bwa

### ISSUE THREAD

**Issue by gabeng** [chapmanb/bcbio-nextgen#2107]
I just noticed that one will never have any variant calls in PAR1/2 using hg19 and bwa alignment: bwa sets MAPQ to zero if there are secondary alignments. Since PAR1/2 on chrY is not N-masked in hg19, this is naturally the case. I suggest to mention this in the docs and to recommend GRCh37 (the 1kg version with decoy and masking) or to remove hg19 entirely.

**Comment by chapmanb** [comment]
Ben;
Thanks much for the discussion. Both GRCh37 and hg19 do not handle duplicated regions well. We've been suggesting moving to hg38, which is fully supported in bcbio and has specific support for handling regions with identical alternative choices. Would this work for your analyses? In terms of docs, we've written up a validation (http://bcb.io/2015/09/17/hg38-validation/) but happy to add it to the standard docs as well if you can suggest a useful location to provide this information. Thanks again.

**Comment by gabeng** [comment]
I totally agree that moving to hg38 would be the best idea, but that is not up to me, unfortunately. 
Many people may not be aware of the difference between choosing hg19 and GRCh37 in bcbio. The best place to add a note may be here: http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html?highlight=grch37#reference-genome-files

**Comment by chapmanb** [comment]
Ben -- understood about build 38, although practically bcbio's GRCh37 and hg19 distributions should both have the same issues with repetitive regions, so I don't believe it helps to choose one over the other. Both are based on the Broad distributions which don't have decoy and masking. We'd avoided adding these in because of mixed reviews from people on the effects of decoys, arguing in favor of fixing it properly in build 38. I haven't done a full validation of decoy and not but heard both recommendations and detractions from people who had. Do you find adding it unambiguously better in your validations?

**Comment by gabeng** [comment]
Brad, I havent't checked the decoys, but the PAR1 is definitely masked in your build of GRCh37, but not in hg19. How can I check exactly the provenance of the genome builds?

**Comment by chapmanb** [comment]
Ben -- thanks so much for the heads up. I hadn't realized this and amended the documentation to be clear about this difference as well as linking to more resources:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#reference-genome-files

The bcbio distributions are from the Broad b37 and hg19 bundles, but the provenance of those is not as definite other than being from the 1000 genomes distribution. Apologies, build 37 is so frustrating and we've tried to resolve this as much as we could with 38 by using a single unambiguous distribution.

Thanks again for this helpful discussion and I'm glad GRCh37 is providing what you need. Let me know if you run into anything else at all worth highlighting.
