### ISSUE TITLE
ftp connect to ftp.broadinstitute.org failed

### ISSUE THREAD

**Issue by weizhu365** [chapmanb/bcbio-nextgen#2118]
I ran into some error while installing genome refernece data:

Running GGD recipe: hg19 hapmap 3.3
--2017-10-21 10:21:02--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/hg19/hapmap_3.3.hg19.sites.vcf.gz
           => `-'
Resolving ftp.broadinstitute.org... 69.173.80.251
Connecting to ftp.broadinstitute.org|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ...
Login incorrect.

**Comment by chapmanb** [comment]
Sorry about the issue, this is typically caused by Broad's servers being busy. We don't have any control over these external resources, but the installer/upgrade process you were running will restart from where it left off if you run with the same command again. Hopefully the server will be happier when retrying and finish cleanly for you. Hope this helps.

**Comment by veggiesaurus** [comment]
Can we re-open this? FTP access is now disabled permanently, as documented [here](https://gatk.broadinstitute.org/hc/en-us/articles/360035890811), and Google bucket should be used instead.
