### ISSUE TITLE
nglims link broken

### ISSUE THREAD

**Issue by biocyberman** [chapmanb/bcbio-nextgen#2133]
I was reading the [sequencer integration](https://bcbio-nextgen.readthedocs.io/en/latest/contents/sequencer.html) session and tried the link  https://wiki.galaxyproject.org/Admin/SampleTracking/NextGen It is broken and nowhere to be found. So my next question is, how bcbio-nextgen is handling the integration with machines and LIMS?

This is something important, but it's not something urgent, just want to discuss and find something gradually.

**Comment by chapmanb** [comment]
Vang;
Sorry about the confusing and out of date documentation. I removed this from the documentation page as we're not actively supporting nglims since it hasn't gotten any love in a while. Practically we're no longer trying to tackle the sequencer integration as part of bcbio with an increased focus on the tools and pipelines. Our hope is that Common Workflow Language integration will give us interoperability with platforms that support automated LIMS processing. Most groups I know of are doing custom work around commercial LIMS so I don't unfortunately have a full open source solution right now. Sorry to not have this covered but hope this helps clear up the current status.

**Comment by biocyberman** [comment]
Thanks for the clarification, Brad. We are also customizing a commercial LIMS. But the whole process is time consuming and costly so I just want to check if there is any viable FOSS alternatives.
