### ISSUE TITLE
Single-end read support for Kallisto

### ISSUE THREAD

**Issue by IvantheDugtrio** [chapmanb/bcbio-nextgen#2150]

**Comment by chapmanb** [comment]
Ivan -- what kind of problems are you hitting with single-end reads? Could you describe what's happening so we can try to help.

**Comment by roryk** [comment]
Hi Ivan,

We have single-end support in kallisto but it is turned off at the moment. We've been avoiding clicking it on for kallisto because we don't have a great way of handling the fragment length parameter without requiring users input it. https://groups.google.com/forum/#!topic/kallisto-sleuth-users/h5LeAlWS33w has a little bit of discussion about it. It might be better to use Salmon instead which should give similar results.

**Comment by IvantheDugtrio** [comment]
I was just running this on an RNA expression library and wanted to see what kind of results I would get with Kallisto. Since I'm just playing around with different settings for the expression calling maybe it's best if I don't use Kallisto for this library what with varying fragment lengths and whatnot.

**Comment by Stefano04** [comment]
Sorry to reopen the threads. 

How conceptually wrong is it to use mean and sd of reads instead of mean and sd of fragments? 

Thanks for answering!

Stefano

**Comment by chapmanb** [comment]
Stefano;
From the discussion Rory links above, you do need to have some kind of general estimate of fragment (not read) length for single end. This could be from the library preparation or other information. If you don't have it, I believe using Salmon might be the better option. Hope this helps.
