### ISSUE TITLE
Changing MuTect2 options

### ISSUE THREAD

**Issue by tb08** [chapmanb/bcbio-nextgen#2175]
Hello,
Is it possible to specify different options for the variant caller beyond min_allele_fraction? For example  with mutect2, I would like to change max_alt_alleles_in_normal_count=1 to 2 or 3 in the cases for which I suspect my normal sample may contain a bit of tumor DNA contamination. Other options that might be useful to be able to tweak include   max_alt_alleles_in_normal_qscore_sum and max_alt_allele_in_normal_fraction. 
I tried adding a ressources section in my config file:
&nbsp;ressources:
&nbsp;&nbsp;mutect2:
&nbsp;&nbsp;&nbsp;   options: ["--max_alt_alleles_in_normal_count 3"]
But this did not change the mutect command being executed. Any suggestions?

**Comment by chapmanb** [comment]
Thanks for the question. MuTect2 support in bcbio should support the approach of adding options through the resources (https://github.com/chapmanb/bcbio-nextgen/blob/560fb6a926b5009c7819354b2fd0cd2880fd5deb/bcbio/variation/mutect2.py#L95) so you can tweak as you'd like. If that is an exact copy/paste from your configuration I believe the issue is a typo: change `ressources` to `resources`. Hope that helps explain it and get things working for you.

**Comment by tb08** [comment]
Hi Brad,
Indeed I made a typo with resources, my bad. Thank you very much for your fast reply and catching it.
