### ISSUE TITLE
Could not find or load main class org.broadinstitute.gatk.engine.CommandLineGATK

### ISSUE THREAD

**Issue by lananhle** [chapmanb/bcbio-nextgen#2179]
I installed GenomeAnalysisTK-3.8-0-ge9d806836 with java version "1.8.0_151" to call variant by using SRR database.
The command line i use that: 
$ java -cp "sra_gatk_package/*" org.broadinstitute.gatk.engine.CommandLineGATK -T
UnifiedGenotyper -I SRR835775 -R GRCh37/GRCh37.fa -L NC_000020.10:61000001-6110000
0 -o chr20.SRR835775.vcf.
Unfortunately, the errors i received is: 
Could not find or load main class org.broadinstitute.gatk.engine.CommandLineGATK

**Comment by chapmanb** [comment]
Sorry about the issue, this sounds like a general GATK problem which is better suited for the GATK forums and it looks like you cross-posted there: https://gatkforums.broadinstitute.org/gatk/discussion/10932/error-could-not-find-or-load-main-class-org-broadinstitute-gatk-engine-commandlinegatk#latest

As a quick suggestion to fix, the syntax you're using for calling GATK does not look right. You should be doing:
```
java -jar /path/to/GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar -T UnifiedGenotyper
```
It seems like you might be getting that syntax from an outdated source since UnifiedGenotyper is also no longer the recommended variant caller. Hopefully this provides enough to get your analysis going.
