### ISSUE TITLE
Possible regression error in Oncofuse

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#2195]
I get the error of this solved issue again: https://github.com/chapmanb/bcbio-nextgen/issues/1667 that @roryk fixed a while ago - perhaps something to do with the ericscript integration, @chapmanb?

**Comment by chapmanb** [comment]
Sven-Eric -- thanks much for the report and apologies for the oversight. It looks like we were still checking for the older `fusion_mode` parameter in order to enable generation of chimeric output reads for oncofuse and so didn't have those available for running. I pushed a fix which only uses `fusion_caller` and avoids the extra check on the deprecated variable. Hope this fixes it for your run, please let us know if you run into any other problems.

**Comment by schelhorn** [comment]
Thanks, Brad - it's appreciated. Also, you guys should take a couple of days off ;)
