### ISSUE TITLE
samtools sort exceeded memory limit on SLURM cluster

### ISSUE THREAD

**Issue by hliu2016** [chapmanb/bcbio-nextgen#2204]
I am running RNA-seq analysis on slurm cluster. My bam files are about 8~9G and each nodes has 64G memory. But I found that the pipeline failed at the step of samtools sort, the command in the log/bcbio-nextgen-commands.log file is:
`samtools sort -@ 16 -m 3G -O BAM -n -T /home/tmpOgdCOU/3_21Y_rep3.nsorted-sort -o /home/tmpOgdCOU/3_21Y_rep3.nsorted.bam /app/datamart/jieyi_bio/rat_star/work/align/3_21Y_rep3/3_21Y_rep3_star/3_21Y_rep3.bam`

I guess each thread may need more memory, so I went further to change the parameter in the bcbio_system.yaml. I set the cores to 4 and memory to 10G. However, the is not helpful and it still broke because of exceeding memory limit.

I have no much idea that samtools would use how many memory to sort a about 9~ bam file. How should I adjust the cores/memory parameters?

**Comment by chapmanb** [comment]
Thanks for the detailed report. The issue you're running into is that the memory you tell samtools to use is likely slightly exceeding the allocation for SLURM so the scheduler ends up stopping the job. In that sense tuning up and down will give similar problems, so keeping it at the original specification og 3Gb makes the most sense.

I pushed a fix to the latest development (`bcbio_nextgen.py upgrade -u development`) which should resolve this by slighly scaling down memory usage on samtools and also making it more precise by swapping over to Mb instead of Gb. I hope if you update and re-run that'll cleanly pass through this step and get your analysis finished. Hope this helps.

**Comment by hliu2016** [comment]
@chapmanb 
Thank you for your kind help.
