### ISSUE TITLE
How to specify to do variant calling with: Freebayes, GATK4 and GATK4 gVCF

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2210]
Hi, 

We have done some evaluations of GATK4 beta4 on our data using Picard GenotypeConcordance and did notice some differences between:

- Freebayes v.s. GATK4 gVCF
- Freebayes v.s. GATK4 multi-sample
- GATK4 gVCF v.s. GATK4 multi-sample

These differences concern mostly heterozygous (HET) genotypes. 
We did not find a direct correlation between these discordant HET genotypes and low genotype quality or depth.  

Therefore we would like to run all 3 variant calling methods (Freebayes, GATK4 multi-sample, GATK4 gVCF) on at least our incoming batches of samples. This until we can figure out what is causing the differences or get comfortable enough with just using the GATK4 gVCF results. 

How can I specify in the bcbio analysis yaml file that I want to run all the 3 variant calling methods?

The configuration below would just run freebayes and GATK4 gVCF right? How can I enable to also run GATK4 multi-sample (in addition to freebayes and GATK4 gVCF)?

```
variantcaller: freebayes, gatk-haplotype
jointcaller: gatk-haplotype-joint
```

Thank you.

**Comment by chapmanb** [comment]
Neill;
Unfortunately there isn't a way to run both batch and joint calling on the same set of samples. The configuration will let you do either one. Since this isn't a standard case we expected folks to run in production work, we haven't developed for it. When I run validations or benchmarking on these I use two separate samples (ie. NA12878-1, NA12878-2) and keep the configurations separate. This results in duplicated upstream alignment work but allows you to run them all in the same project.

Sorry it can't do what you're looking for but hope this helps as a workaround.

**Comment by NeillGibson** [comment]
Ok thank you for the information. I'll use the work around you suggested or limit our analysis to freebayes + GATK joint variant calling.
