### ISSUE TITLE
Question regarding XYZ-gdc-viral.bam file in QC

### ISSUE THREAD

**Issue by leiendeckerlu** [chapmanb/bcbio-nextgen#2220]
Hi there,

I was wondering if you use a downsampled read input for the alignment against the viral genomes to produce the XYZ-gdc-viral.bam file?

I'm asking since I get significantly more reads mapped to a viral genome, e.g. HPV16 if I use bwa mem directly on the fastq files.

Many thanks!

**Comment by chapmanb** [comment]
Thanks for the question, we use the unmapped reads for this assessment, which I'd guess is the source of the differences. Here's the command we use:

https://github.com/chapmanb/bcbio-nextgen/blob/0e176c39a3200a038671a780ac73c4eb3bc2f740/bcbio/qc/viral.py#L33

Hope this helps

**Comment by leiendeckerlu** [comment]
Thanks for the quick reply. 

Please correct me if I'm wrong, but this implies that the only reads that I can see in addition should be split and or spanning reads between HPV16 and, let's say hg38, right?

**Comment by chapmanb** [comment]
That's exactly right, anything that maps reasonably to hg38 wouldn't be present, so if bwa could softclip a HPV specific section and still align it would not get included. This is a little imperfect but bcbio is meant as a quick count for presence/absence rather than a quantitation. Aligning the whole fastq would take a while but if there are other approaches to do this we'd be happy to explore.

**Comment by leiendeckerlu** [comment]
Many thanks! As always highly appreciated. :)
