### ISSUE TITLE
fusion_caller oncofuse and ericscript did not run in RNA-seq pipeline

### ISSUE THREAD

**Issue by hliu2016** [chapmanb/bcbio-nextgen#2239]
Hi, I have run the RNA-seq pipeline to process 12 samples. The yaml file is as below:

> details:
>   - analysis: RNA-seq
>     algorithm:
>       fusion_caller: [pizzly, oncofuse, ericscript]
>       variantcaller: [gatk-haplotype]
>       transcriptome_align: True
>       aligner: star
>       quality_format: standard
>       #trim_reads: read_through
>       #adapters: [truseq, polya]
>       #tools_on: [gatk4]
>       expression_caller: [stringtie, salmon]
>       transcript_assembler: [stringtie]
>       #spikein_fasta: ../data/spikeins/spikeins.fa
>     metadata:
>       batch: TestBatch1
>     description: Test1
>     genome_build: rn6
> 

The pipeline successfully finished and most files are upload to the final directory. However, I noticed that no results can be found for the fusion_caller oncofuse and ericscript, while pizzly has results. For oncofuse and ericscript, their executables are in the PATH environment and can be called directly. So, why they did not run? 

Besides, the variants (saved in vcf files) called by gatk have been uploaded to each sample directory, combined the variants with respect to the batch metadata. Would you like to merge the variants of all samples and upload a copy to the project directory in the final folder? I think this will greatly facilitate the downstream analysis.

**Comment by chapmanb** [comment]
Thanks much for the bug report and feedback. Right now oncofuse and eriscript only work on human genome builds so won't run for your rn6 sample. Apologies for the lack of documentation on this; I updated the configuration docs to reflect this.

We also updated the outputs for gatk variant calling so that individual sample gVCFs are in the sample directories and a joint called, annotated and filtered VCF is present in the project directory. If you update to the latest development version (`bcbio_nextgen.py upgrade -u development`) and re-run it should hopefully provide what you need for your downstream analysis.

Thank you again for the helpful feedback and report.
