### ISSUE TITLE
Any specific reason for disabling MKL?

### ISSUE THREAD

**Issue by userbz** [chapmanb/bcbio-nextgen#2246]
Hi,

I have been trying to install bcbio today on an Ubuntu subsystem under Windows 10 (WSL). There were some errors I have encountered related to the [nomkl] packages. 
After removing the following line from the installer, the installation was completed without problem. 
subprocess.check_call([anaconda["conda"], "install", "--quiet", "--yes", "nomkl"])

As far as I know, the Intel MKL library boosts the Numpy/Scipy performance significantly (at least for Intel CPUs). That might also be the reason that the newer versions of Numpy/Scipy have it by default. 
May I ask what is the reason to install nomkl before all other packages? At least for me, the nomkl version of numpy failed to work properly and ended up with segmentation faults.

Best, 
Bob

**Comment by chapmanb** [comment]
Bob;
Thanks much for the feedback and testing on the Windows 10 Linux subsystem. It's great that things work minus the nomkl issues, so to support this I removed the requirement for nomkl and make it an option. We used it because we don't really do a ton of numpy/scipy compute that would benefit from it and the MKL libraries are quite large. However, that's probably not an issue for many installs so it's great to have it be flexible.

We're planning to have a new release soon which will finalize all this so hopefully 1.0.8 will install cleanly for you on WSL. Thank you again.

**Comment by userbz** [comment]
Hi,
Thank you!
You are right that MKL has become chunky, which could be expensive if installed in every conda environment. I tried to avoid that by installing bcbio within an existing env, but wasn’t successful. It seemed that bcbio prohibits that due to some restrictions on external resources. 
Anyway, it is great that a new version is coming soon. I am looking forward to it. 

Regards,
Bob
