### ISSUE TITLE
new mapping tool: elPrep

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#2256]
Hi Brad,

I don't know if you're interested in supporting yet another mapper, but I was wondering if you've already heard of [elPrep](https://github.com/ExaScience/elprep).

elPrep is a mapping tool developed as an industry colaboration at a university here in Belgium.
There's a small talk from FOSDEM available on [youtube](https://www.youtube.com/watch?v=l2BZoyzj6VM) and a [paper](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0132868) in PLOS one. If we believe the paper, this tool can amount to a 6-10x speedup for mapping.

Cheers 
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for the heads up on elPrep. This is replacement for BAM manipulation tools like samtools, biobambam and sambamba rather than an aligner. I'd evaluated this a few years ago when it was written in Lisp but it looks to have been re-written in go. We're already using multithreaded support in our existing tools so I'm not sure if elPrep will provide substantial speedup. If you want to evaluate compared to multi-threaded samtools or biobambam and find improved speeds we'd be happy to look at incorporating where it makes sense. Thanks again.

**Comment by matthdsm** [comment]
Hi Brad,

I'll have a look into possible speed gains using elPrep. I'll close this issue for now and reopen after I've had the time to do a serious evaluation.

Cheers
M

**Comment by matthdsm** [comment]
Hi Brad,

I'm going to look a bit into integration elprep into bcbio. Since elPrep does splitting/merging and duplicate marking. Like you said, this looks to be an alternative for biobambam and sambamba. Are there any other thing I need to look out for?

Thanks for any pointers you have.

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for looking into it. My suggestion would be to test first outside of bcbio to see if you find a speed improvement over biobambam2 or samtools for the commands you're looking to sub in. Before investing time in integration we should understand the benefit it provides. If you find improvements, then we'd need to add it as a configuration option and run some validations to ensure outputs are functionally equivalent. Thanks again for working on this.
