### ISSUE TITLE
feed CNVkit reference data

### ISSUE THREAD

**Issue by schneiderthomas** [chapmanb/bcbio-nextgen#2269]
Hi,

I was wondering if there is a way to supply control *.cnn when setting up a bcbio run.  I am interested in germline SV detection and want to use the same references every time run a new case.  However, it seems from the documentation the controls *.cnn file will recalculated every time bcbio runs.

Am I correct in this statement or is there I feature I missed?  Could a feature be made where this could be supplied?

**Comment by chapmanb** [comment]
Thanks much for starting this discussion. This is definitely something we'd like to support and I started with a basic framework to specify these. We need to work on the actual implementation within CNVkit which requires two additions:

- Identify the target and antitarget BED regions from the input background file so these are consistent with the newly generated coverage bins for input samples.
- Substitute in the supplied background reference CNN instead of calculating background.

I'll continue to work on implementing this and track progress here to let you know when it's ready. Thanks again for the suggestion.

**Comment by etal** [comment]
The CNVkit distribution includes a script `reference2bed.py` which unpacks the target and antitarget regions from the reference.cnn file into two BED files, with filename extensions added automatically. (Sorry if that complicates reuse here.) The same internal functions are used by CNVkit's `batch` command, so if bcbio uses this script, the behavior will be the same.

**Comment by chapmanb** [comment]
Thanks again for starting this discussion, and thanks Eric for the tip on `reference2targets.py`, that nicely filled in the missing piece for us.

The latest development version of bcbio supports specifying a pre-built background CNN with:
```
algorithm:
   background:
       cnv_reference: /path/to/your/background.cnn
```
Please let us know if you run into any problems and thanks again for the suggestion.
