### ISSUE TITLE
downloads during install fail when Sourceforge is in Disaster Recovery mode

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#2299]
This happened when trying to download 

http://downloads.sourceforge.net/project/adamajava/qsignature.tar.bz2

Instead of the bz2 archive I download a small html file, saying:

> We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
> the use of javascript to function.  Please check back later.

I guess I can wait, or download the file with a browser (it works that way), but I was wondering if there is a workaround to make the ggd recipe work with wget in "Disaster Recovery mode" whatever that means.

**Comment by chapmanb** [comment]
Sorry about the issue, this looks to be working now so I guess Sourceforge has recovered from their disaster. We don't have a workaround for failed external downloads other than retrying later. We often cache downloads that are especially problematic in S3 but try to avoid this if we can since that relies on us paying the download costs.

Sorry again and hopefully retrying now gets everything working cleanly for you.
