### ISSUE TITLE
odd ensemble behavour

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#723]
I'm using ensemble with the setting ensemble: numpass: 2 and encountered some strange behavour.

For some reason, freebayes thinks that a SNP exists although there are no reads that support it (AO=0). No other caller (gatk-haplotype, platypus, samtools) thinks that there is a snp there. Bcbio-nextgen's ensemble caller agrees with Freebayes, however: 

Freebayes call:
15-52-freebayes.vcf:chr2	179583496	rs16866465	T	G	6256.21	PASS	AB=0.847896;ABP=327.853;AC=1;AF=0.166667;AN=2;AO=264;BaseQRankSum=1.473;CIGAR=1X;DB;DP=958;DPB=958;DPRA=1.62827;EPP=576.279;EPPR=1507.84;FS=0;GC=44;GTI=1;HRun=0;HaplotypeScore=12.9334;LEN=1;MEANALT=1.5;MQ=59.97;MQ0=0;MQM=60;MQMR=59.9481;MQRankSum=0.641;NS=6;NUMALT=1;ODDS=45.2655;PAIRED=1;PAIREDR=0.998557;PAO=0;PQA=0;PQR=0;PRO=0;QA=9282;QD=18.96;QR=25022;RO=693;RPP=3.0432;RPPR=3.01343;RUN=1;ReadPosRankSum=-0.205;SAF=131;SAP=3.0432;SAR=133;SRF=346;SRP=3.01343;SRR=347;TYPE=snp;technology.illumina=1;EFF=INTRON(MODIFIER||||26926|TTN|protein_coding|CODING|NM_003319.4|46|1),INTRON(MODIFIER||||27051|TTN|protein_coding|CODING|NM_133432.3|47|1),INTRON(MODIFIER||||27118|TTN|protein_coding|CODING|NM_133437.3|47|1),NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|gAa/gCa|E6900A|33423|TTN|protein_coding|CODING|NM_133378.4|81|1),NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|gAa/gCa|E7827A|34350|TTN|protein_coding|CODING|NM_001256850.1|82|1),NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|gAa/gCa|E8144A|35991|TTN|protein_coding|CODING|NM_001267550.1|84|1)	GT:AO:DP:PL:QA:QR:RO	0/1:0:80:0,100,100:0:2871:80

Ensemble call:
15-52-ensemble.vcf:chr2	179583496	rs16866465	T	G	6256.21	PASS	AB=0.847896;ABP=327.853;AC=2;AF=0.166667;AN=12;AO=264;BaseQRankSum=1.473;CIGAR=1X;DB;DP=958;DPB=958;DPRA=1.62827;EFF=INTRON(MODIFIER||||26926|TTN|protein_coding|CODING|NM_003319.4|46|1),INTRON(MODIFIER||||27051|TTN|protein_coding|CODING|NM_133432.3|47|1),INTRON(MODIFIER||||27118|TTN|protein_coding|CODING|NM_133437.3|47|1),NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|gAa/gCa|E6900A|33423|TTN|protein_coding|CODING|NM_133378.4|81|1),NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|gAa/gCa|E7827A|34350|TTN|protein_coding|CODING|NM_001256850.1|82|1),NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|gAa/gCa|E8144A|35991|TTN|protein_coding|CODING|NM_001267550.1|84|1);EPP=576.279;EPPR=1507.84;FS=0;GC=44;GTI=1;HRun=0;HaplotypeScore=12.9334;LEN=1;MEANALT=1.5;MQ=59.97;MQ0=0;MQM=60;MQMR=59.9481;MQRankSum=0.641;NS=6;NUMALT=1;ODDS=45.2655;PAIRED=1;PAIREDR=0.998557;PAO=0;PQA=0;PQR=0;PRO=0;QA=9282;QD=18.96;QR=25022;RO=693;RPP=3.0432;RPPR=3.01343;RUN=1;ReadPosRankSum=-0.205;SAF=131;SAP=3.0432;SAR=133;SRF=346;SRP=3.01343;SRR=347;TYPE=snp;technology.illumina=1	GT:AO:DP:PL:QA:QR:RO	0/0:2:148:0,100,100:22:5332:146	0/1:262:309:100,0,100:9260:1646:46	0/1:0:80:0,100,100:0:2871:80	0/0:0:146:0,100,100:0:5314:146	0/0:0:122:0,100,100:0:4353:122	0/0:0:153:0,100,100:0:5506:153

**Comment by parlar** [comment]
By the way, a nice feature for the ensemble caller, run in the above mode, would be to include a list in the INFO field sating which callers actually supported the call and which did not.

**Comment by parlar** [comment]
Do you think that the freebayes call also should be submitted as an issue to the freebayes git repository? Can you see any other reason other than a bug for the call?

**Comment by chapmanb** [comment]
Par;
Sorry about the problem. The underlying issue is that the ensemble calling isn't treating multiple samples by splitting into individual samples and doing an ensemble of each. Instead it does a comparison by the position, so if other callers have a call at that position in a different sample it'll resolve the position itself to true and then pick the first representative caller set, which seems to be FreeBayes in this case.

I'd like to work on better multi-sample calling to split these and do the ensemble individually, then combine back together. I think that would then do the right thing in this case. This will take some development time.

It does seem like something is wrong with the FreeBayes calculation. I've been actively trying to update to the latest FreeBayes but am blocked by one issue: https://github.com/ekg/freebayes/issues/129  This might not be a problem if you're only doing pooled calling so you manually install and try the latest FreeBayes development version to see if it does the right thing on your data.

Sorry again about the issue and thanks for the report.

Separately,

**Comment by ekg** [comment]
@chapmanb I think the [recent changes in freebayes should resolve these problems](https://github.com/ekg/freebayes/commit/c0548503729eb06335904142e27cd9f823b9f839) on your end. Please let me know.

**Comment by lpantano** [comment]
hopefully the last comment helped with that. Let us know if you have further issues.

thanks a lot!
