### ISSUE TITLE
alternate timelimit for controller vs engine

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#736]
Looks like my engine/worker jobs are getting killed due to the controller/master job hitting the timelimit and shutting down. Sometimes compute resources are scarce and the slurm array of worker jobs can be serial in nature.

Is there a way to specify a different queue/timelimit for the the controller vs engine jobs? That way I can put the controller on a long running queue and the workers on something else.

**Comment by chapmanb** [comment]
Daryl;
Practially the controller and workers need to run for the same amount of time so we don't have a way to give these different queues/timelimits. IPython needs the whole setup available to run. bcbio will start going as soon as some engines are available but if they're being killed mid-run due to timelimits and replaced with others waiting it's not likely to be a very efficient run process since lots of analyses will be restarted midstream. Hope this helps.

**Comment by dwaggott** [comment]
Ahh right, that's what I guessed.

Notably, it's the controller job that gets killed. The first engine could
kick off right away but subsequent engines might take a while to muster
resources. The controller has to therefore stay active for potentially much
longer than any queue timelimits. We have long running queues but they are
very limited hence only really suitable for a controller process.

**Comment by chapmanb** [comment]
Daryl;
bcbio should start processing as soon as you can get 1 controller and 1 engine so if you can set engine parameters to at least be able to get a single job started that is probably the best way forward. Unfortunately trying to set controller/engine options separately would create a large number of command line arguments. This is likely to add a lot of complexity without a large improvement in your situation, since you're still going to run into issues with your engines getting killed under the current timelimits you're setting. Sorry to not have a better answer, I know dealing with highly over sub scribed clusters is hard.

**Comment by dwaggott** [comment]
Easiest solution was to post modify the resource request on only the controller job i.e.

```
scontrol show job 1437883 # QOS is normal
scontrol update JobId=1437883 QOS=long 
scontrol show job 1437883 # QOS is long
```

Please close.

**Comment by chapmanb** [comment]
Daryl -- glad you found a workaround and got it running. Thanks much.
