### ISSUE TITLE
locally define custom pipelines

### ISSUE THREAD

**Issue by zeneofa** [chapmanb/bcbio-nextgen#738]
Hi,

I was wondering if there was a way to locally define custom pipelines, for example creating a python script in the config directory (or the same directory as a template yaml file) with custom pipelines classes defined inside? My current problem is that it requires editing the installed module, bcbio/pipeline/main.py to achieve this. This may not always be feasible for systems where bcbio was installed by a sys-admin. 

I also tend to run multiple type of analysis' that are often repeated every so often, this could potentially lead to a very bloated main.py file. I also sometimes handle post pipeline analysis (such as custom plots, subsetting alignment files, downsampling etc) using python. It would be awesome to have a convenient way to integrate these scripts for each of the seperate pipelines I use.

**Comment by chapmanb** [comment]
Unfortunately we don't have a way to do this. You can use bcbio parallelization libraries from outside of the main runtime but setting this up as a way to run custom scripts hasn't been one of the development goals. Our main goal with bcbio has been to develop curated community-built pipelines, rather than building a toolkit for making your own pipelines, so we haven't emphasized this aspect.

Longer term we're hoping to integrate with tools using the common workflow language (https://github.com/common-workflow-language/common-workflow-language) so it's easier to do these type of custom additions with tools that support them more generally.

Sorry to not have a good solution for you but hope the explanation of project goals helps some.

**Comment by zeneofa** [comment]
No problem, thanks for the info. Will check if I can scratch something up.

Thnx again for all the work you guys are going, much appreciated.

**Comment by lpantano** [comment]
Hi, I understand your idea. What i ended up is using the functions of bcbio, like many functions inside `bam.py` or `fastq.py`  or all that ones that are `basic` functions but so common. I mix that with an 'easy' implementation of ipython_cluster_helper copying code from @rory, like this one: https://github.com/roryk/singlecell/blob/master/singlecell/cluster.py.  

I worked a little bit more in that code, and finished having something like this: https://github.com/lpantano/seqcluster-helper/blob/master/sqhelper/cluster.py and calling the different functions like this: https://github.com/lpantano/seqcluster-helper/blob/master/scripts/seqcluster-helper.py#L61

I just copy the same cluster.py code in any other pipeline i want to do and modify according the different steps. You need to do this like a package to get all functions imported when ipython send the jobs to the cluster. 

is not the solution to the problem, but implementing parallelization with ipython-cluster-helper is amazing, and using functions from bcbio is amazing to and saving much time.

**Comment by roryk** [comment]
Closing this out for now, we're still betting on CWL working out in which case doing stuff like this will be much easier.
