### ISSUE TITLE
LooseVersion instance has no attribute 'version'

### ISSUE THREAD

**Issue by alig99** [chapmanb/bcbio-nextgen#748]
Hi,  I have tried many things, but cannot get past this error.
I have done an isolated installation of bcbio & was just trying to a test run of the Exome with validation against reference materials using NA12878-exome.

/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 89, in _group_by_ctype
    if LooseVersion(programs.get_version_manifest("bedtools")) >= LooseVersion("2.22.0"):
  File "/bcbio/anaconda/lib/python2.7/distutils/version.py", line 296, in __cmp__
    return cmp(self.version, other.version)
AttributeError: LooseVersion instance has no attribute 'version'

Can anyone please help,   thanks alig

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. It looks like bcbio is having trouble determining the version of bedtools installed from the version manifest directory (in `/path/to/bcbio_install_dir/manifest`). I pushed a fix to give a more useful error message in this case, but the underlying issue is that there might be something problematic about your installation. How did you install bcbio? If you run a tool upgrade:
```
bcbio_nextgen.py upgrade --tools
```
Hopefully it'll correctly create the manifest with installed tools and you can proceed. Hope this helps.

**Comment by alig99** [comment]
Hi,  I did an isolated install.  So I then started the command
bcbio_nextgen.py upgrade --tools
but because of the isolated install I named the directory for the tools.
With hindsight this was a mistake because I ran the command
bcbio_nextgen.py upgrade --tools --tooldir=manifest                (as that dir was empty & though that    was where the tools were supposed to be found!)
So I think I was near the end of the upgrade when I got this error
Creating manifest of installed packages in /home/neuro/Documents/bcbio/manifest
Traceback (most recent call last):
  File "/home/neuro/Documents/bcbio/manifest/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/neuro/Documents/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 75, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/home/neuro/Documents/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 342, in upgrade_thirdparty_tools
    os.remove(os.path.join(manifest_dir, fname))
OSError: [Errno 21] Is a directory: '/home/neuro/Documents/bcbio/manifest/data'
Does this mean I should somehow uninstall & start all over again, I hope not!
Thanks for your help, alig

**Comment by chapmanb** [comment]
alig;
Sorry about the confusion. The script is having trouble because it doesn't expect the tools to be inside the manifest directory. That directory should only contain a list of YAML files that describe the installed versions.

Unfortunately, the best way at this point is probably to remove that manifest directory and run with:
```
bcbio_nextgen.py upgrade --tools --tooldir=/home/neuro/Documents/bcbio
```
to avoid creating more confusion. Hope this helps.

**Comment by roryk** [comment]
Closing out since this is pretty stale. Feel free to reopen if there is still an outstanding issue. Thanks!
