### ISSUE TITLE
Error: bamtools install

### ISSUE THREAD

**Issue by szuszmok** [chapmanb/bcbio-nextgen#761]
Hi Brad,

I couldn't finish the installation process, because of the bamtools download link is not available. At least I think this is the problem, but not sure.

Any suggestions for solving are welcome and thank you much!

[localhost] local: /usr/local/bin/brew info samtools
[localhost] local: export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install --env=inherit   bamtools

Warning: local() encountered an error (return code 1) while executing 'export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install --env=inherit   bamtools'

Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 75, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 335, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 255, in configure_instance
    install_biolinux(options)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 279, in install_biolinux
    _perform_install(target=target, flavor=flavor, more_custom_add=options.get("custom_add", None))
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/fabfile.py", line 118, in _perform_install
    install_brew(flavor=flavor, automated=True)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/fabfile.py", line 308, in install_brew
    brew.install_packages(env, to_install=pkg_install)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 49, in install_packages
    _install_pkg(env, pkg_str, brew_cmd, ipkgs)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 87, in _install_pkg
    _install_pkg_latest(env, pkg, args, brew_cmd, ipkgs)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 205, in _install_pkg_latest
    raise ValueError("Failed to install brew formula: %s" % pkg)
ValueError: Failed to install brew formula: bamtools
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 255, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the installation issue. There was a new version of the cmake dependency released in homebrew and the pre-compiled bottle we'd prepared was not installing correctly. cmake can end up being tricky to build, so it is likely failing during the bamtools build here.

I pushed a fix to CloudBioLinux to resolve this: https://github.com/chapmanb/cloudbiolinux/commit/49c6a6b1b0af9033c48c6eb0b8424e3aea7fe55f If you remove any cached CloudBioLinux installs:
```
rm -rf tmpbcbio-install
```
and re-run, it should now pre-fetch the cmake dependency and work cleanly. Sorry about the issue and thanks much for reporting it.

**Comment by matted** [comment]
I'm seeing this same error when trying to build the Docker image from the current master branch.  I don't know how to tell if something in cloudbiolinux has changed, or if the Dockerfile isn't doing the right thing to pull in the fix discussed above.

**Comment by chapmanb** [comment]
Matt;
Sorry about the build problems. There were some changes to homebrew dependency resolution and it was trying to pull in pkg-config and failing. I pushed fixes to CloudBioLinux to avoid the issue, so if you re-build I confirmed everything works cleanly. Thanks much for the heads up on the issue.

**Comment by matted** [comment]
Great, it works now, many thanks.  A question related to this - what do you think about setting up an automated build repository on Docker Hub for bcbio-nextgen?  We have a fork set up and hooked to Docker Hub just to get automated Docker builds, but I think it would be cleaner to have it exactly up to date off the official repo.

Our use case is to build Docker images off your container, with a few internal changes for our environment.  We've also been starting off the bcbio-nextgen-docker-image.gz image on S3, but it's not clear (to me) when that's getting updated.  Thanks again.

**Comment by chapmanb** [comment]
Matt;
We'd definitely like to do automated builds and have both a development and release build (like the current non-docker code) that are official and obvious. Are you having good success building bcbio on Docker Hub and making it available through the Index? I'd tried this in the past but the bcbio-build containers were too big and timed out regularly. I will definitely revisit if things are working better.

We've been patiently waiting for user namespace support to push the Docker approach more. I think this is critical for wider adoption in local HPC, since root will be mapped to a non-privileged user. It's been getting delayed every release since 1.0 but is now scheduled for 1.7:

https://github.com/docker/docker/pull/12648

Thanks for all the interest and work on the Docker side.

**Comment by matted** [comment]
It's funny you should mention build problems on Docker Hub... in the past I recall that things were working decently, but our last few few builds there have failed with "Unexpected failure" messages (which I believe are problems on the Docker Hub side, and not the build instructions).  So maybe I can't be as optimistic about that solution, at least for now.  Our builds are here:

https://registry.hub.docker.com/u/giffordlab/bcbio-nextgen/builds_history/156924/

I completely agree with the Docker security issues.  It works for us only because we have a small and (approximately?) completely-trusted group, with minimal super-sensitive data on our systems.  I can see how it's almost a complete non-starter in larger settings, since Docker access is root access.  Here's hoping that upcoming versions of Docker address this...
