### ISSUE TITLE
Incorrect path in bwa_index.loc for custom genome

### ISSUE THREAD

**Issue by druvus** [chapmanb/bcbio-nextgen#798]
Hi,
I end up with incorrect paths in bwa_index.loc when I try to setup a custom genome using the following command. 

    bcbio_setup_genome.py -f MB0009.fa -g MB0009.gtf -i bowtie bowtie2 star seq bwa -n Ecoli -b MB0009

The path in the bwa index location file is lacking the genome name.

    MB0009  MB0009  MB0009  /media/data/bin/bcbio-nextgen/data/genomes/Ecoli/bwa/MB0009.fa

The path is correct in bowtie/bowtie2 indices location files. 

    MB0009  MB0009  MB0009  /media/data/bin/bcbio-nextgen/data/genomes/Ecoli/MB0009/bowtie2/MB0009
    MB0009  MB0009  MB0009  /media/data/bin/bcbio-nextgen/data/genomes/Ecoli/MB0009/bowtie/MB0009

Andreas

**Comment by roryk** [comment]
Hi Andreas,

Thanks for the report. Hmm, I can't seem to reproduce this:

```
 bcbio_setup_genome.py -f chr22.fa -n test-chr22 -b test-build -i bowtie2 bwa seq
```
lead to an entry like this:

```
test-build	test-build	test-build	/bcbio-nextgen/genomes/test-chr22/test-build/bwa/test-build.fa
```

**Comment by lpantano** [comment]
Rory,
I think the problem is only when you set up -g file.gtf.

there is this line that change dir: https://github.com/chapmanb/bcbio-nextgen/blob/master/scripts/bcbio_setup_genome.py#L190 after genome index, and `bwa` function in `cloudbiolinux` returns a relative `path` : `bwa/genome.fa`. 
Then the file doesn't exists when (inside `loc.py`) `os.path.abspath` exec and returns the wrong path that it doesn't exists.

one fix could be to add `os.path.abspath(index_fn(fasta_file))`. Or run the preprare-transcript inside the `build_dir`.

**Comment by roryk** [comment]
Thanks @lpantano and @druvus. You were right on about the cause of the error. I swapped the permanent os.chdir to a temporary one and that seems like it fixes the issue. Feel free to reopen if it didn't actually fix it. :)
