### ISSUE TITLE
add new module to bcbio-nextgen

### ISSUE THREAD

**Issue by szuszmok** [chapmanb/bcbio-nextgen#808]
Hi,
I would like to add an error-correction module to the pipeline. It could be configurated by editing the sample yaml file.
There are lots of error-correction algorithms that could improve the pipeline - at least, I think so, but correct me if I'm wrong, it's just an idea. I've selected algorithms which have fastq output, so it won't make the analysis pipeline unreasonably complicated.
Could this be useful in some way?

Thank you for any comment!

**Comment by chapmanb** [comment]
Thanks for the offers to help. We're always happy to get additional contributors. This page has a broad overview of the codebase and details about contributing so is a good place to get started:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/code.html

Practically, we haven't validated use of error correction algorithms upstream of variant calling. I haven't seen error correction applied upstream of variant calling by many groups, relying instead of the variant caller to identify and remove errors. It does seem to be primarily used for de-novo assembly, where it helps avoid assembly issues with incorrect kmers.

There was earlier discussion about using paired end read mergers like PEAR (http://sco.h-its.org/exelixis/web/software/pear/) for overlapping reads ends, but this is also a relatively uncommon case so we haven't explored it.

My suggestion would be to try some validations with error-corrected reads outside of coding into bcbio to see how it improves variant calling results. This could save you integration work if it doesn't help, or point you in the right directory of tools to use if it does help. Happy to help with any specific questions or work. Thanks again.

**Comment by roryk** [comment]
Thanks @szuszmok, closing this out because it is a little stale and not much action has been going with it. Feel free to reopen if work is ongoing. Thanks!
