### ISSUE TITLE
Add ambiguous read mappings which are generated by disambiguate to "final" data for upload

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#824]
In `disambiguate` settings, currently only the disambiguated read mappings are represented in the `final` output directory for upload. However, also the two ambiguous read mappings that are secondary outputs of [bcbio.pipeline.disambiguate](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/disambiguate/__init__.py#L124) are of interest for later quality control and should be archived. I therefore suggest that also these files are written to the final destination, in CRAM format if specified so in the analysis configuration (by also following the `archive: cram` setting that currently pertains to the main mapping, so no extra configuration option required). Note that in cases where no ambiguous read mappings were found, these secondary output files could be, in principle, empty (containing no reads, just the BAM header) - so the CRAM converter would have to be able to deal with such situations.

**Comment by mjafin** [comment]
I agree with you @schelhorn and the secondary species alignments can be of interest too (to see e.g. mouse stromal expression). They are in the work folder though so for the projects I've needed them I've just dug them out from there. Otherwise they would need to be chromosome sorted and CRAM compressed and am not sure if the overhead is always warranted.

**Comment by schelhorn** [comment]
Yes, that is certainly an option - but manual processing doesn't scale well if you work on hundreds of samples. Also, the sorting and compression overhead wouldn't be that high since the secondary files are expected to much significantly smaller compared to the disambiguated alignment.

**Comment by roryk** [comment]
Hi @schelhorn and @mjafin,

Thanks for the discussion. Part of the goal of having a separate work and upload directory is that at the end of an analysis you can nuke the work directory and be left with what you would need going forward. If the disambiguated reads are useful I think it makes sense to add them to the upload directory as well. It especially makes sense when the upload is a key/value type store like S3 and you're planning on scrapping everything else since they won't exist anywhere after the run on something like Amazon.

**Comment by chapmanb** [comment]
Sven-Eric, Miika and Rory;
Good suggestions and ideas. I pushed fixes now which will sort, merge and upload the additional output files from disambiguation. I did not tackle any of the CRAM finalization and these will still be in BAM format independent of that setting, but this hopefully provides the output data you need. Thanks again for all the suggestions.

**Comment by schelhorn** [comment]
Thanks!
