### ISSUE TITLE
Clarify behavior of GEMINI database creation for querying variation across samples

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#828]
I am currently running bcbio without batched samples and noticed that the GEMINI variation databases seem to be generated one-per-sample in the `final` project subdirectory for upload. I was wondering if this is intended behaviour since it reduces the utility of future GEMINI queries that ideally would operate across all samples. 

I noticed in the bcbio source code that additional merging of samples into GEMINI databases seems to take place with `batch`ed samples, so there seems to be functionality implemented for this. On the other hand, GEMINI may solely intended to be used here as filtering engine for VCF files, and users may be expected to merge VCF files across samples (or GEMINI databases) for themselves. All in all, the bcbio documentation does not seem to be very clear about this. 

Therefore, I would appreciate (1) a more detailed documentation of the GEMINI outputs depending on the analysis configuration and (2) a short description of the recommended workflow for generating variation reports across samples. In case the GEMINI outputs are generally suited for such across-sample reports, I'd (3) appreciate bcbio to prepare such a combined GEMINI database in the `final` directory for upload.

**Comment by chapmanb** [comment]
Sven-Eric;
You're right on with the bcbio/GEMINI integration: it creates merged databases of variants in the same batch. We don't try to do any bigger warehousing or integration across projects since bcbio projects don't necessarily correspond to a full set of variants, and it is getting into an additional difficult problem.

We generate `project-summary.yaml` files which contain metrics we use for summarizing variant calls across multiple analyses for many of our projects, but don't have any additional downstream tools for this.

Hope this helps clarify the current setup.

**Comment by schelhorn** [comment]
Alright, thanks for the clarification. I'll generate a combined GEMINI database myself then, based on merged VCFs (seems to be only how GEMINI can do it, no iterative adding of VCFs seems to be possible).

**Comment by roryk** [comment]
Hi Eric,

You probably want to also square off the variant files before loading them into GEMINI, otherwise you will have a lot of positions with missing genotypes. If a call is made in sample A and none of the others, then you won't know what the genotype is of any of the other samples at that position. Brad has something to do the squaring off here: https://github.com/chapmanb/bcbio.variation.recall.

**Comment by schelhorn** [comment]
Thanks for the heads up,@roryk. I'll probably do that and then query with GQT.

**Comment by stephenturner** [comment]
I'm stepping into this two years later - I now have a final output folder with a bunch of VCF files and separate gemini databases. Is the procedure you mentioned @roryk using @chapmanb's tool still the recommended practice here, or is there something now built into bcbio? 

> You probably want to also square off the variant files before loading them into GEMINI, otherwise you will have a lot of positions with missing genotypes. If a call is made in sample A and none of the others, then you won't know what the genotype is of any of the other samples at that position. Brad has something to do the squaring off here: https://github.com/chapmanb/bcbio.variation.recall.

I also couldn't find anything in the gemini docs about merging databases. @brentp or @arq5x any thoughts?

Thanks all.

**Comment by brentp** [comment]
gemini still requires merged VCFs. We don't have any plan to do anything else as it would first require "squaring off" and that's outside the scope of gemini.

Adding a squared off VCF might be possible, but there's no machinery in place to do that.

**Comment by chapmanb** [comment]
Stephen;
bcbio will produce a combined GEMINI database for samples analyzed together in the same `batch` (under `metadata`). It doesn't try to create a single combined database for all samples so the behavior is the same as previously discussed, along with the recommended manual process. As Brent mentioned GEMINI still requires squaring off and combining prior to loading.

Would it be useful for bcbio to have a second metadata parameter describing samples that it should combine and merge together into a single database? We haven't had many folks asking for this, so I'm trying to understand the use case and needs.

Thanks much for the discussion.

**Comment by stephenturner** [comment]
ah, thanks @chapmanb, didn't realize this. at this point, since the experiment was just some amplicon data, i'm just rerunning it adding an extra column to the csv i'm using for automated sample configuration. about the second metadata parameter, isn't this essentially what the batch parameter is doing?

**Comment by chapmanb** [comment]
Stephen -- if analyzing together in a batch works for you that is fabulous and is exactly how bcbio was meant to work. I suggested a potential additional parameter if you didn't want to analyze together but wanted bcbio to combine and create a global GEMINI database of multiple batches. This isn't something I'm sure is a great idea, I was only brainstorming, so glad the analyze together option works for you.
