### ISSUE TITLE
Remove .txt from the list of supported sequence file types

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#839]
Text files with the suffix .txt are currently auto-detected as sequence files by the bcbio.workflow.template routine. Upon presence of non-sequence text files such as readmes that often are co-located with sequence data, the templating process is confused. Since .txt is not a commonly assumed suffix for sequence files (and should indeed not be used for such data since it is not explicit regarding the type of the file content) I suggest it should be removed from this list in https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/workflow/template.py.

**Comment by roryk** [comment]
Hi Sven-Eric,

Thanks for all of your super good suggestions. I totally agree with you that .txt is terrible because it isn't explicit regarding the content of the file, but disagree that it is not commonly seen for sequence files, we see it a bunch unfortunately. I hope we can one day remove it too. :)

**Comment by schelhorn** [comment]
I see, in that case it's of course fine to keep them (and have wetlab people crash their workstations by opening 100GB of fastq with the Windows text editor ☺).

**Comment by roryk** [comment]
Hi Sven-Eric,

haha-- @mjafin had a great suggestion of using fastqdir/*.fastq.gz or whatever when you're using the template system instead of just pointing it at the directory, which won't pick up any stray text files that are in there.
