### ISSUE TITLE
Avoid using pip for upgrading bcbio-nextgen

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#847]
Rationale for this request: bad network connectivity for my machines. The problem with using `pip` is that it clones in a temporary directory, and if the upgrade fails (network lost or very slow download) it needs to do it all over again. By doing a checkout in the temporary dir used for installs, I can work around this problem (checking out things elsewhere, then copying).

An alternative would be to provide an option to skip upgrading bcbio-nextgen. When trying to update the data files I get often stuck due to the network issues because I'm forced to update also the code.

**Comment by chapmanb** [comment]
Luca;
We can't avoid pip for doing code upgrades, as this would require a lot of work to move every dependency to conda. I'm sympathetic to pip instability issues but don't think we have a reasonable way to work around it currently.

Regarding data upgrades, you should be able to do:
```
bcbio_nextgen.py upgrade --data
```
without updating the code. Let me know if that is still timing out due to pip and happy to adjust so it can work cleanly.

**Comment by lbeltrame** [comment]
The second approach works, thanks. Closing.
