### ISSUE TITLE
FASTQ download from S3 during sample preparation does not run in parallel

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#874]
Very curiously I just noticed that FASTQ download from S3 using `aws s3` (due to Frankfurt region) does not seem to proceed in parallel but serially. I just tried it both in `local` (multiprocessing) and in `ipython` (on a torque cluster) mode. In the `local` case, two jobs were configured to run (since two jobs fit into the constraint of the number of cores of the node for the `bwa, sambamba, samtools` parallel job that seems to define the required resources of `organize_samples`), but only one `aws s3` job actually ran in parallel. In the `iypthon` case, several engines were correctly started on the nodes (each with the resources of the initial  `bwa, sambamba, samtools`), but only one engine was doing the `aws s3` download while the remaining engines were alive and connected but just waiting for tasks. After `organize_samples`, the actual mapping etc. was then done in parallel as desired. I am at a loss and would really like (and need) parallel sample preparation. May this be due to a erroneous `organize_samples` task that only kicks in with FASTQs located on `aws` and somehow runs serially?

**Comment by chapmanb** [comment]
Sven-Eric -- sorry about the issues. You're correct about your interpretation of how things work. `organize_samples` isn't currently setup to parallelize over multiple machines. This is the initial step where bcbio reads the YAML file and sets up sample for processing, and the downloads currently happen as part of this. The download steps do make use of all the machine cores to pull down files in parallel.

As a result it would take some heavy refactoring to make the sample fastq downloads happen over multiple machines. I'm also not sure if this would start to saturate the shared filesystem and actually provide a big speedup over maxing out network reads and filesystem writes for each concurrently, so that would also take some experimentation.

So I can understand your concerns and suggestions but realistically am not sure we'll have the chance in the short term to test and refactor this since it would be an underaking. What kind of sample numbers/sizes are you running and what download times do you end up with?

Thanks again for the discussion and thoughts.

**Comment by schelhorn** [comment]
Alright, thanks a lot for the clarification. I usually process around 100-300 samples in parallel and have a file system that saturated at 10x1Gbit/s writes. Since that is more than a S3 download can achieve even using a maxed out config I was hoping to parallalize it. Using just one machine for that task is limiting out to less than 1Gbit/s. Given that I have a way to sync the files to the working directory prior to bcbio processing, is there a way that bcbio can recognize that the files are already there? Will out check for the files existence or can I perhaps manually add a checkpoint file to convince bcbio that sample prep is complete? It's all gzipped FASTQ anyway, so no additional conversion is required.

**Comment by schelhorn** [comment]
Other than bgzip'ing if required, that is.

**Comment by schelhorn** [comment]
Fine, I have moved FASTQ download from S3 as well as bgzip'ing and grabix-indexing to the torque by a pre-processor script that is limited to a number of PBS slots as to not overburden the file system. The script also generates the bcbio directory tree and moves the pre-processed files from the node-local tmp to the shared tree where bcbio expects them (in the S3 input and align_prep folders). Upon starting of bcbio on the shared tree, bcbio detects that the files are already present and directly proceeds with the alignment. Not the most elegant or robust solution (with regard to future changes in bcbio), but it works. If only `pbgzip` was in a better shape -- but I am digressing.

However, I'd still suggest that fully parallelized sample prep should be included in bcbio at a later time - especially since everything else in bcbio can nicely be distributed. bcbio sample prep is kind of the last roadblock.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks much for figuring out a workaround. This sounds like a perfectly reasonable to me. We don't have any plans to change the internal input data structures and if we do will look into having this file distribution happen within bcbio in a more parallelized manner. Thanks again.
