### ISSUE TITLE
Support for compressed fastq formats: LEON and QUARTZ

### ISSUE THREAD

**Issue by inti** [chapmanb/bcbio-nextgen#879]
Hi, 
large projects can use lots of disk space on the form of fastq files. There are a few alternatives for compression of fastq files. In particular LEON https://gatb.inria.fr/leon-read-compression/ allow lossless compression. I was wondering if it would be too difficult for you to add this as a input file. 

compressed files can be decompressed and used on streaming which I think is compatible with pretty much every aligner I have seen. I guess it boils down to recognising *.leon files and adding a decompressing command `leon -file read.fastq.leon -d ` and stream the data into the aligner. or maybe decompress it and then remove the fastq file after it has been used. 

From their website `As a concrete example of space saving, a 441 GB human fasta file weights only 39 GB after leon compression ! (whole genome sequencing with 102x coverage, SRR345593/SRR345594)`
So it could help when disk space or I/O are issues. 

Simialrly, quartz http://www.nature.com/nbt/journal/v33/n3/full/nbt.3170.html would help to reduce size of downstream BAM files by removing potentially redundant information from the quality scores. 

LEON does not actually change the final results in any way, if you use the lossless compression, but QUARTZ does. 

Thanks in advance

**Comment by chapmanb** [comment]
Inti;
Practically we don't have plans to support alternative FASTQ compression schemes. For FASTQ processing and parallelization we need indexed access to the reads, and use bgzipped FASTQ with grabix indexes (https://github.com/arq5x/grabix). This provides reasonable compression. The practical issue with using a nicer but less widely used alternative like LEON is that we'll need to uncompresss/recompress to do the indexing which mitigates the space advantages you get with it.

On the output side, we support CRAM which allows you to do lossy compression by reducing resolution of quality scores. We did some benchmarking of how this affects variant calling and alignment here:

http://bcb.io/2013/02/13/the-influence-of-reduced-resolution-quality-scores-on-alignment-and-variant-calling/

File formats are a place where you need to stick to standards, otherwise you end up converting back and forth. We'd happily pick up LEON or Quartz if they gain additional usage in the community.

**Comment by inti** [comment]
Brad: it sounds reasonably. Thanks, Inti
