### ISSUE TITLE
Possible to do non-root install on high performance cluster head node?

### ISSUE THREAD

**Issue by davemcg** [chapmanb/bcbio-nextgen#895]
I'm trying to install bcbio-nextgen on a HPC. Web access is only available on the login node. The install script (which I'm running with --isolate and --nodata) is being auto-killed for being too compute intensive. 

Specifically it is dying at perl /.../vep_convert_cache.pl -species homo_sapiens -version 79_GRCh37

The compute nodes don't have web access, so I can't run the script on them. 

I suppose the most straight-forward option is having the administrators of my cluster install the software?

**Comment by chapmanb** [comment]
Sorry about the issues, it sounds like you will need to discuss with your cluster administrators to find out the best way to build/install things. bcbio doesn't require root permissions, but does need a machine with web access and the ability to run compute without being killed. If your HPC environment doesn't want to support this the only workaround I can think of is to specifically run the failing commands on a compute node since they don't need web access, and then restart. Hope this helps some.

**Comment by lpantano** [comment]
Hopefully you could get this solved working with your rc help.

let us know if we can help in any other issue.

thanks a lot
