### ISSUE TITLE
python path bug?

### ISSUE THREAD

**Issue by kspham** [chapmanb/bcbio-nextgen#897]
Hi Brad,
I ran the sv pipeline and ran into this issue. Is it a bug in installation or something wrong with mine?
subprocess.CalledProcessError: Command 'set -o pipefail; cat /hive/groups/recon/projs/mus_strain_cactus/ragout/sv/129S1/work/prealign/129S1/129S1.rg.sorted-dedup-callable-callableblocks.bed | grep -v ^track | grep -v ^browser | /hive/groups/recon/projs/mus_strain_cactus/ragout/variant/anaconda/bin/py -x 'bcbio.variation.bedutils.remove_bad(x)' | sort -k1,1 -k2,2n > /hive/groups/recon/projs/mus_strain_cactus/ragout/sv/129S1/work/bedprep/tx/tmp486zGZ/129S1.rg.sorted-dedup-callable-callableblocks.bed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    bcbio.variation.bedutils.remove_bad(x)
AttributeError: 'module' object has no attribute 'bedutils'
grep: write error
grep: write error
cat: write error: Broken pipe
' returned non-zero exit status 2

**Comment by chapmanb** [comment]
Son;
Sorry about the issue. I'm confused to what is going on with your installation, since the `bcbio.variation.bedtools` module has been in the code for a while:

https://github.com/chapmanb/bcbio-nextgen/commits/master/bcbio/variation/bedutils.py

Do you have PYTHONPATH or PYTHONHOME or something else set that might be disrupting this? What version of bcbio are you running? Sorry to not have any better ideas but hope this helps some.

**Comment by roryk** [comment]
Hi @kspham,

Closing this out since it is pretty stale and I think you're all set. If not feel free to reopen. Hope all is well.

**Comment by kspham** [comment]
Yes, please close
