### ISSUE TITLE
parsing absolute path in project setup

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#907]
I was wondering if path parsing could be added to the project setup code.

i.e. 
```
# error
bcbio_nextgen.py -w template freebayes-variant projects/project1

# good
bcbio_nextgen.py -w template freebayes-variant project1

```

The same request for the sample csv file, but this seems trickier.
i.e.
```
# creates data/project1_csv.yaml which isn't what I was expecting  
bcbio_nextgen -w template projects/project1/config/project1-template.yaml data/project1.csv folder/*

```

**Comment by dwaggott** [comment]
Also, I just tried standard practice issuing these commands from within the upstream directory and it doesn't seem to parse my csv file name correctly.

Using the file `project_batch4_n24_fb_joint.csv` creates a new project called `project_batch4_n24_fb_joint_csv`

**Comment by chapmanb** [comment]
Daryl;
Thanks for the reports and sorry about the problems. It looks like there are two things going on:

- The confusing `*_csv` output occurrs when the input CSV was not found. This is poor behavior and I added a check to raise an error about the file being missing instead of doing this. Beyond that it sound readily handle CSV files in any location, not just in the current directory, as long as you provide the right path to them.
- When using a project name, not a CSV file, like `projects/project1` -- what is your expected output? Did you want it to write the output into the `projects` directory with `project1` as a name? I'd prefer not to make that change as it becomes inconsistent with how using `/path/to/the/metadata.csv` works, since that writes to the current directory, not `/path/to/the`. I made a fix so if you specified a path for a project name, it uses the final base name (`project1`) and ignores the path. My suggestion is to always run the template functionality from the directory you want the output in, which keeps the outputs from bcbio templating a bit easier to understand without adding more cases.

Thanks for the feedback and hope this helps.
