### ISSUE TITLE
Processing failed on GEMINI chunk load

### ISSUE THREAD

**Issue by mpschr** [chapmanb/bcbio-nextgen#910]
Hi

Another problem occured with the GEMINI population. Everything seems to be running fine, until some tmporary files are not found upon unlinking and possibly cause an error. Maybe you can identify what the real problem is?

The whole log is here:
https://gist.github.com/mpschr/3799977323769ee2c1b5#file-bcbio_nextgen-log

**Comment by chapmanb** [comment]
Michael;
Sorry about the issue, I'm not exactly sure what is causing this. It looks like GEMINI is writing with the temporary directory set to `/tmp`? A couple of thoughts/questions:

- Is it possible there is a cronjob that cleans up `/tmp` on the machine which removed these in the middle of processing?
- What version of GEMINI are you running?
- Do you have a specific temporary directory set for bcbio?

Sorry about the issues and hope this helps us get to the root cause of the issue. If you're really stuck and don't need gemini results you can also do `tools_off: [gemini]` in the `algorithm` section to get the rest of the analysis done. Thanks again.

**Comment by mpschr** [comment]
Hi Brad.

The bug must be related with continuing the run of the pipeline. I've renamed the work-folder and restarted the whole variant2-pipeline, and it seems that everything has run just fine and the pipeline has finished.

Regarding your questions:

 - Since a whole run worked out nicely, I think the cronjob can be excluded
 - gemini 0.16.0
 - If the temp dir is the same as workdir, then it is called 'scratch'. Other than that I have no specific settings.

If I can try to eliminate some specific files to gemini and try a rerun and see if it helps. But I'd need your advice on this.

I hope this helps

**Comment by chapmanb** [comment]
Michael;
Glad the re-run worked cleanly for you. It sounds like there was some kind of automatic processing cleaning up local files in `/tmp` which resulted in those getting removed. I checked in a fix in GEMINI to ensure these intermediate files also use the project specific temporary directory (instead of the system temporary directory) to avoid this issue in the future. Thanks again for the detailed report and patience debugging this.
