### ISSUE TITLE
bcbio dir and tool dir

### ISSUE THREAD

**Issue by YiChingTang** [chapmanb/bcbio-nextgen#920]
hi, 
I assign the same path for /path-to-bcbio and /path-to-bcbio-tool while installing with isolate mode. 
The main installation went smoothly without any error message, but when I want to add other tools the following message return.

Do you suggest me to re-install and assign different path?
btw, this error happens when I install GEMINI and CADD, dbnsfp, while it shows nothing when installing GATK.

ValueError: Default tool directory not yet saved in config defaults. Specify the '--tooldir=/path/to/tools' to upgrade tools. After a successful upgrade, the '--tools' parameter will work for future upgrades.

**Comment by chapmanb** [comment]
Sorry about the problems. Assigning the same path to both isn't a problem and should work. My guess is that none of the installs finished completely cleanly, since bcbio writes the configuration file with `tooldir` at the end of the process. My suggestion would be to either re-run the base install process or one of the upgrades with `--tooldir` specified as the initial value. If everything works cleanly, you should get a `/path/to/bcbio/config/install-params.yaml` file with `tooldir` in it, which should get things working for all future calls to bcbio. Hope this helps.

**Comment by roryk** [comment]
Closing this out because it should be working okay and this is pretty old. Feel free to reopen if it is still an issue. Thanks!
