### ISSUE TITLE
Could not find the main class: org.broadinstitute.gatk.tools.CatVariants

### ISSUE THREAD

**Issue by funnell** [chapmanb/bcbio-nextgen#928]
I installed GATK 3.4 and tried running the tests. One of the errors I received is
````
Could not find the main class: org.broadinstitute.gatk.tools.CatVariants
````
I tried to install GATK 3.2 instead but that didn't seem to work so I've tried to replace version 3.4 with version 3.2. I'm still getting the above error, so I'm at a loss.

**Comment by chapmanb** [comment]
Sorry about the issues. I'm confused about the error message since it shouldn't be dependent on the version of GATK you install manually. CatVariants gets called in bcbio from `gatk-framework`, our little distribution of only the MIT licensed parts of GATK (https://github.com/chapmanb/gatk). Can you confirm this doesn't work from the commandline:
```
gatk-framework org.broadinstitute.gatk.tools.CatVariants --help
```
Sorry to not have a better clue of what is wrong. Could you post the full traceback you get from bcbio? What type of system are you running on? Hope this helps some.

**Comment by funnell** [comment]
Ok here is the gist of that command's output: https://gist.github.com/funnell/e7200d6f344313df38a5
Something about an unsupported major.minor version?

**Comment by chapmanb** [comment]
Thanks for the detailed traceback. That error means you have an incompatible Java version. GATK only works with java 1.7. It sounds like you have 1.6 on your PATH. If you update to 1.7 everything should work cleanly. Please let us know if you run into any other problems.

**Comment by funnell** [comment]
You are probably right, but my java version says 1.7:
```
$ java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
```
Is there somewhere in the bcbio-nexgen config files that I can look to see which java binary is being used?

**Comment by chapmanb** [comment]
Apologies about that, I should have also mentioned that `JAVA_HOME` should be set to point at your Java 1.7 version (or not set with `unset JAVA_HOME`) or it will preferentially pick that up. I added details about this to the documentation as well:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#gatk-or-java-errors

Hope this gets you going.

**Comment by funnell** [comment]
That fixed it, thanks!
