### ISSUE TITLE
parallel: queue name not found

### ISSUE THREAD

**Issue by funnell** [chapmanb/bcbio-nextgen#933]
I'm running this command:
```
bcbio_nextgen.py config/test.yaml -t ipython -n 48 -s sge -q comp1.q -q comp2.q
```
and seeing this message:
```
No cluster queue or queue instance matches the phrase "comp2"
```
It seems like the ".q" part is being removed? This doesn't stop execution though.

**Comment by roryk** [comment]
Hi @funnell,

Sorry for the problems. I think you are seeing that message because it tries both with the .q and without the .q. Does comp2.q exist? I see you have two -q parameters in the call, does comp1.q work?

**Comment by funnell** [comment]
Both comp1.q and comp2.q (should) exist:
```
$ qconf -sql
WTSS.alignments.q
all.q
comp0.q
comp1.q
comp2.q
fusions.q
heavyio.q
interact.q
```

I've specified both because I would like to use nodes in either queue. I've used both of these queues in the past, although not with bcbio-nextgen (I'm a new user).

**Comment by roryk** [comment]
Thanks @funnell,

Sorry to remote debug like this, I don't have access to SGE so I'm just guessing. There is a part in the code that is trying to figure out which parallel environment is set up and it is parsing the SGE conf. Could you paste in the output to ```qconf -sql comp1.q``` and ```qconf -sql comp2.q``` in a gist? It is parsing the output here: https://github.com/roryk/ipython-cluster-helper/blob/master/cluster_helper/cluster.py#L382 and is checking for which parallel environment can work with the queue. I'm thinking something in there is failing.

**Comment by roryk** [comment]
Oh, nevermind, I'm dumb. This comes up because it checks with and without the .q, so the one without the .q throws up an error message but the one with the .q works. It should keep working fine, just with that disconcerting message when it checks for the one that doesn't exist. Thanks for reporting it; I'll close this and if it is actually interfering with it running, feel free to open it back up. Thanks!

**Comment by roryk** [comment]
It is funny because I solved this issue before and forgot. :) https://github.com/roryk/ipython-cluster-helper/issues/15

**Comment by tombair** [comment]
Not sure if I should report this here or with ipython but I ran into this again. It is due to code in bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py. The code there looks like it originates with bcbio but I think you have fixed it and it has not gotten all the way through the pipe to them.

I had a similar error to above and made a crude fix to the above script and fixed it

crude fix:
`def _find_parallel_environment(queue):
 337     """Find an SGE/OGE parallel environment for running multicore jobs in specified queue.
 338     """
 339     base_queue = os.path.splitext(queue)[0]
 340
 341     #queue = base_queue + ".q"  #tb added line below
 342     queue = base_queue
 343     available_pes = []
 344     for name in subprocess.check_output(["qconf", "-spl"]).strip().split():
 345         if name:
 346             for line in subprocess.check_output(["qconf", "-sp", name]).split("\n"):
 347                 if _has_parallel_environment(line):
 348                     if (_queue_can_access_pe(name, queue) or _queue_can_access_pe(name, base_queue)):
 349                         available_pes.append(name)
 350     if len(available_pes) == 0:
 351         raise ValueError("Could not find an SGE environment configured for parallel execution. "
 352                          "See %s for SGE setup instructions." %
 353                          "https://blogs.oracle.com/templedf/entry/configuring_a_new_parallel_environment")
 354     else:
 355         return _prioritize_pes(available_pes)
 356`

Let me know if you would rather have me submit to ipython, again your fix is in place queue just gets overwritten with %s.q again

**Comment by roryk** [comment]
Hi Tom,

Could you post the actual error? The code right below it checks for both the `.q` and without the `.q` extension so it should work without the fix.

**Comment by tombair** [comment]
The error I get is:

[tbair@neon-login-0-2 work]$ bcbio_nextgen.py -n 16 -t ipython -q IIHG -s sge ../config/K00274.yaml
[2016-03-22T19:19Z] neon-login-0-2.local: Resource requests: bwa, sambamba, samtools; memory: 2.00, 2.00; cores: 16, 16, 16
[2016-03-22T19:19Z] neon-login-0-2.local: Configuring 1 jobs to run, using 16 cores each with 32.1g of memory reserved for each job
No cluster queue or queue instance matches the phrase "IIHG.q"
No cluster queue or queue instance matches the phrase "IIHG.q"
No cluster queue or queue instance matches the phrase "IIHG.q"
No cluster queue or queue instance matches the phrase "IIHG.q"
No cluster queue or queue instance matches the phrase "IIHG.q"
No cluster queue or queue instance matches the phrase "IIHG.q"
No cluster queue or queue instance matches the phrase "IIHG.q"
No cluster queue or queue instance matches the phrase "IIHG.q"
No cluster queue or queue instance matches the phrase "IIHG.q"

and the code snip, with 1 commented it works with 2 commented it does not -- and I added 2 it is not part of the code base. Again this is in bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py so not your codebase but part of the bcbio install

   base_queue = os.path.splitext(queue)[0]
##TBedit
1-->    #queue = base_queue + ".q"
 2-->   queue = base_queue
    available_pes = []
    for name in subprocess.check_output(["qconf", "-spl"]).strip().split():


Hope that helps

**Comment by roryk** [comment]
Hi Tom,

It will say that error when it checks the one with the .q, but will try the name without the .q when that one fails, so this error is harmless. Does this prevent anything from running?

**Comment by tombair** [comment]
It does not stop things from running but I was chasing down an error and the warning was concerning.

**Comment by roryk** [comment]
Great-- this warning might be a red herring. Happy to help chase down the error if you can post that up as well.

**Comment by tombair** [comment]
Sure, should I start a new issue?

**Comment by roryk** [comment]
Sounds good, thanks!
