### ISSUE TITLE
Merge extras in disambiguation-postprocessing may not run in parallel

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#979]
It seems to me as if this section in [bcbio.pipeline.disambiguate.resolve()](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/disambiguate/__init__.py#L64) is not running parallel. Could it be changed so that all disambiguated BAMs are merge-sorted in parallel rather than on only one node?

```python
dis2 = run_parallel("disambiguate_merge_extras", [[disambigs, disambigs[0]["config"]]])
```

**Comment by chapmanb** [comment]
Sven-Eric -- thanks for catching this. I pushed a fix which first splits up by samples, then runs the merge in parallel over each sample. Please let me know if you run into any problems with this. I'm always a bit nervous coding on the disambiguate parts since I don't have any real cases to test on. Thanks again.

**Comment by schelhorn** [comment]
Excellent, thank you. I'll test.
