### ISSUE TITLE
cURL headers required for Git

### ISSUE THREAD

**Issue by verdurin** [chapmanb/bcbio-nextgen#984]
I'm trying a new installation on a CentOS 7.1 VM and it breaks on the compilation of Git. It appears that the RPM 'libcurl-devel' is required, so this should be added to the list of requirements.

A Git RPM was installed already.

**Comment by chapmanb** [comment]
Adam;
Apologies about the problem and thanks for the report. We install Git to avoid issues with brew not working with older versions. Instead of always installing it, I adjusted it to only try the install if the system git is too old. This'll hopefully avoid the issue for up to date systems.

I also expanded the documentation on the libcurl requirement here:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#isolated-installations

Thanks again for letting us know.
