### ISSUE TITLE
Controlling input and output metadata

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#999]
Greetings,
 Im trying to avoid writing my own automated project configuration, but the process provided with bcbio seems to make too many assumptions sometimes, or does not allow enough customized pathing. But Im hoping I just do not know how to properly use it.

My fastq and readgroup 'ID' naming scheme is slightly different than what the docs assume it will be using 'samplename' in the project.csv to find fastq files. Is there a way for me to provide a pair of fastq.gz files to use for each sample in the project.csv? I cant exactly put /path/to/fastq_1_ACGTGC.fastq.gz,/path/to/fastq_2_ACGTGC.fastq.gz.

I noticed that it creates folders such as 'project_2015-09-01' with project run information, which is great, but can I specify I would like these in a different directory? Maybe I could substitute 'project' with something as well?

A few of my projects are continuous so I run samples over time in batches, but they are all under the same "project" title. I prefer to keep all sample results to go to the same final folder while keeping analysis metadata separate. This is all personal preference so if the answers to any of these questions are 'no', I will only rage internally. Thank you!

**Comment by roryk** [comment]
Hi @bwubb,

Sorry that it isn't working out of the box. I'm a little unclear on what it is doing wrong in terms of pairing up the files, how are read1 and read2 denoted in your file naming scheme? Maybe we could add support for your scheme if it is something more general.

I'm also a little unclear on what you were hoping for the project directory at the end of the run. Right now what that does is store some generalized data about the run; if you add samples and rerun it, some of that data won't be correct. For example if there is a file with summary information with all of the samples, and a new sample is added, that summary file won't be updated properly with the new sample which will lead to some problems later on down the road.

Let me know if I'm not understanding. I think it is coffee time.

Thank you for taking time to post feedback and suggestions, it is very helpful even if we end up not being able to accommodate.

**Comment by bwubb** [comment]
Hi @roryk,

 Thank you for the reply. bcbio is working for me, just that it seems like I will need change up my project dir organization and conform to something more bcbio friendly.

I have the advantage of being able to queue and run 100+ seq data simultaneously, as joint variant calling is not needed. But since I generate a config.yaml for each sample bcbio will treat each sample as its own project. I was looking for a way to take something like the created dir `project_name/final/project_2015-08-13` and A) name it something with a bit more specific and B) update its contents (including project-summary.yaml) with every sample config.yaml executed under the project_name dir.

The fastq naming is nothing obscure, SampleID_RunID_[1-8]_[1,2]_barcode.fastq.gz. This is the result of the demultiplexed files our sequencing core gives, therefore I wrote my alignment inputs from this.

These are just personal use issues and there are some obvious solutions staring at me, just looking to see how flexible the included code was. Thanks.

**Comment by roryk** [comment]
Hi @bwubb,

Great, glad it is working. I think for the updating the project directory, it would be tough to do that since there are some global statistics that get calculated that need all of the samples to be present. We could add something to put in a custom name instead of the project-default type naming though, but I'm not sure that would get you any closer to a good solution.

Gotcha-- I see, yeah that naming scheme will not be parsed correctly by the code that pairs the samples together. The reason why is that it just guesses that any two files that differ only by 1 or 2 or R1 or R2 are paired. So in your instance SampleID_RunID_1_1 and SampleID_RunID_2_1 will get paired together I think. What we usually do for files like this as a workaround is create a directory that has symbolic links that are named less ambiguously that link back to the original files. Sorry that isn't a great solution. I can't think of an easy way to support figuring out what pairing is correct automatically very easily for these samples. Maybe we could pair them all up and then go through the pair list and look for pairs > 2 and see if we can figure out something from that. Could you post up an example YAML file that is incorrectly generated so I can use it to test against?

**Comment by bwubb** [comment]
I take it back, bcbio is not working on my HPC cluster. I will definitely post an example incorrect yaml, but first would you be able to explain to me what is going on?

`Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 75, in _run_toplevel
    pipelines, config = _pair_samples_with_pipelines(run_info_yaml, config)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 430, in _pair_samples_with_pipelines
    del sample["files"]
TypeError: 'str' object does not support item deletion
`

The same sample data I was successful with on my local server flips out when trying to run on HPC.

**Comment by chapmanb** [comment]
Brad -- this error looks like you passed an incorrect run info YAML file as input to `bcbio_nextgen.py`. Could you pass along the command line used for the HPC run? Maybe there is a typo in there we could spot. There shouldn't be any differences in running locally versus on a cluster in terms of parsing the input file. Hope this helps.

**Comment by bwubb** [comment]
My command would just be `bcbio_nextgen.py ../config/CM214MP4MouseNum3571.yaml -n 4`

But I think I figured out the issue:

`details:`
  `- analysis: variant2`

Apparently that - is very important and was not just a stylistic choice. I do not know if it will run all the way through yet, but at least it doesnt break right away. Are there any other sections of the .yaml which might be similarly configured?

**Comment by chapmanb** [comment]
Brad;
That's right on. The configuration file is in YAML format (https://en.wikipedia.org/wiki/YAML) so the syntax is important. The automatic configuration generation code is meant to make this easier by only having to prepare CSV files instead of YAML:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#automated-sample-configuration

Hope this helps.
